#import "/templates/blog.typ": *
#import "/templates/enums.typ": *
#import "@preview/pintorita:0.1.4"
#import "/templates/mod.typ": typ_frame

#show raw.where(lang: "pintora"): it => pintorita.render(it.text)

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/en/meta/2025/hello-world.typ
// source_sha256: sha256:65dbf04987df727f53d31a10a943fd383589043af5449e6c16f1929bbdddc659

#show: main.with(
  title: "你好",
  desc: [我的新博客首发，带着新主题和新外观。],
  date: "2025-08-24",
  tags: (

    blog-tags.life,
    blog-tags.typst,
  
  ),
  lang: "zh",
  i18nKey: "meta/2025/hello-world",
  sourceLang: "en",
  translationSourceHash: "sha256:65dbf04987df727f53d31a10a943fd383589043af5449e6c16f1929bbdddc659",
  translationStatus: "machine",
)

= 你好，世界！

这是一篇测试用文章，用来测试评论功能。

// #html.elem("div", attrs: (class: "pintora-diagram flex justify-center"))[
//   #html.frame[
//     #import "@preview/chronos:0.2.1"
//     #align(center)[
//       #chronos.diagram({
//         import chronos: *
//         _par("爱丽丝", color: red)
//         _par("鲍勃", color: blue)

//         _seq("爱丽丝", "鲍勃", comment: "你好", color: green)
//       })
//     ]
//   ]
// ]

#figure(caption: "序列图示例", kind: image)[
  #typ_frame("pintora-diagram flex justify-center")[
    #show raw.where(lang: "pintora"): it => pintorita.render(it.text, style: "dark")
    ```pintora
    sequenceDiagram
    autonumber
    participant [<actor> 用户]
    用户->>Pintora: 给我画一个序列图（使用DSL）
    activate Pintora
    Pintora->>Pintora: 解析DSL，绘制图表
    alt DSL 是正确的
      Pintora->>用户: 返回绘制的图表
    else DSL 是不正确的
      Pintora->>用户: 返回错误信息
    end
    deactivate Pintora
    @start_note left of Pintora
    根据渲染目标的不同输出格式
    1. 在浏览器端，输出SVG或Canvas
    2. 在Node.js端，输出PNG文件
    @end_note
    ```
  ]
]
