#import "/templates/blog.typ": *
#import "/templates/enums.typ": *
#import "@preview/kouhu:0.2.0": kouhu

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/en/meta/2025/syntaxes.typ
// source_sha256: sha256:e9412943cc93fd5d9c07c39c6279ef83085045442b091a41a3b362221cd92613

#show: main.with(
  title: "Typst 语法",
  desc: [Typst 语法列表，用于渲染测试。],
  date: "2025-05-27",
  tags: (

    blog-tags.programming,
    blog-tags.typst,
  
  ),
  lang: "zh",
  i18nKey: "meta/2025/syntaxes",
  sourceLang: "en",
  translationSourceHash: "sha256:e9412943cc93fd5d9c07c39c6279ef83085045442b091a41a3b362221cd92613",
  translationStatus: "machine",
)

= 原始块

#quote(block: true)[
  这是一个内联原始块 `class T`。
]

== 示例

=== 内联原始块

==== 块定义

这是一个内联原始块 `class T`。

这是一个内联原始块 ```js class T```。

这是一个长的内联原始块 ```js class T {}; class T {}; class T {}; class T {}; class T {}; class T {}; class T {}; class T {}; class T {};```。

Js 语法高亮由 syntect 处理：

```js
class T {};
```

Typst 语法高亮在内部特别处理：

```typ
#let f(x) = x;
```

= 自定义块

你好？

#kouhu(length: 50)

$"H3" Delta = 2$

$ "ax"^2 + "bx" + c = 0 $

aaa

```elixir
f("foo")

def foo do
  "bar"
end
```
