#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/en/tutorials/2025/make-nbis-thread-safe.typ
// source_sha256: sha256:2487222fa7f0c680fa85ce5fdb87f3d66561f95ee20b9bf5786b3cf9f7831fc8

#show: main.with(
  title: "使 NBIS 的 wsq_decode_mem 线程安全",
  desc: [通过修改源代码使其线程安全],
  date: "2025-09-15",
  tags: (

    blog-tags.programming,
    blog-tags.clang,
  
  ),
  lang: "zh",
  i18nKey: "tutorials/2025/make-nbis-thread-safe",
  sourceLang: "en",
  translationSourceHash: "sha256:2487222fa7f0c680fa85ce5fdb87f3d66561f95ee20b9bf5786b3cf9f7831fc8",
  translationStatus: "machine",
)

最近，我正在进行一个解码 WSQ 文件的项目，这需要使用 NBIS 的 wsq_decode_mem 函数。但我发现这个函数不是线程安全的。在与 AI 编码后，我对源代码进行了几处修改，使其线程安全。

= 问题

该函数不是线程安全的，因为它使用了几个全局静态变量来存储解码器的状态。当我的程序并行运行时，这些变量会被不同的线程覆盖，导致解码器崩溃。

= 解决方案

修改源代码以使用线程局部变量。

在 `imgtools/include/wsq.h` 中插入，

```c
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
#define WSQ_TLS _Thread_local
#elif defined(__GNUC__) || defined(__clang__)
#define WSQ_TLS __thread
#else
#define WSQ_TLS
#warning "没有线程局部存储；WSQ 解码将不是线程安全的。"
#endif
```

在 `imgtools/include/wsq.h` 中，用线程局部变量替换全局静态变量，

```c
extern int debug;
extern WSQ_TLS QUANT_VALS quant_vals;
extern WSQ_TLS W_TREE w_tree[];
extern WSQ_TLS Q_TREE q_tree[];
extern WSQ_TLS DTT_TABLE dtt_table;
extern WSQ_TLS DQT_TABLE dqt_table;
extern WSQ_TLS DHT_TABLE dht_table[];
extern WSQ_TLS FRM_HEADER_WSQ frm_header_wsq;

/* hifilt/lofilt 是只读常量，因此无需更改 TLS */
extern float hifilt[];
extern float lofilt[];
```

在 `imgtools/src/lib/wsq/globals.c` 中，用线程局部变量替换全局静态定义，

```c
#ifdef TARGET_OS
   WSQ_TLS QUANT_VALS quant_vals;

   WSQ_TLS W_TREE w_tree[W_TREELEN];

   WSQ_TLS Q_TREE q_tree[Q_TREELEN];

   WSQ_TLS DTT_TABLE dtt_table;

   WSQ_TLS DQT_TABLE dqt_table;

   WSQ_TLS DHT_TABLE dht_table[MAX_DHT_TABLES];

   WSQ_TLS FRM_HEADER_WSQ frm_header_wsq;
#else
   WSQ_TLS QUANT_VALS quant_vals = {};

   WSQ_TLS W_TREE w_tree[W_TREELEN] = {};

   WSQ_TLS Q_TREE q_tree[Q_TREELEN] = {};

   WSQ_TLS DTT_TABLE dtt_table = {};

   WSQ_TLS DQT_TABLE dqt_table = {};

   WSQ_TLS DHT_TABLE dht_table[MAX_DHT_TABLES] = {};

   WSQ_TLS FRM_HEADER_WSQ frm_header_wsq = {};
#endif
```

在 `imgtools/src/lib/wsq/decoder.c` 中，在 `nextbits_wsq` 和 `getc_nextbits_wsq` 中用线程局部变量替换静态变量，

```c
static WSQ_TLS unsigned char code;   /*下一个数据字节*/
static WSQ_TLS unsigned char code2;  /*填充的数据字节*/
unsigned short bits, tbits;  /*请求的当前数据字节的位*/
int bits_needed;     /*完成请求所需的附加位*/

                          /*用于从数据流中“屏蔽”n个
                            位*/
static unsigned char bit_mask[9] = {0x00,0x01,0x03,0x07,0x0f,
                                    0x1f,0x3f,0x7f,0xff};
```

`bit_mask` 是只读常量，因此无需更改 TLS。

`code` 和 `code2` 变量分别用于存储下一个数据字节和填充的数据字节。更改 TLS 后，这些变量将存储在线程局部存储中，因此不会被不同的线程覆盖。

= 结果

多线程问题解决了 :-)

在修改了这些变量后，`wsq_decode_mem` 函数现在是线程安全的，因此我在我的项目中构建并使用了它，多个线程运行良好。
