#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2018/origin-download-speedup.typ
// source_sha256: sha256:95d5eb603749f0acd2675714bbcc359db9d7cb7d3dfa18f9d3cda24444b518d0

#show: main.with(
  title: "Download Acceleration for Origin in China",
  desc: [Download Acceleration for Origin in China],
  date: "2018-11-18",
  tags: (

    blog-tags.game,
    blog-tags.tooling,
  
  ),
  lang: "en",
  i18nKey: "tutorials/2018/origin-download-speedup",
  sourceLang: "zh",
  translationSourceHash: "sha256:95d5eb603749f0acd2675714bbcc359db9d7cb7d3dfa18f9d3cda24444b518d0",
  translationStatus: "machine",
)

Open the `EACore.ini` file located in the Origin installation directory (default `C:\Program Files(x86)\Origin`), and copy and paste the following content:

```ini
[connection]
EnvironmentName=production

[Feature]
CdnOverride=akamai
```

Save and close the file, then restart Origin. I tested it and the download speed can reach full speed.
