name = "wonderland"
account_id = "8bafdbd1f2d967917dbc0a67156266fa"
compatibility_date = "2025-05-31"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

# [[d1_databases]]
# binding = "DB"                  # 代码里用 env.DB 访问
# database_name = "blog-ugc"
# database_id = "fc8ede2f-f73f-454a-a55b-4187a8ced702"

[[d1_databases]]
binding = "DB"
database_name = "wonderland"
database_id = "2c79f3b3-ebc3-412c-a17d-3be2cdc53a28"
