#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/life/2018/wwdc-2018-keynot-review.typ
// source_sha256: sha256:87facd61949b1cce482cce9f774fa147e09ba2b9b403ea171d645c3476fb10f7

#show: main.with(
  title: "Personal Summary of WWDC 2018 Keynote",
  desc: [Personal summary of the WWDC 2018 Keynote, covering iOS 12, watchOS 5, tvOS, and macOS Mojave.],
  date: "2018-06-06",
  tags: (

    blog-tags.apple,
    blog-tags.misc,
  
  ),
  lang: "en",
  i18nKey: "life/2018/wwdc-2018-keynot-review",
  sourceLang: "zh",
  translationSourceHash: "sha256:87facd61949b1cce482cce9f774fa147e09ba2b9b403ea171d645c3476fb10f7",
  translationStatus: "machine",
)

The images in this article are from #link("https://mp.weixin.qq.com/s/mwhcO9MI2mD5mxNICqiMCg")[ifanr - Apple WWDC 2018: The most comprehensive summary is here, don't miss any highlights]

The opening stated, "Today is all about software." I was a bit disappointed as I was expecting some hardware updates, but it's not a big deal.

= iOS 12

== Hotfix

First is the system speedup; indeed, iPhones feel slower over time, and it seems Apple is finally taking this issue seriously. They also addressed the device slowdown issue, and support extends to the iPhone 5s, which I think shows at least some sincerity.

#figure(image("/public/assets/img/2018/06/640.jpeg"))

#figure(image("/public/assets/img/2018/06/640-2.jpeg"))

== AR

Apple released a new model format `USDZ`, which includes model and animation data. My guess is that it should be similar to the current `Direct X` `X` file format, used for one-stop storage of all related data for a single model or scene, for model data management in 3D applications. This can also be considered part of Apple's software ecosystem, and it seems `Metal` might still have a chance in the gaming field.

#figure(image("/public/assets/img/2018/06/640-36.jpeg"))

AR games now have multiplayer and spectator modes, providing more options for gatherings and team-building activities.

#figure(image("/public/assets/img/2018/06/640-3.jpeg"))

== Photos

Learning from Google, the Photos app has become smarter, meaning more automatic recommendation options, including search and organization. These are minor issues, but what's newer is the ability to recommend shareable content, helping you choose a few photos that are more suitable for sharing. Moreover, the recipient can share back similar photos based on what they received. Upon reflection, this is actually a pretty good feature, allowing a more complete record of a group activity on everyone's phones. However, after losing part of my iCloud photos, I have lost interest in this app, and my main photo storage is now on Dropbox.

#figure(image("/public/assets/img/2018/06/640-4.jpeg"))

#figure(image("/public/assets/img/2018/06/640-5.jpeg"))

BTW, photo sharing is also end-to-end encrypted, and I feel quite secure with Apple's security technology.

== Siri

Siri, widely recognized as the "artificial intelligence disability," is increasingly moving away from being just a voice command assistant...

This time, the `Shortcuts` feature was released. As I understand it, this allows a specific function to be created as a voice command _exception_, so when invoking Siri, it can basically skip the semantic analysis process and directly output results, somewhat similar to a function call.

In addition, Apple also allows users to create their own `Workflow`, which is essentially bundling a series of functions into one command for easy one-time invocation.

These two features are essentially part of Siri's own functionality, so devices that can invoke Siri, like the HomePod and Apple Watch, can use this feature. I speculate this feature could have a significant impact on future smart homes.

#figure(image("/public/assets/img/2018/06/640-6.jpeg"))

#figure(image("/public/assets/img/2018/06/640-7.jpeg"))

== Built-in Apps

Apple updated its four built-in apps - News, Stocks, Voice Memos, and iBooks (now renamed Apple Books) - which are honestly quite useless to me, as they are the kind of apps I never open. However, it's worth mentioning that the Stocks app integrates news, allowing users to see financial news related to specific stocks, which might help stock traders understand market trends.

#figure(image("/public/assets/img/2018/06/640-8.jpeg"))

#figure(image("/public/assets/img/2018/06/640-9.jpeg"))

== CarPlay

CarPlay has opened up to third-party navigation software, which is great, but I still don't have a car.

#figure(image("/public/assets/img/2018/06/640-10.jpeg"))

== Anti-Addiction

First, the `Do Not Disturb` mode can now support scheduled automatic exits, which is just a compensatory feature for previous shortcomings. Additionally, at night while sleeping, notifications will be silenced and hidden, so you won't wake up and see notifications that keep you from falling back asleep.

#figure(image("/public/assets/img/2018/06/640-11.jpeg"))

Next is the improvement in notification display. In iOS 12, notifications can be grouped, so you won't see a long list of notifications when the screen lights up, pushing potentially urgent notifications out of sight. Notifications can also be `silenced, with no pop-ups, no red dots, and of course, no sounds`; the display and handling of notifications have also been made smarter, with the system providing intelligent reply suggestions or prioritizing potentially urgent notifications for the user.

#figure(image("/public/assets/img/2018/06/640-12.jpeg"))

#figure(image("/public/assets/img/2018/06/640-13.jpeg"))

Next is the legendary _anti-addiction_ system. In iOS 12, you can see your daily usage of applications on your phone, giving you an intuitive understanding of which apps consume a lot of your time, and you can also set usage time limits for specific applications, making it easier to reduce phone usage.

#figure(image("/public/assets/img/2018/06/640-14.jpeg"))

Additionally, there are settings for children, such as parents being able to see their child's daily phone usage and limit their time on specific applications. Kids who are addicted to their phones may find their good days coming to an end.

== Emoji

Apple's efforts in promoting and using Emoji are quite significant. This time, the updated version of Emoji, Animoji, added several new characters and introduced tongue detection.

#figure(image("/public/assets/img/2018/06/640-15.jpeg"))

Next is my favorite part - Apple announced the new `Memoji` technology, allowing users to create their own Animoji and use them in video chats, which have evolved into group chats of up to 32 people. Want to see the effect of Memoji? Go watch Pixar and Disney's 3D animated movies. This is my personal favorite new feature.

#figure(image("/public/assets/img/2018/06/640-16.jpeg"))

#figure(image("/public/assets/img/2018/06/640-17.jpeg"))

== Summary

I see people online saying that there are no new features in iOS 12 at this WWDC, but in my view, every item mentioned above is a new feature. Although they may not feel particularly refreshing, most of them are functionalities we frequently encounter in our daily phone usage, such as device speedup. Although the dark mode that many hoped for did not appear, based on the current presentation, iOS 12 already shows enough sincerity, and I really like it.

#figure(image("/public/assets/img/2018/06/640-18.jpeg"))

#figure(image("/public/assets/img/2018/06/640-19.jpeg"))

= watchOS 5

The Apple Watch has come a long way from being underestimated in its first generation to becoming a representative of smartwatches. It wasn't easy. Initially, the Apple Watch hadn't found its positioning, but now it's quite clear - focusing on sports and fitness-related features, and it seems to be developing well, even though I don't own one.

#figure(image("/public/assets/img/2018/06/640-20.jpeg"))

== Achievement System & Activity Tracking

watchOS 5 now has a seven-day challenge system, allowing users to challenge friends and earn medals. I think Apple is not far from establishing its own sports leaderboard.

In watchOS 5, the system can automatically detect the user's activity status to make recorded exercise time more accurate. However, I have always felt this should have been a feature from the beginning. The practice of requiring users to manually start and stop is unreasonable, as it will undoubtedly be abused, leading to a lot of inaccurate data, which can harm the device's positioning and reputation.

#figure(image("/public/assets/img/2018/06/640-21.jpeg"))

== Walkie-Talkie

Apple also released a `Walkie-Talkie` feature. However, this feature seems to rely on the network, so I am skeptical about its real-time performance and usability.

#figure(image("/public/assets/img/2018/06/640-22.jpeg"))

== Siri & Notifications

Siri `Shortcuts` naturally made its way to the Apple Watch and became one of the watch faces; you no longer need to say "Hi, Siri" to wake it up, as you can simply raise your wrist, which indeed saves a lot of effort.

watchOS 5 also supports interactive notifications, allowing users to perform simple interactive operations, such as rating a Didi driver or checking into a hotel, making the watch's functionality more diverse and powerful.

#figure(image("/public/assets/img/2018/06/640-23.jpeg"))

There are also some relatively useless new features, like browsing the web... and some not-so-useless features, like listening to podcasts.

#figure(image("/public/assets/img/2018/06/640-24.jpeg"))

== Campus Card

What excites me is that watchOS 5 introduced the campus card feature, meaning you can use your Apple Watch to swipe into dorms, laundry rooms, cafeterias, etc. This is indeed very practical and convenient, but currently, only a few universities in the U.S. have started using it, and it may take a long time for domestic universities to catch up.

#figure(image("/public/assets/img/2018/06/640-25.jpeg"))

Finally, Apple revealed the only hardware of the event - a rainbow strap and matching rainbow watch face, enriching the style choices for wearers.

#figure(image("/public/assets/img/2018/06/640-26.jpeg"))

== Summary

Over the years, the Apple Watch's positioning has gradually become clearer, its features have become richer, and its styles have become more diverse. Overall, the trend seems good. However, with the increase in features, I am quite concerned about battery life and endurance. If a watch needs to be charged every day, I think the inconvenience it brings cannot be compensated by additional features. With the popularity of `eSIM`, I believe the Apple Watch has even greater potential.

= tvOS

This is a new operating system designed for a device that cannot be purchased in the domestic market, but I really like this compact content aggregation platform...

This time, tvOS upgraded users to `4K HDR` quality...

#figure(image("/public/assets/img/2018/06/640-27.jpeg"))

At the same time, the new tvOS also supports `Dolby Atmos`...

#figure(image("/public/assets/img/2018/06/640-28.jpeg"))

If you like to have an Apple TV in your living room, then the `2160p HDR TrueHD 7.1 Atmos` movies you downloaded before now have a place to shine.

Of course, to achieve these effects, having just an Apple TV is not enough; you also need a full set of supporting peripherals (7 HomePods reserved).

Finally, Apple updated the astronaut perspective screensaver, becoming part of `Aerial`.

= macOS Mojave

Named after the desert in the southwestern United States.

#figure(image("/public/assets/img/2018/06/640-29.jpeg"))

== Dark Mode

For those of us who love to work late at night, dark mode is really useful...

#figure(image("/public/assets/img/2018/06/640-30.jpeg"))

== File Management

The new system supports intelligent classification of desktop files...

#figure(image("/public/assets/img/2018/06/640-31.jpeg"))

In the new system, when previewing images in `Finder`, the system provides a more functional `Gallery View`...

#figure(image("/public/assets/img/2018/06/640-32.jpeg"))

In the new system, the screenshot feature has been enhanced...

#figure(image("/public/assets/img/2018/06/640-33.jpeg"))

== Security Control

The new system now offers finer-grained permission control, allowing more restrictions on applications' access to user data. I must say, Apple's security design is one of the most conscientious among major internet companies.

== UIKit on macOS

Although Apple clearly stated in the Keynote that iOS will not merge with macOS, they provided a compromise solution by adding part of the previously core framework of iOS, `UIKit`, to the underlying layer of macOS apps...

#figure(image("/public/assets/img/2018/06/640-34.jpeg"))

== App Store

The new system redesigned the previously unpopular `App Store` application...

#figure(image("/public/assets/img/2018/06/640-35.jpeg"))

= Summary

There are no particularly eye-catching new features, but updates to commonly used functionalities are everywhere, indicating a significant update effort... Apple remains the idealistic, principled, and capable Apple, and as a fan, I have no regrets.

#link("https://ws4.sinaimg.cn/large/006tKfTcgy1fs1hyuwyg2j31gw0pl4qp.jpg")[image]
