#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2025/cloudflare-d1-comments.typ
// source_sha256: sha256:4b9bbb4e0eb27edec58b03997c1342e37800b53d371b28da8926ad8b39772be0

#show: main.with(
  title: "Adding a Comment Feature to Your Blog with Cloudflare D1 and Astro",
  desc: [Adding a Comment Feature to Your Blog with Cloudflare D1 and Astro],
  date: "2025-08-30",
  tags: (

    blog-tags.programming,
    blog-tags.cloudflare,
    blog-tags.astro,
    blog-tags.blog
  
  ),
  lang: "en",
  i18nKey: "tutorials/2025/cloudflare-d1-comments",
  sourceLang: "zh",
  translationSourceHash: "sha256:4b9bbb4e0eb27edec58b03997c1342e37800b53d371b28da8926ad8b39772be0",
  translationStatus: "machine",
)

Since deploying my blog on Cloudflare, I have been looking for a suitable comment system. At the beginning of establishing my blog website, I used Disqus, but Disqus is very slow to access in China and sometimes gets blocked, so I gave up on it.

Later, I learned about #link("https://valine.js.org/")[Valine] and always wanted to give it a try, but I was too lazy to do so.

Until recently, I learned about Cloudflare D1 and Astro's Drizzle ORM, so I wanted to try adding a comment feature to my blog.

= Tech Stack

- Cloudflare D1
- Astro
- Drizzle ORM
- Bun

= Implementation Steps

== Create Database and Table

In the project, you can create the database and table using the wrangler command line tool.

```bash
bunx wrangler d1 create wonderland
```

Then I placed the `migrations/0001_init.sql` database migration script in the project.

```sql
DROP TABLE IF EXISTS comments;
CREATE TABLE
    IF NOT EXISTS comments (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        post_slug TEXT NOT NULL, -- Unique identifier/slug for the article
        author_name TEXT NOT NULL,
        author_email TEXT NOT NULL,
        author_url TEXT NOT NULL,
        content TEXT NOT NULL,
        created_at INTEGER NOT NULL DEFAULT (unixepoch ()),
        parent_id INTEGER,
        ip_hash TEXT
    );

CREATE INDEX IF NOT EXISTS idx_comments_post_created ON comments (post_slug, created_at DESC);

INSERT INTO comments (post_slug, author_name, author_email, author_url, content) VALUES ('test-slug', 'John Doe', 'john.doe@example.com', 'https://example.com', 'This is a test comment');
INSERT INTO comments (post_slug, author_name, author_email, author_url, content) VALUES ('test-slug', 'John Doe', 'john.doe@example.com', 'https://example.com', 'This is a test comment');
```

Then execute the database migration script using the `wrangler d1 execute` command.

```bash
bunx wrangler d1 execute wonderland --local --file=./migrations/0001_init.sql
```

_D1_ is a very magical database, and its commands can be executed _locally_ or _remotely_ by simply adding the `--local/--remote` parameter to the command, which greatly facilitates development and debugging, meaning you can mess around locally without worrying about affecting the production environment.
