#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/calix/2026/calix-initial.typ
// source_sha256: sha256:6122244ad0f12039ce312a3a225af9901e1d361451621d00890fe4a57c5cbd97

#show: main.with(
  title: "After Kehua's Shutdown, I Created 'Calix' — A Place for Thoughts to Rest",
  desc: [Project features and tech stack sharing],
  date: "2026-01-07",
  tags: (

    blog-tags.programming,
    blog-tags.software,
    blog-tags.elixir,
  
  ),
  lang: "en",
  i18nKey: "calix/2026/calix-initial",
  sourceLang: "zh",
  translationSourceHash: "sha256:6122244ad0f12039ce312a3a225af9901e1d361451621d00890fe4a57c5cbd97",
  translationStatus: "machine",
)

Direct link: #link("https://calix.hemifuture.cn")[Calix]

= Origin

At the end of 2025, the Kehua APP announced its shutdown.

For many users, this is just the end of an ordinary app. But for me, it holds many thoughts written in the dead of night, a place to vent during low moments, a refuge for words that I didn’t know who to share with.

What makes Kehua unique is its "anonymous resonance" mechanism — you write down your thoughts, and the system helps you find a stranger somewhere in the world who is experiencing similar feelings. There’s no social pressure, no judgment from acquaintances, just pure understanding and resonance between two unfamiliar souls.

The moment I learned it was about to close, I realized: *If no one is going to do this, then I will.*

Thus, *Calix* was born. #footnote[This is a footnote test. This is a footnote test. This is a footnote test. This is a footnote test. This is a footnote test. This is a footnote test. This is a footnote test. This is a footnote test.]

= What is Calix?

Calix, derived from the Zhuangzi, "Calix words flow naturally like pouring from a cup" — words that flow effortlessly, yet are just right.

Calix is its English name, meaning "cup" in Latin, symbolizing the holding of your emotions.

This is a platform for emotional expression and resonance matching. Its core idea is simple: *Let the words in your heart have a place to rest.*

Here, you can:

== 📝 Write Down Your Thoughts

Whether it’s late-night anxiety, sudden sadness, or confusion about how to express yourself, you can write it down here. Supports text and images, with no word limit and no pressure of likes.

== 🔮 Find Resonance

This is the core function of Calix and the soul of Kehua. After you post a dynamic, the system will help you find strangers who have similar experiences and feelings.

== 💡 Illuminate Each Other

When you see a dynamic that resonates with you among the resonance candidates, you can choose to "illuminate" it. This is a silent expression of empathy — "I understand you, I’m here too."

If two people illuminate each other's dynamics, the system will send a reminder that "you have illuminated each other." This is the moment when two hearts find each other.

== 💬 Warm Conversations

After illuminating each other, you can start chatting. It’s not the kind of "add friend" with a clear purpose like on social media, but rather two people who have faced similar dilemmas sharing their stories under the protection of anonymity.

Sometimes, the understanding of a stranger can be more powerful than the comfort of an acquaintance.

= Seamless Migration from Kehua

As a long-time user of Kehua, I deeply understand the value of those historical dynamics. They are a reflection of my past self, a testament to my growth.

Thus, Calix has specifically created a *Kehua data import* feature:

1. Export your content zip file from the Kehua APP
2. Upload it on Calix's "Import Kehua Data" page
3. The system automatically parses all dynamic content, publication times, and images
4. One-click import, all historical dynamics perfectly preserved

The imported dynamics will retain their original publication times, and you can choose to have them re-participate in resonance matching or simply keep them as a quiet record of the past.

*Every word you wrote on Kehua deserves to be preserved.*

= Tech Stack

As an independent development project, Calix chose a simple and reliable tech solution:

- *Elixir + Phoenix*: Functional language + high-concurrency web framework, providing a smooth real-time push experience
- *Phoenix LiveView*: Server-side rendered real-time interaction, no complex front-end and back-end separation needed
- *Tailwind CSS*: A modern styling solution, with a clean and restrained interface

No microservices, no over-engineering, an architecture that one person can maintain.

= In Conclusion

The original intention of creating Calix is simple — I needed a place to express myself, and Kehua is no longer there.

But during the development process, I gradually realized that this is not just a "substitute."

It is my understanding of "emotional expression":

- People need to express themselves, but not all words are suitable for acquaintances
- Resonance is not sympathy, but rather "I have been through this, I understand you"
- Anonymity is not for avoidance, but for facing oneself more authentically
- Connection is not for socializing, but to no longer feel lonely

If you have ever written down those unplaceable thoughts in the dead of night, if you are also looking for a safe space to be understood —

*Welcome to Calix.*

Let the words in your heart have a place to rest.

*Calix is currently in the early development stage, with more features continuously iterating.*

*If you are also a long-time user of Kehua, don’t forget to import your historical data. Those words deserve to be preserved.*
