#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/design-pattern-chain-of-responsibility.typ
// source_sha256: sha256:842407b6845910dd931013730b12c7f41d7c932751a010ec6c29dbc13d845351

#show: main.with(
  title: "Design Patterns (4) — Chain of Responsibility Pattern",
  desc: [The Chain of Responsibility pattern is a software design pattern used to process requests and delegate the responsibility of handling requests to a series of handlers. In the Chain of Responsibility pattern],
  date: "2022-12-31",
  tags: (

    blog-tags.software-engineering,
    blog-tags.rust,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2022/design-pattern-chain-of-responsibility",
  sourceLang: "zh",
  translationSourceHash: "sha256:842407b6845910dd931013730b12c7f41d7c932751a010ec6c29dbc13d845351",
  translationStatus: "machine",
)

The Chain of Responsibility pattern is a software design pattern used to process requests and delegate the responsibility of handling requests to a series of handlers.

In the Chain of Responsibility pattern, a request starts from one handler and is passed to the next handler one by one until the final handler can process the request. The advantage of this pattern is that it allows the system to dynamically add or remove handlers and easily change the execution order of handlers.

Here is an example of implementing the Chain of Responsibility pattern in Rust:

```rust
struct Request {
    content: String,
}

trait Handler {
    fn set_next(&mut self, handler: Box<dyn Handler>);
    fn handle_request(&self, request: &Request);
}

struct ConcreteHandlerA {
    next: Option<Box<dyn Handler>>,
}

impl ConcreteHandlerA {
    fn new() -> ConcreteHandlerA {
        ConcreteHandlerA { next: None }
    }
}

impl Handler for ConcreteHandlerA {
    fn set_next(&mut self, handler: Box<dyn Handler>) {
        self.next = Some(handler);
    }

    fn handle_request(&self, request: &Request) {
        if request.content.starts_with("A") {
            println!("ConcreteHandlerA: Handling request with content starting with 'A'");
        } else {
            if let Some(ref next) = self.next {
                next.handle_request(request);
            }
        }
    }
}

struct ConcreteHandlerB {
    next: Option<Box<dyn Handler>>,
}

impl ConcreteHandlerB {
    fn new() -> ConcreteHandlerB {
        ConcreteHandlerB { next: None }
    }
}

impl Handler for ConcreteHandlerB {
    fn set_next(&mut self, handler: Box<dyn Handler>) {
        self.next = Some(handler);
    }

    fn handle_request(&self, request: &Request) {
        if request.content.starts_with("B") {
            println!("ConcreteHandlerB: Handling request with content starting with 'B'");
        } else {
            if let Some(ref next) = self.next {
                next.handle_request(request);
            }
        }
    }
}

struct ConcreteHandlerC {
    next: Option<Box<dyn Handler>>,
}

impl ConcreteHandlerC {
    fn new() -> ConcreteHandlerC {
        ConcreteHandlerC { next: None }
    }
}

impl Handler for ConcreteHandlerC {
    fn set_next(&mut self, handler: Box<dyn Handler>) {
        self.next = Some(handler);
    }

    fn handle_request(&self, request: &Request) {
        if request.content.starts_with("C") {
            println!("ConcreteHandlerC: Handling request with content starting with 'C'");
        } else {
            if let Some(ref next) = self.next {
                next.handle_request(request);
            }
        }
    }
}

fn main() {
    let mut handler_a = ConcreteHandlerA::new();
    let mut handler_b = ConcreteHandlerB::new();
    let mut handler_c = ConcreteHandlerC::new();

    handler_a.set_next(Box::new(handler_b));
    handler_b.set_next(Box::new(handler_c));

    let request = Request { content: "A message".to_string() };
    handler_a.handle_request(&request);

    let request = Request { content: "B message".to_string() };
    handler_a.handle_request(&request);

    let request = Request { content: "C message".to_string() };
    handler_a.handle_request(&request);

    let request = Request { content: "D message".to_string() };
    handler_a.handle_request(&request);
}
```

In this example, we define a struct named `Request`, which contains a string field named `content`. This struct represents a request, where the `content` field indicates the content of the request.

Next, we define a trait named `Handler`, which includes two methods: `set_next` and `handle_request`. The `set_next` method allows setting the next handler to a given handler, while the `handle_request` method allows the handler to process a given request.

Then, we define three concrete handlers (`ConcreteHandlerA`, `ConcreteHandlerB`, and `ConcreteHandlerC`), each capable of handling requests that start with the letters A, B, or C, respectively. Each concrete handler contains a field named `next`, which indicates the next handler.

In the `main` function, we create three handlers and connect them together to form a chain of responsibility. We then create four requests and pass them to the start of the chain (i.e., `handler_a`). Each handler checks the content of the request and decides whether to forward the request based on whether it can handle it.

If a handler can process the request, it prints a message indicating that it is handling the request. If a handler cannot process the request, it forwards the request to the next handler and prints a message indicating that it is forwarding the request. In this way, the request is passed along the chain of responsibility until it reaches the end.

When all handlers are unable to process the request, the request is discarded. The code in this example implements the basic idea of the Chain of Responsibility pattern, and you can modify and extend it according to your needs.

The Chain of Responsibility pattern has the following advantages:

- Reduces coupling between objects. The Chain of Responsibility pattern allows each object to only know its direct next object, without needing to know the entire structure of the chain. This reduces coupling between objects, making them easier to reuse and maintain.
- Facilitates the addition or alteration of handlers. The Chain of Responsibility pattern allows you to easily add or change handlers. If a new handler needs to be added, it can simply be appended to the end of the chain. Similarly, if the execution order of handlers needs to be changed, it can be done by adjusting the order of handlers in the chain.
- Provides a clear path for request passing. The Chain of Responsibility pattern provides a clear path for request passing, which helps determine whether a request is ultimately processed and can assist developers in debugging the system.
- Allows each handler to decide whether to process the request. The Chain of Responsibility pattern allows each handler to decide whether to process the request. This helps reduce the complexity of the system and makes it easier to maintain and extend.

However, it also has some drawbacks:

- The chain may become very long. If the chain contains many handlers, it may become very long, which could lead to a decrease in system performance.
- Difficult to debug. One of the drawbacks of the Chain of Responsibility pattern is that debugging can become difficult. Since requests may be interrupted at any point in the chain, each handler in the chain must be checked to determine the cause of the error.
- Potential for misuse. If the Chain of Responsibility pattern is misused, it can lead to complexity in the system and degrade system performance.
