#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/design-pattern-factory.typ
// source_sha256: sha256:4dc032f4982b69d48da4beb0bdade8a57ccc5144f7ae053104bea85310f9dfe9

#show: main.with(
  title: "Design Patterns (0) — Factory Pattern",
  desc: [The factory pattern is a software design pattern that belongs to the category of creational patterns. The purpose of the factory pattern is to create a series of related or dependent objects through an abstract factory class.],
  date: "2022-12-30",
  tags: (

    blog-tags.software-engineering,
    blog-tags.rust,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2022/design-pattern-factory",
  sourceLang: "zh",
  translationSourceHash: "sha256:4dc032f4982b69d48da4beb0bdade8a57ccc5144f7ae053104bea85310f9dfe9",
  translationStatus: "machine",
)

The factory pattern is a software design pattern that belongs to the category of creational patterns. The purpose of the factory pattern is to create a series of related or dependent objects through an abstract factory class. It is used to abstract the process of object creation. By using the factory pattern, we can separate the creation and usage of objects, allowing us to replace new objects without modifying existing code.

The factory pattern has the following advantages:

1. In the factory pattern, we can encapsulate the object creation process within the factory class, so the client does not need to know the specific implementation details.
2. In the factory pattern, we can change the specific factory class to switch between different products.
3. In the factory pattern, we can control the object creation process more flexibly, which gives the system better extensibility.

The disadvantages of the factory pattern are also evident: when new products need to be added, the factory class needs to be modified, which violates the "Open/Closed Principle."

Here is an example of the factory pattern implemented in Rust:

First, we define a `Shape` trait and three structs that implement this trait:

```rust
trait Shape {
    fn area(&self) -> f64;
}

struct Circle {
    radius: f64,
}

impl Shape for Circle {
    fn area(&self) -> f64 {
        3.14 \* self.radius \* self.radius
    }
}

struct Rectangle {
    width: f64,
    height: f64,
}

impl Shape for Rectangle {
    fn area(&self) -> f64 {
        self.width \* self.height
    }
}

struct Triangle {
    base: f64,
    height: f64,
}

impl Shape for Triangle {
    fn area(&self) -> f64 {
        self.base \* self.height / 2.0
    }
}
```

Then we define a `ShapeFactory` struct, which has a static method `new_shape` that creates the corresponding `Shape` object based on the given type:

```rust
struct ShapeFactory;

impl ShapeFactory {
    fn new_shape(shape_type: &str) -> Box<dyn Shape> {
        match shape_type {
            "circle" => Box::new(Circle { radius: 1.0 }),
            "rectangle" => Box::new(Rectangle { width: 2.0, height: 3.0 }),
            "triangle" => Box::new(Triangle { base: 4.0, height: 5.0 }),
            _ => panic!("Invalid shape type"),
        }
    }
}
```

Finally, we can use `ShapeFactory` to create different types of `Shape` objects:

```rust
fn main() {
    let shape1 = ShapeFactory::new_shape("circle");
    let shape2 = ShapeFactory::new_shape("rectangle");
    
    shape1.area();
}
```
