#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/design-pattern-strategy.typ
// source_sha256: sha256:5ef2d478bf4fb6ae485e783b85134e413a34618a8b2bd1af776da5785a972097

#show: main.with(
  title: "Design Patterns (3) — Strategy Pattern",
  desc: [The Strategy Pattern is a commonly used design pattern that defines a series of algorithms and encapsulates each algorithm so that they can be interchanged. The Strategy Pattern allows algorithms to vary independently of the clients that use them, enabling changes to the algorithms without affecting the clients.],
  date: "2022-12-31",
  tags: (

    blog-tags.software-engineering,
    blog-tags.rust,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2022/design-pattern-strategy",
  sourceLang: "zh",
  translationSourceHash: "sha256:5ef2d478bf4fb6ae485e783b85134e413a34618a8b2bd1af776da5785a972097",
  translationStatus: "machine",
)

The Strategy Pattern is a commonly used design pattern that defines a series of algorithms and encapsulates each algorithm so that they can be interchanged. The Strategy Pattern allows algorithms to vary independently of the clients that use them, enabling changes to the algorithms without affecting the clients.

For example, suppose we have a system responsible for sending emails to users. This system can use different strategies to send emails, such as sending via an SMTP server or sending via an API call. We can use the Strategy Pattern to encapsulate these sending strategies and allow the system to dynamically switch strategies as needed.

Here is an example of implementing the Strategy Pattern in Rust:

```rust
struct Context<'a> {
    strategy: &'a dyn Strategy,
}

trait Strategy {
    fn execute(&self, num1: i32, num2: i32) -> i32;
}

struct AddStrategy;

impl Strategy for AddStrategy {
    fn execute(&self, num1: i32, num2: i32) -> i32 {
        num1 + num2
    }
}

struct SubtractStrategy;

impl Strategy for SubtractStrategy {
    fn execute(&self, num1: i32, num2: i32) -> i32 {
        num1 - num2
    }
}

struct MultiplyStrategy;

impl Strategy for MultiplyStrategy {
    fn execute(&self, num1: i32, num2: i32) -> i32 {
        num1 \* num2
    }
}

fn main() {
    let context = Context {
        strategy: &AddStrategy,
    };
    let result = context.strategy.execute(3, 4);
    println!("Result: {}", result);

    let context = Context {
        strategy: &SubtractStrategy,
    };
    let result = context.strategy.execute(3, 4);
    println!("Result: {}", result);

    let context = Context {
        strategy: &MultiplyStrategy,
    };
    let result = context.strategy.execute(3, 4);
    println!("Result: {}", result);
}
```

In this example, we define a `Context` struct that contains a reference to a strategy. Then we define a `Strategy` trait and implement an `execute` method to invoke the strategy. We define three structs, each implementing the addition, subtraction, and multiplication strategies.

Advantages of the Strategy Pattern:

1. The Strategy Pattern provides perfect support for the Open-Closed Principle by encapsulating algorithms in independent strategies, making them easy to switch, understand, and extend.
2. The Strategy Pattern offers a way to replace inheritance. It is about how to define algorithms, encapsulating each algorithm into an independent `Strategy` object related to the corresponding `Context` object, allowing them to be interchangeable.
3. The Strategy Pattern provides a simple way to encapsulate a set of specific behaviors and algorithms and dynamically choose which algorithm to use at runtime.

Disadvantages of the Strategy Pattern:

1. The Strategy Pattern can increase the number of strategy classes, with each concrete strategy class existing separately. If there are many strategy classes, it will inevitably consume more system resources.
2. The Strategy Pattern can be cumbersome to use and may increase the complexity of the system.
