#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/design-pattern-singleton.typ
// source_sha256: sha256:caab2843c38ee16e3c74b919f08b00cf4910e6b4b022b18fa8210038da672512

#show: main.with(
  title: "Design Patterns (1) — Singleton Pattern",
  desc: [The singleton pattern is a common design pattern that ensures a class has only one instance and provides a global access point to that instance. The purpose of this is],
  date: "2022-12-31",
  tags: (

    blog-tags.software-engineering,
    blog-tags.rust,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2022/design-pattern-singleton",
  sourceLang: "zh",
  translationSourceHash: "sha256:caab2843c38ee16e3c74b919f08b00cf4910e6b4b022b18fa8210038da672512",
  translationStatus: "machine",
)

The singleton pattern is a common design pattern that ensures a class has only one instance and provides a global access point to that instance. The purpose of this is to limit the number of instances and save system resources.

There are many ways to implement the singleton pattern, but the common ones include:

1. Lazy Singleton: Creates the instance only when it is first called, but has thread safety issues.
2. Eager Singleton: Creates the instance at class loading time, avoiding thread safety issues, but if instance creation fails, it can lead to class loading failure.
3. Double-Checked Locking Singleton: Uses double-checked locking to ensure thread safety and creates the instance only when it is first called.
4. Enum Singleton: Uses an enum type to implement the singleton, eliminating thread safety concerns.

The singleton pattern has several key points:

- A class has only one instance
- The instance must be created by itself
- It must provide this instance to the entire system by itself

Here is an example of implementing the singleton pattern using Rust:

```rust
use std::sync::{Once, ONCE_INIT};
use std::cell::RefCell;

struct Singleton;

impl Singleton {
    fn new() -> Singleton {
        Singleton
    }
}

static mut SINGLETON: *const Singleton = 0 as *const Singleton;
static INIT: Once = ONCE_INIT;

fn get_instance() -> &'static Singleton {
    unsafe {
        INIT.call_once(|| {
            SINGLETON = Box::into_raw(Box::new(Singleton::new()));
        });
        &*SINGLETON
    }
}

fn main() {
    let instance1 = get_instance();
    let instance2 = get_instance();

    assert_eq!(instance1 as *const Singleton, instance2 as *const Singleton);
}
```

In the example above, we used `std::sync::Once` to ensure that the `get_instance` function is called only once. `SINGLETON` is a pointer to the `Singleton` type, used to hold the unique instance. In the `get_instance` function, we called the `call_once` method of `Once`, passing a closure as a parameter. When `call_once` is called, the provided closure will be executed once.

Note that the closure passed to `call_once` cannot be called directly but is invoked through the internal mechanism of `Once`. The benefit of this approach is that it guarantees the closure is called only once, thus avoiding concurrency issues.

In the closure, we used the private constructor of `Singleton` to create a new instance. We then assigned the address of this instance to `SINGLETON`. Finally, we return `SINGLETON` as the return value of the function.

In the code above, we used `Once` and a closure to ensure that the `get_instance` function is called only once, and we used a global pointer to hold the unique instance. This guarantees that every time `get_instance` is called, it returns the address of the same instance.

The advantages of using the singleton pattern include:

- Ensuring that there is only one instance in the system, avoiding duplicate object creation and saving system resources.
- It can be accessed conveniently, using specified methods to access it, which provides a certain level of control.

The disadvantages of the singleton pattern are also quite evident:

Due to the lack of an abstraction layer in the singleton pattern, extending the singleton class is quite difficult; the responsibilities of the singleton class are too heavy, which somewhat violates the "Single Responsibility Principle"; and since there is no abstraction layer in the singleton pattern, it cannot form an inheritance-based hierarchy.

Usage scenarios for the singleton pattern:

1. When the system only needs one global object, and that object has a complex initialization process, the singleton pattern can be used.
2. When the system needs to frequently access an object that has a complex initialization process, the singleton pattern can be used.
3. When the system only needs one login interface or settings interface, and that interface needs to access global data, the singleton pattern can be used.
