#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/design-pattern-prototype.typ
// source_sha256: sha256:a16648016e042c7ca0ca8d82c327b76effaff94678b3da4eba5ab8ec75576334

#show: main.with(
  title: "Design Patterns (2) — Prototype Pattern",
  desc: [The prototype pattern is a creational design pattern that allows you to copy an object instead of creating a new one. The prototype pattern is useful in scenarios where complex objects need to be created, as the process of creating a complex object can consume a lot of time and resources.],
  date: "2022-12-31",
  tags: (

    blog-tags.software-engineering,
    blog-tags.rust,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2022/design-pattern-prototype",
  sourceLang: "zh",
  translationSourceHash: "sha256:a16648016e042c7ca0ca8d82c327b76effaff94678b3da4eba5ab8ec75576334",
  translationStatus: "machine",
)

The prototype pattern is a creational design pattern that allows you to copy an object instead of creating a new one. The prototype pattern is useful in scenarios where complex objects need to be created, as the process of creating a complex object can consume a lot of time and resources.

The basic implementation of the prototype pattern is to implement a method that clones itself, and then call this method to create a new object. This way, we can obtain a new object by calling the clone method instead of recreating a new object.

Here is an example of using the prototype pattern implemented in Rust:

```rust
use std::cell::RefCell;
use std::rc::Rc;

trait Prototype {
    fn clone(&self) -> Box<dyn Prototype>;
}

struct ConcretePrototype {
    value: i32,
}

impl Prototype for ConcretePrototype {
    fn clone(&self) -> Box<dyn Prototype> {
        Box::new(ConcretePrototype { value: self.value })
    }
}

fn main() {
    let prototype = ConcretePrototype { value: 1 };
    let prototype_clone = prototype.clone();

    println!("Original value: {}", prototype.value);
    println!("Cloned value: {}", prototype_clone.value);
}
```

In this example, we define a `Prototype` trait and a `ConcretePrototype` struct that implements this trait. The `ConcretePrototype` struct has a `value` field, which is an integer.

In the `main` function, we create an instance of `ConcretePrototype`, then call its `clone` method to obtain a copy. We output the `value` of the original instance and the copy, and we can see that they are the same.

The advantages of the prototype pattern include:

- When creating new objects, there is no need to know the creation process; you only need to know the type of the object and the copy method to create a new object, simplifying the object creation process.
- The instance type can be dynamically changed at runtime; by copying existing objects to create new ones, the system's functionality can be dynamically extended at runtime.

The prototype pattern also has some drawbacks. One drawback is that a clone method must be implemented for each class, which can increase the complexity of the code; another drawback is that if there are circular references in the class, it may lead to infinite recursion, causing the system to crash.

Overall, the prototype pattern is a flexible way to create new objects, but it also has some limitations. When choosing to use the prototype pattern, these limitations should be considered to decide whether to use this pattern.
