#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/design-pattern-builder.typ
// source_sha256: sha256:50228cfcd32050fc4ad60b1a298939e655912c6bb386813e136a2dc3e944558b

#show: main.with(
  title: "Design Patterns (4) — Builder Pattern",
  desc: [The Builder Pattern is a design pattern that helps you create complex objects. It encapsulates the object creation process in a dedicated builder object.],
  date: "2022-12-31",
  tags: (

    blog-tags.software-engineering,
    blog-tags.rust,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2022/design-pattern-builder",
  sourceLang: "zh",
  translationSourceHash: "sha256:50228cfcd32050fc4ad60b1a298939e655912c6bb386813e136a2dc3e944558b",
  translationStatus: "machine",
)

The Builder Pattern is a design pattern that helps you create complex objects. It encapsulates the object creation process in a dedicated builder object to assist you in creating complex objects.

The Builder Pattern consists of the following four parts:

- Product: Represents the complex object to be created.
- Abstract Builder: Defines the interface for creating the product.
- Concrete Builder: Implements the abstract builder's interface and is responsible for creating the specific implementation of the product.
- Director: Calls the builder's methods to create the product.

The advantages of the Builder Pattern include:

- Encapsulating the creation process of complex objects within the builder object, making the creation process clearer.
- Allowing different concrete builders to create different products.
- Using the director class to control the product creation process, making it more flexible.
- Guiding the product creation process without exposing the internal details of the product.

The disadvantages of the Builder Pattern include:

- The Builder Pattern requires a considerable amount of code to implement, which may lead to a large codebase.
- If the internal changes of the product are complex, it may require defining many concrete builder classes to implement these changes, making the system more complex.
- Since the abstract builder class in the Builder Pattern needs to define methods for creating all parts, if the internal changes of the product are minimal, the Builder Pattern may introduce a lot of redundant code.

Here is a simple example of implementing the Builder Pattern in Rust:

```rust
struct Product {
    field1: i32,
    field2: String,
    field3: bool,
}

trait Builder {
    fn set_field1(&mut self, value: i32);
    fn set_field2(&mut self, value: String);
    fn set_field3(&mut self, value: bool);
    fn build(self) -> Product;
}

struct ConcreteBuilder {
    field1: i32,
    field2: String,
    field3: bool,
}

impl Builder for ConcreteBuilder {
    fn set_field1(&mut self, value: i32) {
        self.field1 = value;
    }

    fn set_field2(&mut self, value: String) {
        self.field2 = value;
    }

    fn set_field3(&mut self, value: bool) {
        self.field3 = value;
    }

    fn build(self) -> Product {
        Product {
            field1: self.field1,
            field2: self.field2,
            field3: self.field3,
        }
    }
}

struct Director {
    builder: Box<dyn Builder>,
}

impl Director {
    fn set_builder(&mut self, builder: Box<dyn Builder>) {
        self.builder = builder;
    }

    fn build_product(&mut self) -> Product {
        self.builder.set_field1(1);
        self.builder.set_field2("hello".to_string());
        self.builder.set_field3(true);
        self.builder.build()
    }
}

fn main() {
    let mut director = Director {
        builder: Box::new(ConcreteBuilder {
            field1: 0,
            field2: "".to_string(),
            field3: false,
        }),
    };
    let product = director.build_product();
    println!("field1: {}, field2: {}, field3: {}", product.field1, product.field2, product.field3);
}
```

In this example, we define a `Product` struct that represents the complex object to be created. We also define a `Builder` trait that specifies how to create the product. Then, we define a `ConcreteBuilder` struct that implements the `Builder` trait and is responsible for creating the specific implementation of the product. Finally, we define a `Director` struct that calls the builder's methods to create the product.

In the `main` function, we create a `Director` object and set a `ConcreteBuilder` object as the builder. Then, we call the `build_product` method to create the product and print the fields of the product.
