#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/elixir-genserver.typ
// source_sha256: sha256:91e4da72a1b58d5444f54f9215f2c0b663b96b6e9bcba1cd404c117a7f785288

#show: main.with(
  title: "GenServer in Elixir",
  desc: [GenServer in the Elixir language is an abstract model for implementing concurrent programming. GenServer provides a unified interface for managing and communicating the relationships between various states and processes.],
  date: "2022-12-29",
  tags: (

    blog-tags.elixir,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2022/elixir-genserver",
  sourceLang: "zh",
  translationSourceHash: "sha256:91e4da72a1b58d5444f54f9215f2c0b663b96b6e9bcba1cd404c117a7f785288",
  translationStatus: "machine",
)

GenServer in the Elixir language is an abstract model for implementing concurrent programming. GenServer provides a unified interface for managing and communicating the relationships between various states and processes.

GenServer can be used to implement various functionalities, such as caching, persistent data storage, message queues, etc. The GenServer interface can be implemented by defining different callback functions. These callback functions include:

- init/1: Used to initialize the state of the GenServer.
- handle\_call/3: Used to handle received requests and return responses.
- handle\_cast/2: Used to handle received messages without needing to return a response.
- handle\_info/2: Used to handle other information that is not requests or messages.

In addition to these callback functions, GenServer also provides some other functions that can be used to control the state and processes of the GenServer. These functions include:

- start\_link/3: Used to start a new GenServer process.
- call/3: Used to send requests to the GenServer and wait for a response.
- cast/2: Used to send messages to the GenServer without waiting for a response.
- stop/1: Used to stop the GenServer process.

Here is an example of using GenServer to implement caching:

```elixir
defmodule Cache do
  use GenServer

  def start_link(opts) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__) 
  end

  def init(opts) do
    {:ok, %{cache: Map.new}}
  end

  def set(key, value) do 
    GenServer.call(__MODULE__, {:set, key, value}) 
  end

  def get(key) do 
    GenServer.call(__MODULE__, {:get, key})
  end

  def handle_call({:set, key, value}, _from, state) do 
    state = Map.put(state[:cache], key, value) 
    {:reply, :ok, state} 
  end

  def handle_call({:get, key}, _from, state) do 
    value = Map.get(state[:cache], key) 
    {:reply, value, state} 
  end 
end
```

In the example above, we used the GenServer's `start_link/3` function to start a new process and used the `init/1` function to initialize the process's state. We also defined the `set/2` and `get/1` functions to operate on the cache. These functions send requests by calling the GenServer's `call/3` function and wait for a response. In the `handle_call/3` function, we handled two types of requests: setting a cache value and getting a cache value. For the request to set a cache value, we used the `Map.put/3` function to update the cache and return `:ok`. For the request to get a cache value, we used the `Map.get/2` function to retrieve the cache value and return that value.

When writing Elixir programs, GenServer can typically be used to implement various concurrent tasks. For example, GenServer can be used to build high-performance servers, maintain complex data structures, or even simulate complex logic and state machines.
