#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/elixir-modules.typ
// source_sha256: sha256:75fa89b1cdb2d817e241531fd3dbd818066f1e61c98cccc22723e971b1d1cfd9

#show: main.with(
  title: "Elixir Modules",
  desc: [Elixir modules are tools for organizing code, helping developers break code into manageable units. In Elixir],
  date: "2022-12-26",
  tags: (

    blog-tags.elixir,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2022/elixir-modules",
  sourceLang: "zh",
  translationSourceHash: "sha256:75fa89b1cdb2d817e241531fd3dbd818066f1e61c98cccc22723e971b1d1cfd9",
  translationStatus: "machine",
)

Elixir modules are tools for organizing code, helping developers break code into manageable units.

In Elixir, modules can contain functions, constants, structs, and enumerations. Module names typically start with an uppercase letter, such as `User` and `Math`.

Here is a code example that defines a module containing a function and a constant:

```elixir
defmodule User do
  # Constant
  DEFAULT_AGE = 18

  # Function
  def greet(name) do
    "Hello, #{name}!"
  end
end

# Calling the function
User.greet("Alice") # => "Hello, Alice!"

# Accessing the constant
User.DEFAULT_AGE # => 18
```

Modules can also use the `import` keyword to bring in functions from other modules. For example, here is a code example that imports functions from another module:

```elixir
defmodule User do
  import Math

  def calculate_average(numbers) do
    sum = Enum.reduce(numbers, 0, &+/2)
    sum / length(numbers)
  end
end
```

In this example, we imported the `Math` module from the Elixir standard library and used its `Enum.reduce/3` function.

Additionally, modules can use the `alias` keyword to set aliases for functions within modules. For example, here is a code example that uses an alias:

```elixir
defmodule User do
  alias Math.Enum, as: E

  def calculate_average(numbers) do
    sum = E.reduce(numbers, 0, &+/2)
    sum / length(numbers)
  end
end
```

In this example, we used the `alias` keyword to set the alias for the `Math.Enum` module as `E`.

Elixir modules can also use inner modules to further segment code. Inner modules are defined within outer modules and can help developers break code into smaller units.

For example, here is a code example that defines an inner module containing a function and a constant:

```elixir
defmodule User do
  defstruct name: "", age: 0

  defmodule Utils do
    DEFAULT_AGE = 18

    def greet(name) do
      "Hello, #{name}!"
    end
  end
end

# Calling a function from the inner module
User.Utils.greet("Alice") # => "Hello, Alice!"

# Accessing a constant from the inner module
User.Utils.DEFAULT_AGE # => 18
```

Moreover, Elixir modules can use the `use` keyword to apply macros from certain modules. Macros are a special tool in Elixir that can extend language functionality at compile time. For example, here is a code example that uses a macro:

```elixir
defmodule User do
  use ExUnit.Case, async: true

  test "greet function" do
    assert greet("Alice") == "Hello, Alice!"
  end
end
```

In this example, we used the `use` macro from the `ExUnit.Case` module and set the `async: true` parameter to enable asynchronous testing. This macro expands language functionality at compile time, allowing us to use the `test` function to define test cases.

Overall, Elixir modules are a very useful tool that can help developers break code into manageable units. Using modules can help developers better organize code and make it more readable and maintainable.
