#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/final-value-after-operations-and-distinct-averages.typ
// source_sha256: sha256:20577159e3c2ec146fc820339d25f94c43afa3e09043905077809d14d9c1f3b9

#show: main.with(
  title: "Thought Process for Solving Problems — Variable Values After Operations & Number of Different Averages",
  desc: [2011. Variable Values After Operations Difficulty: Easy Problem: There exists a programming language that only supports 4 operations and 1 variable X.],
  date: "2022-12-23",
  tags: (

    blog-tags.algorithm,
  
  ),
  lang: "en",
  i18nKey: "study/2022/final-value-after-operations-and-distinct-averages",
  sourceLang: "zh",
  translationSourceHash: "sha256:20577159e3c2ec146fc820339d25f94c43afa3e09043905077809d14d9c1f3b9",
  translationStatus: "machine",
)

= 2011. Variable Values After Operations

== Difficulty: Easy

== Problem:

There exists a programming language that only supports 4 operations and 1 variable `X`:

- `++X` and `X++` increase the value of variable `X` by *1*
- `--X` and `X--` decrease the value of variable `X` by *1*

Initially, the value of `X` is `0`.

You are given a string array `operations`, which is a list of operations. Return the *final value* of `X` after performing all operations.

*Example 1:*

```ini
Input: operations = ["--X","X++","X++"]
Output: 1
Explanation: The operations are executed as follows:
Initially, X = 0
--X: X decreases by 1, X = 0 - 1 = -1
X++: X increases by 1, X = -1 + 1 = 0
X++: X increases by 1, X = 0 + 1 = 1
```

*Example 2:*

```ini
Input: operations = ["++X","++X","X++"]
Output: 3
Explanation: The operations are executed as follows:
Initially, X = 0
++X: X increases by 1, X = 0 + 1 = 1
++X: X increases by 1, X = 1 + 1 = 2
X++: X increases by 1, X = 2 + 1 = 3
```

*Example 3:*

```ini
Input: operations = ["X++","++X","--X","X--"]
Output: 0
Explanation: The operations are executed as follows:
Initially, X = 0
X++: X increases by 1, X = 0 + 1 = 1
++X: X increases by 1, X = 1 + 1 = 2
--X: X decreases by 1, X = 2 - 1 = 1
X--: X decreases by 1, X = 1 - 1 = 0
```

*Note:*

- `1 <= operations.length <= 100`
- `operations[i]` will be `"++X"`, `"X++"`, `"--X"`, or `"X--"`

#line(length: 100%)

= Personal Thoughts

== 1. Simulation

Initially set x=0, iterate through the string array operations. When encountering “++X" or “X++", increase x by 1; otherwise, decrease x by 1.

```cpp
class Solution {
public:
    int finalValueAfterOperations(vector<string>& operations) {
        int x = 0;
        for (auto &op : operations) {
            if (op == "X++" || op == "++X") {
                x++;
            } else {
                x--;
            }
        }
        return x;
    }
};
```

```cpp
class Solution {
public:
    int finalValueAfterOperations(vector<string>& operations) {
        int t = 0;
        for(auto &operation:operations){
            switch(operation[1]){
                case '+': t++;break;
                default: t--;break;
            }
        }
        return t;
    }
};
```

#line(length: 100%)

= 2465. Number of Different Averages

== Difficulty: Easy

== Problem:

You are given an integer array `nums` of even length starting from index *0*.

As long as `nums` is *not* an empty array, you repeatedly perform the following steps:

- Find the minimum value in `nums` and remove it.
- Find the maximum value in `nums` and remove it.
- Calculate the average of the two removed numbers.

The *average* of two numbers `a` and `b` is `(a + b) / 2`.

- For example, the average of `2` and `3` is `(2 + 3) / 2 = 2.5`.

Return the number of *different* averages that can be obtained from the above process.

*Note*, if the minimum or maximum value has duplicate elements, you can remove any one of them.

*Example 1:*

```ini
Input: nums = [4,1,4,0,3,5]
Output: 2
Explanation:
1. Remove 0 and 5, the average is (0 + 5) / 2 = 2.5, now nums = [4,1,4,3].
2. Remove 1 and 4, the average is (1 + 4) / 2 = 2.5, now nums = [4,3].
3. Remove 3 and 4, the average is (3 + 4) / 2 = 3.5.
There are a total of 2 different numbers among 2.5, 2.5, and 3.5, so we return 2.
```

*Example 2:*

```ini
Input: nums = [1,100]
Output: 1
Explanation:
After removing 1 and 100, there is only one average, so we return 1.
```

*Note:*

- `2 <= nums.length <= 100`
- `nums.length` is even.
- `0 <= nums[i] <= 100`

#line(length: 100%)

= Personal Thoughts

== 1.

Thought Process
Original method: Use a hashmap to store elements in nums, each iteration finds the minimum and maximum values in the array, stores the average in a hashset, and removes the minimum and maximum values from the hashmap, repeating this process until the hashmap is empty.

Complexity: O(n^2)O(n)

Improved method: First sort the array nums, then use two pointers to traverse the minimum and maximum values.

Complexity: O(nlog(n))O(n)

```cpp
class Solution {
public:
    int distinctAverages(vector<int>& nums) {
        unordered_set<double> ust;
        unordered_map<int, int> ump;
        for (auto& x : nums) {
            ++ump[x];
        }
        int mx = INT_MIN, mi = INT_MAX;
        while (!ump.empty()) {
            mx = INT_MIN, mi = INT_MAX;
            for (auto& val : nums) {
                if (!ump.count(val)) {
                    continue;
                }
                mx = max(mx, val);
                mi = min(mi, val);
            }
            if (--ump[mx] == 0) {
                ump.erase(mx);
            }
            if (--ump[mi] == 0) {
                ump.erase(mi);
            }
            ust.insert(double(mx + mi) / 2.0);
        }
        return ust.size();
    }
};
```

Record the thought process for solving problems daily.
