#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/functional-programming-introduction.typ
// source_sha256: sha256:95128ddd72b3b5624305a3e8ca483ef37cab7044bd3bd84393d5d2aff3c5b4de

#show: main.with(
  title: "Introduction to Functional Programming",
  desc: [Functional programming is a programming paradigm that emphasizes the use of functions to solve problems. In functional programming, we typically use recursion to implement algorithms instead of using loops.],
  date: "2022-12-29",
  tags: (

    blog-tags.programming,
    blog-tags.elixir,
  
  ),
  lang: "en",
  i18nKey: "study/2022/functional-programming-introduction",
  sourceLang: "zh",
  translationSourceHash: "sha256:95128ddd72b3b5624305a3e8ca483ef37cab7044bd3bd84393d5d2aff3c5b4de",
  translationStatus: "machine",
)

Functional programming is a programming paradigm that emphasizes the use of functions to solve problems. In functional programming, we typically use recursion to implement algorithms instead of using loops.

= Comparison with Object-Oriented Programming Languages

Compared to object-oriented programming languages, functional programming languages have some distinct characteristics. For example:

- Functional programming languages emphasize using functions to solve problems, while object-oriented programming languages emphasize using objects to solve problems.
- Functional programming languages typically use recursion to implement algorithms, while object-oriented programming languages usually use loops to implement algorithms.
- Functional programming languages support higher-order functions, while object-oriented programming languages do not.
- Functional programming languages support pattern matching, while object-oriented programming languages do not.
- Functional programming languages often have strong function composition capabilities, allowing for easy combination of multiple functions, while object-oriented programming languages do not.

= History

The development of functional programming languages can be traced back to the 1950s. At that time, computer scientist Alonzo Church developed λ calculus, which is a theoretical model for functional programming. Subsequently, John McCarthy developed the Lisp language, which is the world's first functional programming language.

With the advancement of computer technology, functional programming languages have also been continuously evolving. For example, Haskell is a functional programming language characterized by a powerful type system, static type checking, and theoretical support for functional programming. Additionally, there are many other functional programming languages, such as Erlang, F\#, Clojure, and others.

In recent years, functional programming languages have begun to receive increasing attention due to their advantages in handling concurrent programming. For example, Elixir is a functional programming language based on the Erlang VM, characterized by high concurrency, fault tolerance, and strong scalability. Its features include:

- Emphasizing the use of functions to solve problems.
- Using recursion to implement algorithms instead of using loops.
- Supporting higher-order functions, which can take functions as parameters or return values.
- Supporting pattern matching, which allows for easy matching of function inputs and outputs.

Here are a few code examples written in Elixir:

*Calculating the n-th term of the Fibonacci sequence (recursive implementation):*

```elixir
def fib(0), do: 0
def fib(1), do: 1
def fib(n), do: fib(n-1) + fib(n-2)
```

*Calculating the average of an array using pattern matching:*

```elixir
def avg([]), do: 0
def avg(list), do: Enum.sum(list) / length(list)
```

*Using higher-order functions to map each item in an array:*

```elixir
iex> Enum.map([1, 2, 3], &(&1 \* &1))
[1, 4, 9]
```

*Using function composition (`|>` operator) to handle HTTP requests:*

```elixir
"https://example.com"
|> HTTPoison.get()
|> Map.get(:body)
|> String.upcase()
```
