#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/grpc-vs-rest-api.typ
// source_sha256: sha256:0b6bddaee670c38b58cad39f0e847ab3f1bf9b8317f2d10cf0db0ba744c17f08

#show: main.with(
  title: "Comparison of gRPC and REST API",
  desc: [REST API REST (Representational State Transfer) API],
  date: "2022-12-30",
  tags: (

    blog-tags.server,
    blog-tags.software,
    blog-tags.protobuf,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2022/grpc-vs-rest-api",
  sourceLang: "zh",
  translationSourceHash: "sha256:0b6bddaee670c38b58cad39f0e847ab3f1bf9b8317f2d10cf0db0ba744c17f08",
  translationStatus: "machine",
)

= REST API

REST (Representational State Transfer) API is a software architectural style for interactive computer systems. It is based on the HTTP protocol and provides a set of standard operations that allow clients to interact with servers.

Common REST API operations include:

- GET: Retrieve resources
- POST: Create resources
- PUT: Update resources
- DELETE: Delete resources

For example, we can use a REST API to implement a service for managing user information. We can use the GET operation to retrieve information about a specific user, the POST operation to create a new user, the PUT operation to update user information, and the DELETE operation to remove a user.

The advantage of using REST API is that it is based on the HTTP protocol, so it can be called by any HTTP client, which also makes REST API the most common interface style. Additionally, REST API supports cross-language calls because it communicates via the HTTP protocol.

However, there are some limitations to using REST API. Since REST API uses the HTTP protocol, its performance is generally lower, especially in cases of large data transfers. Moreover, calling REST API requires us to understand the HTTP protocol.

= gRPC

gRPC (gRPC Remote Procedure Calls) is a remote procedure call (RPC) framework used for cross-language communication in distributed systems. It is based on the HTTP/2 protocol and uses Protocol Buffers (Protobuf) as the message serialization method, supporting TLS authentication and encryption. gRPC is mainly applied in scenarios requiring extensive bidirectional communication, such as communication between servers, clients, and mobile devices.

In gRPC, both the server and client need to define an interface that specifies the methods to be called and the data types to be transmitted. In gRPC, a service consists of multiple methods, each containing a request and a response, which can be in a single request/response mode or in server-streaming, client-streaming, or bidirectional-streaming modes.

Compared to REST API, gRPC has the following advantages:

- Superior performance: gRPC is based on the HTTP/2 protocol, supporting multiplexing and providing better performance.
- Lightweight: Protocol Buffers is a lightweight encoding format, smaller than JSON and XML.
- Simplicity: gRPC interface definitions are straightforward, and code generation tools will generate client and server code for you.

However, gRPC also has some drawbacks:

- Not universal enough: gRPC uses Protocol Buffers as the message serialization method, which may require third-party libraries or frameworks for languages that do not support Protocol Buffers.
- Does not support cross-language calls: gRPC itself supports cross-language calls, but in practice, due to differences in message serialization methods, issues may arise in cross-language calls.

Here is an example of using gRPC for cross-language communication:

The server implemented in Go:

```go
type helloServiceServer struct{}

func (s *helloServiceServer) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloResponse, error) {
	return &pb.HelloResponse{Message: "Hello " + in.Name}, nil
}

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterHelloServiceServer(s, &helloServiceServer{})
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```

The client implemented in Python:

```python
def run():
    with grpc.insecure_channel('localhost:50051') as channel:
        stub = pb.HelloServiceStub(channel)
        response = stub.SayHello(pb.HelloRequest(name='world'))
    print("Greeter client received: " + response.message)

if __name__ == '__main__':
    run()
```

With gRPC, we can easily achieve cross-language communication.

Compared to REST API, gRPC offers higher performance and lower network overhead. Additionally, gRPC supports streaming communication, which can significantly reduce the number of communications between the server and client.

However, the use of gRPC is not suitable for all scenarios; when we need cross-language calls, we may be limited by Protocol Buffers. Furthermore, using gRPC requires us to understand HTTP/2 and Protocol Buffers.
