#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/leetcode-1768-merge-strings-alternately.typ
// source_sha256: sha256:6caf85f51133c626ef72953dfaa78c9fb7eceb1a6b17e2b78ee7936e416c04a6

#show: main.with(
  title: "LeetCode Daily Problem - 1768 - Merge Strings Alternately",
  desc: [Problem: Given two strings word1 and word2. You are to merge the strings by adding letters alternately, starting with word1.],
  date: "2022-10-23",
  tags: (

    blog-tags.rust,
    blog-tags.algorithm,
  
  ),
  lang: "en",
  i18nKey: "study/2022/leetcode-1768-merge-strings-alternately",
  sourceLang: "zh",
  translationSourceHash: "sha256:6caf85f51133c626ef72953dfaa78c9fb7eceb1a6b17e2b78ee7936e416c04a6",
  translationStatus: "machine",
)

== Problem

Given two strings word1 and word2. You are to merge the strings by adding letters alternately, starting with word1. If one string is longer than the other, append the extra letters to the end of the merged string.

Return *the merged string*.

=== Example 1:

```css
Input: word1 = "abc", word2 = "pqr"
Output: "apbqcr"
Explanation: The merging of the strings is as follows:
word1:  a   b   c
word2:    p   q   r
Merged:  a p b q c r
```

=== Example 2:

```css
Input: word1 = "ab", word2 = "pqrs"
Output: "apbqrs"
Explanation: Note that word2 is longer than word1, so "rs" needs to be appended to the end of the merged string.
word1:  a   b 
word2:    p   q   r   s
Merged:  a p b q   r   s
```

=== Example 3:

```css
Input: word1 = "abcd", word2 = "pq"
Output: "apbqcd"
Explanation: Note that word1 is longer than word2, so "cd" needs to be appended to the end of the merged string.
word1:  a   b   c   d
word2:    p   q 
Merged:  a p b q c   d
```

== Idea

The initial idea is to choose the shorter of the two strings, take its length as the number of times to alternate insert, and then determine which string is longer, appending the excess part of the longer string to the result string:

```rust
impl Solution {
    pub fn merge_alternately(word1: String, word2: String) -> String {
        let len1 = word1.len();
        let len2 = word2.len();
        let sub = len2 as i32 - len1 as i32;

        let mut result: String = String::from("");

        match sub >= 0 {
            true => {
                for idx in 0..len1 {
                    result.push(word1.chars().nth(idx).unwrap());
                    result.push(word2.chars().nth(idx).unwrap());
                }
                result.extend(word2[len1 as usize..].chars());
            },
            false => {
                for idx in 0..len2 {
                    result.push(word1.chars().nth(idx).unwrap());
                    result.push(word2.chars().nth(idx).unwrap());
                }
                result.extend(word1[len2 as usize..].chars());
            }
        }

        return result;
    }
}
```

As can be seen, there is a lot of repetition and unnecessary code in the implementation, such as the variable `sub`, which is completely unnecessary; we can directly compare `len1` and `len2`. Moreover, we can avoid checking in the shorter length part and simply choose the smaller length for the loop:

```rust
impl Solution {
    pub fn merge_alternately(word1: String, word2: String) -> String {
        let len1 = word1.len();
        let len2 = word2.len();

        let mut result: String = String::from("");

        for idx in 0..std::cmp::min(len1, len2) {
            result.push(word1.chars().nth(idx).unwrap());
            result.push(word2.chars().nth(idx).unwrap());
        }

        match len1 > len2 {
            true => result.extend(word1[len2 as usize..].chars()),
            false => result.extend(word2[len1 as usize..].chars());
        }

        return result;
    }
}
```

Is there a way to consolidate the two processes into one loop? Yes, we can create loop indices for `word1` and `word2`, placing them in the same loop, using conditions to control whether to append the next character, with the loop condition being that the index is within the length of the corresponding string:

```rust
impl Solution {
    pub fn merge_alternately(word1: String, word2: String) -> String {
        let len1 = word1.len();
        let len2 = word2.len();

        let mut result: String = String::from("");

        let mut i = 0;
        let mut j = 0;

        while i < len1 || j < len2 {
            if i < len1 {
                result.push(word1.chars().nth(i).unwrap());
            }
            if j < len2 {
                result.push(word2.chars().nth(j).unwrap());
            }
            i += 1;
            j += 1;
        }

        return result;
    }
}
```

This makes the code look neater and more pleasant, but LeetCode shows that this method consumes more memory than the previous one... possibly due to the added index variables.

All three implementations can pass the test cases, so let's leave it at that.
