#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/phoenix-liveview-introduction.typ
// source_sha256: sha256:7ee0aba77af5cb2785288a3134942b6b2ed5a32c93b69aab0969046f940a05ca

#show: main.with(
  title: "Introduction to Phoenix Liveview",
  desc: [The previous article introduced the Phoenix framework, and this section will introduce an enhanced library of it—Liveview. Phoenix],
  date: "2022-12-25",
  tags: (

    blog-tags.elixir,
    blog-tags.software,
  
  ),
  lang: "en",
  i18nKey: "study/2022/phoenix-liveview-introduction",
  sourceLang: "zh",
  translationSourceHash: "sha256:7ee0aba77af5cb2785288a3134942b6b2ed5a32c93b69aab0969046f940a05ca",
  translationStatus: "machine",
)

The previous article introduced the `Phoenix` framework, and this section will introduce an enhanced library of it—`Liveview`.

`Phoenix Liveview` is a library for building single-page applications (SPAs) and is part of the `Phoenix Framework`. It uses WebSocket connections to synchronize the server-side state with the client and employs a binding mechanism similar to JavaScript frameworks, allowing developers to write client-side code using the Elixir language.

Compared to traditional SPAs, `Phoenix Liveview` has many advantages. First, it uses server-side rendering, which means that the server can generate HTML instead of the client rendering it with JavaScript. This helps improve the performance of the application, as server-side rendering can load pages faster. Additionally, Phoenix Liveview provides many features to simplify the writing of client-side code, such as automatic view updates, using Phoenix's routing system to manage URL states, and supporting event handlers.

The general process for developing applications with `Phoenix Liveview` is as follows:

1. Install `Phoenix Liveview` in the `Phoenix Framework` project.
2. Create Liveview components. A Liveview component is an Elixir module that contains the code for rendering HTML and handling client events.
3. Define the routes for the Liveview components in the routing file.
4. Define the server-side state in the Liveview component and use bindings to update the view.
5. Handle client events in the Liveview component. This can be done by defining event handler functions that will be called when events are triggered on the client.
6. Use the rendering functions of `Phoenix Liveview` to present the views of the Liveview components.
7. You can use the automatic testing features of `Phoenix Liveview` to test the Liveview components.

Compared to developing traditional multi-page applications using the `Phoenix Framework`, there are some significant differences when using `Phoenix Liveview` to develop SPAs. First, `Phoenix Liveview` uses server-side rendering, which means that the server can generate HTML instead of the client rendering it with JavaScript. This helps improve the performance of the application, as server-side rendering can load pages faster. Additionally, Phoenix Liveview provides many features to simplify the writing of client-side code, such as automatic view updates, using Phoenix's routing system to manage URL states, and supporting event handlers.

In contrast, developing traditional multi-page applications using the `Phoenix Framework` is more flexible, as it does not restrict the client technologies that developers can use. Developers can use any client technology (such as JavaScript frameworks) to build applications and can use the routing system of the `Phoenix Framework` to manage URL states. However, developing applications with the `Phoenix Framework` may require more client-side code to manage view updates and may require more server-side code to handle requests and responses.

Additionally, the workflow for developing applications using `Phoenix Liveview` may be slightly different. When developing applications with `Phoenix Liveview`, developers need to create Liveview components and define server-side states and client event handlers. In contrast, when developing applications with the `Phoenix Framework`, developers need to create models, views, and controllers, and use Ecto to connect to the database.

Overall, the main difference between using `Phoenix Liveview` and using the `Phoenix Framework` to develop applications lies in the type of application and the development workflow. `Phoenix Liveview` uses server-side rendering and a binding mechanism similar to JavaScript frameworks to build SPAs, while the `Phoenix Framework` is a powerful web framework that can be used to build multi-page applications or SPAs.
