#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/rabbitmq-vs-rocketmq-vs-kafka.typ
// source_sha256: sha256:27f3bfabd70af53b69f590e4e0d35d067d83eab399f8a9786a875ed5dbce2c89

#show: main.with(
  title: "Comparison of RabbitMQ, RocketMQ, and Kafka",
  desc: [RabbitMQ is an open-source message broker and queue server primarily used for transmitting messages between distributed systems to address application scalability and high availability issues.],
  date: "2022-12-30",
  tags: (

    blog-tags.server,
    blog-tags.elixir,
    blog-tags.software,
  
  ),
  lang: "en",
  i18nKey: "study/2022/rabbitmq-vs-rocketmq-vs-kafka",
  sourceLang: "zh",
  translationSourceHash: "sha256:27f3bfabd70af53b69f590e4e0d35d067d83eab399f8a9786a875ed5dbce2c89",
  translationStatus: "machine",
)

RabbitMQ is an open-source message broker and queue server primarily used for transmitting messages between distributed systems to address application scalability and high availability issues. It uses the Advanced Message Queuing Protocol (AMQP) and has good maintainability and pluggability.

RocketMQ is Alibaba's open-source messaging middleware, mainly used for message passing and integration between applications. It provides many practical features, including message persistence, reliability guarantees, traffic shaping, message filtering, and routing.

Kafka is a distributed stream processing platform developed by LinkedIn, designed to provide high throughput and low latency message delivery capabilities. It uses distributed message storage to achieve high availability and can handle a large volume of real-time messages.

Functionally, both RabbitMQ and RocketMQ are message middleware primarily used for message passing between applications. RabbitMQ uses the AMQP protocol, while RocketMQ uses its own protocol, but both provide good maintainability and pluggability. Kafka, on the other hand, is a stream processing platform mainly used for processing a large number of real-time messages.

RabbitMQ, RocketMQ, and Kafka are all message queue systems, and their main role is to decouple applications, allowing different systems to exchange data asynchronously. However, the three differ in architecture.

RabbitMQ is written in Erlang and communicates using the AMQP (Advanced Message Queuing Protocol). When messages are passed between producers and consumers, they go through an intermediate broker server, which is the RabbitMQ server. RabbitMQ supports the online addition of consumers, ensuring high performance even under heavy load.

RocketMQ is an open-source message queue system from Alibaba, written in Java. Its architecture is distributed, using multiple message servers for horizontal scaling. RocketMQ adopts a topic model, where producers publish messages to a topic, and consumers subscribe to messages from that topic. RocketMQ supports message real-time and order, as well as message transactions.

Kafka is an open-source message queue system from LinkedIn, also written in Java. Similar to RocketMQ, Kafka uses a distributed architecture and adopts a topic model. The difference is that Kafka supports message reliability, providing the concept of partitions, allowing messages to be categorized based on partitions. Each partition has a corresponding offset, enabling consumers to start consuming messages from a specific offset in the partition. Additionally, Kafka offers message replication functionality, allowing messages to be copied to different machines, thereby improving availability.
