#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/redis-introduction.typ
// source_sha256: sha256:aaa9ac03649681297cc5482fecda792929b77d0ea7dee4d886323d7287cd87c2

#show: main.with(
  title: "Introduction to Redis",
  desc: [Redis is an in-memory key-value store system, and its name is an abbreviation for REmote DIctionary Server],
  date: "2022-12-30",
  tags: (

    blog-tags.redis,
    blog-tags.software,
  
  ),
  lang: "en",
  i18nKey: "study/2022/redis-introduction",
  sourceLang: "zh",
  translationSourceHash: "sha256:aaa9ac03649681297cc5482fecda792929b77d0ea7dee4d886323d7287cd87c2",
  translationStatus: "machine",
)

Redis is an in-memory key-value store system, and its name is an abbreviation for REmote DIctionary Server. Its emergence has solved many performance issues related to database access under high concurrency for websites, and it can be used for caching, implementing message queues, counters, and various other functions.

The data types in Redis include:

- Strings: Can store any type of data, such as strings, numbers, floating-point numbers, boolean values, etc.
- Hashes: Can store key-value pair data, similar to the Map type in Java.
- Lists: Can store ordered data and support insertion and deletion operations.
- Sets: Can store unordered data, and the data is unique.
- Sorted Sets: Can store data with scores and sort them according to the scores.

The characteristic of Redis is that its read and write performance is very high because its data is stored in memory. At the same time, Redis supports various data persistence methods, allowing data to be recovered from disk in case of data loss.

Redis also supports various distributed deployment methods, including master-slave replication, sentinel, clustering, etc. These features make Redis a very powerful data storage system.

Here is an example of using `Python` to implement a counter with Redis:

```python
import redis

r = redis.Redis(host='localhost', port=6379, db=0)

# Increase the value of the counter
r.incr('counter')

# Get the value of the counter
value = r.get('counter')
print(value)  # Output: 1
```

Redis has many other features:

1. Redis supports transactions, allowing multiple commands to be placed in a single transaction, ensuring the atomic execution of these commands.
2. Redis supports persistence, allowing data in memory to be periodically written to disk, and can also recover data from disk when the Redis server restarts.
3. Redis supports various distributed deployment methods, including master-slave replication, sentinel, clustering, etc.
4. Redis supports setting expiration times for data, allowing each key to have an expiration time; after the expiration time, Redis will automatically delete the key and its corresponding value.
5. Redis supports value compression, which can effectively reduce memory usage.
6. Redis supports scripts, allowing complex operations to be executed using the Redis scripting language, improving program execution efficiency.
7. Redis supports message subscription and publishing, enabling message pushing and receiving.
