#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/skip-list-learning-0.typ
// source_sha256: sha256:622497185b2b6cc34f1b31d0701b8fc10457bc01b3e2752cb89aef68a43d843e

#show: main.with(
  title: "Skip List Learning (0)",
  desc: [A skip list is a data structure designed to improve the query efficiency of arrays or linked lists. The working principle of a skip list is to construct multi-level indexes, allowing query operations to quickly locate elements by 'jumping' through each level of the index.],
  date: "2022-12-15",
  tags: (

    blog-tags.algorithm,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "study/2022/skip-list-learning-0",
  sourceLang: "zh",
  translationSourceHash: "sha256:622497185b2b6cc34f1b31d0701b8fc10457bc01b3e2752cb89aef68a43d843e",
  translationStatus: "machine",
)

A skip list is a data structure designed to improve the query efficiency of arrays or linked lists. The working principle of a skip list is to construct multi-level indexes, allowing query operations to quickly locate elements by 'jumping' through each level of the index. This is similar to a binary search tree, but skip lists are more space-efficient and can be dynamically updated.

The structure of a skip list consists of a series of ordered linked lists, where each level of the linked list serves as an index to the original linked list. In each level of the linked list, each node contains a pointer to the next node and a pointer to the next level linked list.

To better understand the structure of a skip list, let's look at an example. Suppose we have an ordered linked list containing the following numbers:

```rust
1 -> 4 -> 7 -> 10 -> 13 -> 16 -> 19 -> 22 -> 25
```

We can construct a two-level index, where the first level index contains every second number, and the second level index contains every fourth number. The structure of these two levels of indexes is as follows:

```rust
1 -> 4 -> 7 -> 10 -> 13 -> 16 -> 19 -> 22 -> 25
|         |     |     |           |           |
1    ->   7    ->    13    ->    19    ->    25 
|               |                 |
1      ->      10        ->      19
```

In this example, the top-level linked list (also known as the first level index) contains the three indexes 1, 10, and 19, which point to nodes in the next level index. Each node in the next level index (also known as the second level index) points to a node in the original linked list.

In this example, if we want to find the number 19, we can start from the first level index, which contains the three indexes 1, 10, and 19. We can directly locate the position of 19 and then jump to the node for 19 in the original linked list through the second level index. This way, we can quickly find the number 19.

In addition to searching, skip lists also support insertion, deletion, and update operations. The insertion operation can add a new node to the linked list and update the indexes to correctly point to that node. The deletion operation is the opposite; it can remove a node from the linked list and update the indexes so that they no longer point to that node.

Overall, a skip list is an efficient data structure that can save space while maintaining query efficiency and supporting dynamic updates. Its applications are very broad and can be used to implement various sorting algorithms and database indexes.
