#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2022/tail-recursion-introduction.typ
// source_sha256: sha256:bc73163e11f1efa81179bf7a26ba852abbf2be9b33ebd98a3b5cafa54361e598

#show: main.with(
  title: "Introduction to Tail Recursion",
  desc: [Tail recursion is a way of writing recursive functions, characterized by calling itself at the end of the function. The benefit of this approach is that it allows the compiler to optimize the code,],
  date: "2022-12-29",
  tags: (

    blog-tags.algorithm,
    blog-tags.elixir,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2022/tail-recursion-introduction",
  sourceLang: "zh",
  translationSourceHash: "sha256:bc73163e11f1efa81179bf7a26ba852abbf2be9b33ebd98a3b5cafa54361e598",
  translationStatus: "machine",
)

Tail recursion is a way of writing recursive functions, characterized by calling itself at the end of the function. The benefit of this approach is that it allows the compiler to optimize the code, avoiding stack overflow situations.

Tail recursion is a common practice in functional programming. The characteristic of functional programming is that it uses recursion to implement algorithms instead of using loops. Therefore, tail recursion can help us write efficient and concise functional code.

In the Elixir language, we can use tail recursion to write functions. Here is an example of tail recursion:

```elixir
defmodule Recursive do 
  def sum(n, acc) when n == 0, do: acc 
  def sum(n, acc) do 
    sum(n - 1, acc + n) 
  end 
end
```

In this example, we define a function named `sum/2` to calculate the sum from 1 to n. When n equals 0, we directly return the value of the accumulator acc. Otherwise, we call itself, passing n minus 1 and the accumulator plus n.

By using tail recursion, we can avoid stack overflow situations. This is because, in the tail recursion approach, the compiler replaces the function call with a loop, thus preventing stack overflow.

If we want to use tail recursion, we need to ensure that we call itself at the end of the function. For example, in the above example, we called the `sum/2` function at the end of the function.

Here is an example of using tail recursion to calculate factorial:

```elixir
defmodule Factorial do
  def fact(n) when n == 0, do: 1
  def fact(n) do
    n \* fact(n - 1)
  end
end
```

In this example, we define a function named `fact/1` to calculate the factorial of n. When n equals 0, we directly return 1. Otherwise, we call itself and return n multiplied by the result of the factorial of n - 1.

The advantage of tail recursion is that it allows the compiler to optimize the code, avoiding stack overflow situations. This is because, in the tail recursion approach, the compiler replaces the function call with a loop, thus preventing stack overflow.

However, tail recursion also has its drawbacks. For example, the code using tail recursion may be harder to understand, and beginners may need to spend more time learning and comprehending it. Additionally, the code using tail recursion may be longer and less concise.
