#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/meta/2021/20210507-blog-new-style.typ
// source_sha256: sha256:ea0e90ffff3dcc52661d95e9b2277795d91a82180d437dfdc630a1d746283e75

#show: main.with(
  title: "A New Look for the Blog",
  desc: [A New Look for the Blog],
  date: "2021-05-07",
  tags: (

    blog-tags.blog,
    blog-tags.theme,
  
  ),
  lang: "en",
  i18nKey: "meta/2021/20210507-blog-new-style",
  sourceLang: "zh",
  translationSourceHash: "sha256:ea0e90ffff3dcc52661d95e9b2277795d91a82180d437dfdc630a1d746283e75",
  translationStatus: "machine",
)

Previously, this blog was using #link("https://gohugo.io")[Hugo], which felt a bit too complicated. A while ago, while searching for information related to knowledge base frameworks, I came across #link("https://vuepress2.netlify.app")[Vuepress], which is very simple and has a nice default style. After some searching, I found the theme you see now—#link("https://vuepress-theme-reco.recoluan.com")[vuepress-theme-reco]. Thanks to the theme author for creating this beautiful and useful theme~ I hope the theme can continue to be updated, and I also hope I can keep using it, as tinkering can be quite exhausting...
