#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2026/uos-reset-password-and-keyring.typ
// source_sha256: sha256:49031b11f3054a236b9255830333baa9b6217cca28926f96520fbc8de341c26f

#show: main.with(
  title: "UOS Password Reset and Login Keyring Repair Record",
  desc: [Reset the UOS user password through a temporary root shell in GRUB and address the issue of the deepin login keyring not unlocking with the new password.],
  date: "2026-05-23",
  tags: (

    blog-tags.linux,
    blog-tags.dev-ops,
    blog-tags.software,
  
  ),
  lang: "en",
  i18nKey: "tutorials/2026/uos-reset-password-and-keyring",
  sourceLang: "zh",
  translationSourceHash: "sha256:49031b11f3054a236b9255830333baa9b6217cca28926f96520fbc8de341c26f",
  translationStatus: "machine",
)

Some issues leave little room for thought: the machine is right in front of you, the login password is forgotten, the system can still boot, but you can't access the desktop. For UOS, a Linux-based desktop system, the most straightforward approach is to temporarily take over the boot process from GRUB, enter a minimal root shell, mount the real root partition, and then reset the target user password.#footnote[This record assumes you have access to the machine itself or the virtual machine console and have permission to maintain this system. Bypassing the login password is a high-privilege recovery operation and should not be used on unauthorized devices.]

This article documents a complete process: first resetting the system login password, then addressing the issue of the deepin login keyring not unlocking after reboot.#footnote[The login password and the login keyring password are not the same thing. The former is managed by system account authentication; the latter is typically used to protect application credentials saved in the desktop environment. Resetting the system password does not automatically rewrite the encryption password of the old keyring.]

= Overview

The process can be condensed into five steps:

#quote(block: true)[
  Edit GRUB boot parameters → Enter bash → Find `LABEL=Roota` → Mount and `passwd` → Delete the invalid `login.keyring`
]

The real caution lies in two boundaries: one is to confirm that the mounted partition corresponds to Roota's root partition, and the other is to understand that deleting `login.keyring` will invalidate the saved credentials in the old keyring.#footnote[`Roota` is a common root partition label in the UOS/Deepin system partition layout. Different installation methods may vary slightly, so this article uses `blkid` to confirm on-site rather than assuming it is `/dev/sdaX` or `/dev/nvme0n1pX`.]

= Entering the GRUB Edit Interface

Restart the machine, and when the GRUB menu appears, stop and select the UOS item to boot, then press `E` to enter the edit interface.

In the editing content, find the line that starts with `linux`. It is usually long and contains the kernel path, root parameters, quiet/splash, and other boot parameters. Move the cursor to the end of this line and append:#footnote[Here, `rw` means to mount the root filesystem in read-write mode; `init=/bin/bash` means to run bash directly after the kernel starts, rather than normally entering the systemd/init process.]

```bash
rw init=/bin/bash
```

Then press `F10` to boot. The system will not enter the graphical interface but will drop directly to the command line.#footnote[This step only temporarily modifies the boot parameters and will not permanently write to the GRUB configuration; after rebooting, the normal boot items will still work according to the original configuration.]

= Finding the Roota Partition

After entering the command line, first use `blkid` to view block device labels:

```bash
blkid
```

Find the device name corresponding to `LABEL="Roota"` in the output. It may look like:

```text
/dev/sda3: LABEL="Roota" UUID="..." TYPE="ext4"
/dev/nvme0n1p3: LABEL="Roota" UUID="..." TYPE="ext4"
```

Note down this device name. It will be referred to as `<device_name>` later in the text.#footnote[Do not guess the device name based on experience. SATA disks commonly show `/dev/sda3`, NVMe disks commonly show `/dev/nvme0n1p3`, and virtual machines and multi-disk environments may differ entirely. The label from `blkid` is more reliable than the device order.]

= Mounting the Root Partition

Mount the Roota partition to `/root`:

```bash
mount -t ext4 <device_name> /root
```

For example, if `blkid` shows Roota as `/dev/nvme0n1p3`, execute:

```bash
mount -t ext4 /dev/nvme0n1p3 /root
```

Here, `-t ext4` is specified because the Roota in this record is an ext4 filesystem.#footnote[If your system actually shows a `TYPE` other than `ext4`, you should adjust the mount type according to the `blkid` output; do not mechanically copy.]

= Changing the User Password

After mounting, execute `passwd` to change the target user's password:

```bash
passwd <username>
```

Follow the prompts to enter and confirm the new password. After completing, you can exit the temporary shell, unmount the mount point, and then force a reboot:

```bash
exit
umount /root
reboot -f
```

After rebooting, you will normally enter the UOS login interface and can log in using the newly set password.#footnote[`reboot -f` is a forced reboot, suitable for this kind of temporary shell scenario without complete init/systemd management. If used in a normally running system, the normal reboot process should be prioritized.]

= Handling the Login Keyring Not Unlocking

After changing the system password, you may encounter a new prompt: after entering the desktop, it asks to "unlock the login keyring," but the new password does not work.

This is because the old login keyring is still protected by the old password. The system login password has been changed, but the keyring file has not been re-encrypted, so the new password cannot open it.#footnote[Many desktop environments have similar mechanisms: after a successful login, the desktop attempts to automatically unlock the keyring that saves browser, network, application tokens, and other credentials using the login password. After an offline password reset, this automatic unlocking chain is broken.]

If you do not need to retain the credentials in the old keyring, you can delete the `login.keyring` in the current user directory, allowing the system to regenerate it later:

```bash
cd ~/.local/share/deepin-keyrings-wb
rm -rf login.keyring
```

The next time related components need to save credentials, a new login keyring will be created.#footnote[Deleting `login.keyring` means that the passwords, tokens, or application credentials saved in the old keyring may be lost. For scenarios where the main goal is to regain access to the system, this is the simplest solution; if there are important credentials inside, consider backing up this file first.]

= Quick Command List

If you only need to follow the operations, you can check in the following order:

```bash
# 1. Append to the end of the linux line in GRUB:
rw init=/bin/bash

# 2. After entering the shell, find Roota:
blkid

# 3. Mount Roota, replacing the corresponding device name as needed:
mount -t ext4 <device_name> /root

# 4. Change the target user's password:
passwd <username>

# 5. Wrap up and reboot:
exit
umount /root
reboot -f

# 6. After logging into the desktop, if the keyring cannot unlock:
cd ~/.local/share/deepin-keyrings-wb
rm -rf login.keyring
```

= Review

The essence of this issue is that the states of the two passwords are out of sync:

- System account password: reset through `passwd`, controlling login authentication.
- deepin login keyring: still encrypted with the old password, controlling the unlocking of desktop credentials.

The former solves "unable to enter the system," while the latter addresses "constantly prompting for the keyring after entering the system." By separating the two steps, the entire recovery process becomes clear.
