#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2020/bulletproof-task-management-priority-formula.typ
// source_sha256: sha256:748a79bb05e362febda491b8a4074c752437543ca295e74982872fe0097b0169

#show: main.with(
  title: "Rebuilding the Priority Formula in Bulletproof Task Management in Notion",
  desc: [Rebuilding the Priority Formula in Bulletproof Task Management in Notion],
  date: "2022-10-14",
  tags: (

    blog-tags.notion,
    blog-tags.tooling,
  
  ),
  lang: "en",
  i18nKey: "tutorials/2020/bulletproof-task-management-priority-formula",
  sourceLang: "zh",
  translationSourceHash: "sha256:748a79bb05e362febda491b8a4074c752437543ca295e74982872fe0097b0169",
  translationStatus: "machine",
)

Yesterday, I watched #link("https://www.notion.vip/bulletproof-task-management-in-notion/")[Bulletproof Task Management in Notion], where there is a field called `Priority` in the _Tasks_ database, used to calculate the priority of a task based on the four fields: `Urgency`, `Impact`, `Workload`, and `Enjoyment`:

#figure(image("/public/assets/img/2020/12/projects_database__task_prioritizer.png"))

According to the video and #link("https://www.notion.vip/bulletproof-tasks/#the-prioritizer")[the original text], the author divides the four situations of the two dimensions in the Matrix into 4 priorities: 1, 2, 3, 4, with smaller numbers indicating higher priority:

#figure(image("/public/assets/img/2020/12/productivity-methods_eisenhower-matrix.png"))

In the Task Database settings, the priority is divided into four dimensions:
- Urgency
- Impact
- Workload
- Enjoyment

Each dimension has three levels: `High`, `Medium`, `Low`. Each of the four dimensions has a weight, which ultimately calculates the value of the `Priority` item.

The original text and video do not provide a specific calculation method, but based on the 5 records already present in the video, we can calculate the weight of each dimension using a system of equations:

#figure(image("/public/assets/img/2020/12/bulletproof-task-management-priority-formula.png"))

Assuming the priority of `High` is 1, `Medium` is 2, and `Low` is 3, let the weights of the four dimensions be $a, b, c, d$. We can see several special `Priority` values in the figure: *1.67*, *1.83*, *2.67*, which are clearly truncation errors caused by the scores not being exact. We can derive:

$ 1.67 approx 1.6666... = frac(5, 3) \
1.83 approx 1.8333... = frac(11, 6) \
2.67 approx 2.6666... = frac(8, 3) $

Thus, from the first four lines, we can obtain the system of equations:

$ cases(
  2a + b + 2c + 3d = frac(3, 2),
  3a + b + c + 3d = frac(5, 3),
  a + 2b + 3c + 2d = frac(11, 6),
  3a + 2b + 3c + 2d = frac(5, 2),
) $

Solving gives:

$ cases(
  a = frac(1, 3),
  b = frac(1, 2),
  c = frac(1, 6),
  d = 0,
) $

It seems the author believes that enjoyment does not affect task completion.

In summary, with the weights established, we can write the calculation method for `Priority` into the formula:

```
round(
  (
    if(
      prop("Urgency") == "Low",
      3,
      if(
        prop("Urgency") == "Medium",
        2,
        1
      )
    ) / 3 +
    if(
      prop("Impact") == "Low",
      3,
      if(
        prop("Impact") == "Medium",
        2,
        1
      )
    ) / 2 +
    if(
      prop("Workload") == "Low",
      3,
      if(
        prop("Workload") == "Medium",
        2,
        1
      )
    ) / 6
  )* 100
) / 100
```

Single-line version:

```
round((if(prop("Urgency") == "Low", 3, if(prop("Urgency") == "Medium", 2, 1)) / 3 + if(prop("Impact") == "Low", 3, if(prop("Impact") == "Medium", 2, 1)) / 2 + if(prop("Workload") == "Low", 3, if(prop("Workload") == "Medium", 2, 1)) / 6) \* 100) / 100
```

Done!
