#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2020/wsl-elixir-observer.typ
// source_sha256: sha256:a4113f5e0b04853d68f9fb2a65e1853495ad028c4301bc5750e781b2476837a1

#show: main.with(
  title: "Solving the Garbled Text Issue When Using Elixir's Observer in Windows WSL",
  desc: [Solving the Garbled Text Issue When Using Elixir's Observer in Windows WSL],
  date: "2020-03-14",
  tags: (

    blog-tags.wsl,
    blog-tags.elixir,
    blog-tags.linux,
  
  ),
  lang: "en",
  i18nKey: "tutorials/2020/wsl-elixir-observer",
  sourceLang: "zh",
  translationSourceHash: "sha256:a4113f5e0b04853d68f9fb2a65e1853495ad028c4301bc5750e781b2476837a1",
  translationStatus: "machine",
)

- OS: Windows 10
- WSL: Ubuntu 18.04 LTS
- X Server: VcXSrv

When running Elixir's Observer under WSL, I encountered an issue where all text turned into boxes. After checking the [information](https://www.cnblogs.com/freestylesoccor/articles/9630758.html), it was confirmed to be a problem with Chinese fonts. The final solution is as follows:

Install the following three font packages in the system:

```bash
$ sudo apt install ttf-wqy-microhei
$ sudo apt install fonts-wqy-microhei
$ sudo apt install ttf-wqy-zenhei
```

After installation, run the Observer again, and the text will display correctly.
