#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/en/tutorials/2018/enable-latex-export-logging.typ
// source_sha256: sha256:20e30d9247a29941209ae285471257e3974be7465200fc554a77b1e3ceea7f74

#show: main.with(
  title: "在 org-mode 中启用 latex-export-logging",
  desc: [在 org-mode 中启用 latex-export-logging],
  date: "2018-05-11",
  tags: (

    blog-tags.emacs,
    blog-tags.tooling,
  
  ),
  lang: "zh",
  i18nKey: "tutorials/2018/enable-latex-export-logging",
  sourceLang: "en",
  translationSourceHash: "sha256:20e30d9247a29941209ae285471257e3974be7465200fc554a77b1e3ceea7f74",
  translationStatus: "machine",
)

Emacs 版本：GNU Emacs 26.1（也适用于 Emacs 24，甚至可能适用于更早的版本）

默认情况下，当从 emacs org-mode 导出 latex 和 PDF 文件时，日志文件在进程完成后会被删除，您可能希望保留它。

要使 emacs 停止删除日志文件，请按如下操作：

`M-x` -> `customize-variable`，`RET` -> `org-latex-remove-logfiles`

默认情况下，此变量设置为 `true`，意味着日志文件会被自动删除，然后您只需将其切换为 `false`，保存，重启 Emacs，您就可以开始使用了。
