#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/en/tutorials/2018/set-up-flarum-from-scratch.typ
// source_sha256: sha256:240bab1466e9f3ab4666507c69477a9d3ee3be3bff15f6a7dd55344ea349af30

#show: main.with(
  title: "从头开始设置 Flarum",
  desc: [在 Linux VPS 上从头开始设置 Flarum 论坛],
  date: "2018-01-06",
  tags: (

    blog-tags.linux,
    blog-tags.software,
  
  ),
  lang: "zh",
  i18nKey: "tutorials/2018/set-up-flarum-from-scratch",
  sourceLang: "en",
  translationSourceHash: "sha256:240bab1466e9f3ab4666507c69477a9d3ee3be3bff15f6a7dd55344ea349af30",
  translationStatus: "machine",
)

#link("https://flarum.org/docs/install.html")[在继续之前]

= 1. 从 Linode/Vultr/等获取 VPS

// 来自 sinaimg.cn 的外部图像不再可用。

= 2. 选择一个 Linux 发行版并使其运行（我使用 CentOS 7）。

// 来自 sinaimg.cn 的外部图像不再可用。

= 3. 安装 Apache/MySQL/PHP 7.1

== 创建一个非 root 的 sudo 用户

```bash
adduser USERNAME
passwd USERNAME
usermod -aG wheel USERNAME
su USERNAME
```

== 安装和配置 Apache

#link("https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-centos-7")[查看这个]

首先安装它。

```bash
sudo yum update
sudo yum -y install httpd
sudo systemctl enable httpd.service
```

然后创建目录结构。

```bash
sudo mkdir /etc/httpd/sites-available
sudo mkdir /etc/httpd/sites-enabled
```

打开配置文件：

```bash
sudo vim /etc/httpd/conf/httpd.conf
```

在文件末尾添加以下内容：

```conf
IncludeOptional sites-enabled/*.conf
```

== 安装 MySQL

CentOS 7 默认使用 `MariaDB` 而不是 MySQL，但使用它没有区别。

*注意：* yum 默认安装 MariaDB 5.5，这不再满足 flarum 的要求。#link("https://mariadb.com/resources/blog/installing-mariadb-10-on-centos-7-rhel-7/")[请查看这里]以获取安装 MariaDB 10 的说明。

```bash
sudo mysql_secure_installation
```

然后在 `MySQL` 中为 flarum 创建一个 `user` 和一个 `database`。

== 安装和配置 PHP

我在这里使用 php 7.1。

#link("https://webtatic.com/packages/php70/")[看看这个]

首先添加所需的 yum 仓库：

```bash
sudo rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
```

安装 php

```bash
sudo yum install mod_php71w php71w-cli php71w-xml php71w-mbstring php71w-mysql php71w-gd
```

= 4. 安装 Flarum

== 创建站点目录

将您的站点目录命名为您喜欢的任何名称，我将继续使用 `flarum`。

```bash
sudo mkdir /var/www/flarum
```

== 安装 composer

```bash
cd /tmp
sudo curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
```

== 获取 flarum 内容

```bash
cd /var/www
sudo yum install unzip
sudo chown USERNAME:GROUPNAME flarum
cd flarum
composer create-project flarum/flarum . --stability=beta
```

== 调整所有权和权限

将目录的所有者更改为 `apache` 以便 Apache 操作：

```bash
cd ..
sudo chown -R apache:apache flarum
```

= 5. 使其运行

== 为 flarum 在 Apache 中创建虚拟主机

将配置文件命名为您喜欢的任何名称：

```bash
cd /etc/httpd/sites-available
sudo vim flarum.conf
```

填写以下内容（*不要忘记 URL 重写块！*）：

```conf
<VirtualHost *:80>
    ServerName YOURDOMAIN
    ServerAlias ALIAS
    DocumentRoot /var/www/flarum/public
    ErrorLog /var/www/flarum/storage/logs/error.log
    CustomLog /var/www/flarum/storage/logs/requests.log combined

    <Directory "/var/www/flarum/public">
        DirectoryIndex index.php
        AllowOverride All
        allow from all
    </Directory>
</VirtualHost>
```

使您的配置生效

```bash
sudo ln -s /etc/httpd/sites-available/flarum.conf /etc/httpd/sites-enabled/flarum.conf
```

== 配置 firewalld 并重启 Apache 服务器

```bash
sudo firewall-cmd --add-service=http --permanent && sudo firewall-cmd --add-service=https --permanent
sudo systemctl restart firewalld
sudo apachectl restart
```

= 6. 访问您的 flarum 网站并享受！

== 注意：根据我的记忆写下这些，如果有任何遗漏，请在下面发表评论
