#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/en/tutorials/2018/using-virtualenv-in-jupyter-notebook.typ
// source_sha256: sha256:71cf0cc1aadf998ad5902170189aa6ab4c9fa01aa971627ad5633fcecae10662

#show: main.with(
  title: "在 Jupyter Notebook 中使用 virtualenv",
  desc: [在 Jupyter Notebook 中使用 virtualenv],
  date: "2018-05-09",
  tags: (

    blog-tags.python,
    blog-tags.tooling,
  
  ),
  lang: "zh",
  i18nKey: "tutorials/2018/using-virtualenv-in-jupyter-notebook",
  sourceLang: "en",
  translationSourceHash: "sha256:71cf0cc1aadf998ad5902170189aa6ab4c9fa01aa971627ad5633fcecae10662",
  translationStatus: "machine",
)

- 操作系统：macOS High Sierra 10.13.4
- 默认 Python 版本：3.6.5

= 前提条件

+ 已安装 `Jupyter Notebook` 和 `virtualenv`，并使用默认的 Python 版本
+ 已创建一个您想要使用的虚拟环境

= 操作步骤

== 激活您的 virtualenv

```bash
source <envpath>/bin/activate
```

== 在您的环境中安装 ipykernel

```bash
$(yourenv)> pip install ipykernel
```

== Create kernel using your env

```bash
$(yourenv)> python -m ipykernel install --user --name myenv --display-name "Python (myenv)"
```

== 开始享受

现在打开您的 Jupyter Notebook，您会注意到刚创建的内核与默认内核一起出现。享受吧
