#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/life/2019/2019-year-review.typ
// source_sha256: sha256:b6c9ebf1cddccb930294c1b9c671dc885cfdf5b2e94ff3990edabf6c0d4b893f

#show: main.with(
  title: "2019 Summary",
  desc: [2019 Summary],
  date: "2020-01-03",
  tags: (

    blog-tags.life,
  
  ),
  lang: "en",
  i18nKey: "life/2019/2019-year-review",
  sourceLang: "zh",
  translationSourceHash: "sha256:b6c9ebf1cddccb930294c1b9c671dc885cfdf5b2e94ff3990edabf6c0d4b893f",
  translationStatus: "machine",
)

*Another year has passed, and I still feel like I've accomplished nothing.*

I obtained a master's degree that is of little use. I once hoped that maybe I could study abroad, but now it seems like just an unattainable beautiful dream.

Work? I neither like it nor am I good at it; I fear that only my fear of the system drives me to do my job well. Yes, *fear*, since I started working, I have never acted out of a desire to “do something”; instead, I have been driven to do things solely to avoid some “bad outcome” from happening.

Life? Due to the instability of the work environment, I cannot continue with anything that requires persistence. Over time, I have developed a sense of powerlessness and resistance towards “persisting in doing” something. Perhaps this is what is called “learned helplessness”? 

Thus, my hobbies have also begun to languish, and the things that can bring me a sense of achievement are dwindling. Depression comes and goes like the tide, visiting me from time to time, making me feel increasingly distant from the reality of this world.

Relationships? They do not exist; who would want to approach such a pessimistic, negative, and dark person?

= New Year’s Wishes

1. Regain a sense of achievement
2. Don’t care too much about others’ opinions
3. Keep an open mind and be brave to try
4. Become happy
