#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/meta/2025/debut.typ
// source_sha256: sha256:2dd014173a6edc2e59a8872c6a9384fd2e2b63ddddc343dded49a99758449d5a

#show: main.with(
  title: "New Blog Debut",
  desc: [My new blog debut, with a new theme and a new look.],
  date: "2025-08-23",
  tags: (

    blog-tags.life,
    blog-tags.typst,
  
  ),
  lang: "en",
  i18nKey: "meta/2025/debut",
  sourceLang: "zh",
  translationSourceHash: "sha256:2dd014173a6edc2e59a8872c6a9384fd2e2b63ddddc343dded49a99758449d5a",
  translationStatus: "machine",
)

Created a new blog website using a new tech stack.

Tech stack:

- Astro
- Typst
- Tailwind CSS
