#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

#show: main.with(
  title: "The Blog Now Speaks Two Languages",
  desc: [The blog now supports bilingual articles and AI-assisted translation.],
  date: "2026-05-25",
  tags: (
    blog-tags.blog,
    blog-tags.typst,
    blog-tags.software,
  ),
  lang: "en",
  i18nKey: "meta/2026/bilingual-blog",
  sourceLang: "en",
  aiAuthored: true,
)

Recently I finally added bilingual support to the blog.

The site now has both English and Chinese routes. Articles are no longer tied to only one language. When I write something in English, the blog can generate a Chinese version; when I write something in Chinese, it can generate an English version. The two files are still normal Typst source files, so they can be committed, reviewed, edited, and rebuilt like the rest of the site.

= Why

The main reason is simple: I want more people to be able to read the same content.

A personal blog is often written for myself first, but it is still published on the open web. If an article is only in one language, then a lot of readers will simply skip it, not because the topic is useless, but because the entry cost is too high. Bilingual articles lower that cost a little.

AI translation is good enough now to make this practical. It may not always be perfect, but it can produce a usable first draft very quickly. After that I can review the translation when I care about the article, or leave it clearly marked as machine translated when I do not have time.

= How it works

This is not runtime translation.

The blog does not call an API when someone opens a page. Instead, translation is a build-time source generation step. The script reads the original Typst file, asks the model to translate the prose, preserves the code blocks, links, paths, math, and Typst commands, then writes another `.typ` file in the other locale.

So the final website is still just a normal static-ish blog. Cloudflare does not need an OpenAI key. Readers do not wait for a translation request. Search engines can see real localized pages. And if I dislike the generated result, I can edit it directly.

= Source, machine, reviewed

Each article has a small translation status.

- `source` means this is the human-written original.
- `machine` means this file was generated by AI.
- `reviewed` means I have checked it and do not want the script to overwrite it casually.

I also made `source` the default, because future me will definitely forget to type one field sooner or later.

= Tinkering continues

This update is mostly invisible when everything works. The homepage still looks like a homepage, articles still look like articles, and the archive is still the archive. But behind the scenes, the content model is a little more complete now.

It feels like a small infrastructure change, but it changes who can read the site. That is worth the trouble.

*The tinkering never ends.*
