#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/meta/2026/blog-update.typ
// source_sha256: sha256:1ad121ccbcf0dca8c4482e73517b4ff7a1f7bb926d9c17fb8ec2645811fb2006

#show: main.with(
  title: "Blog Update",
  desc: [Blog style update],
  date: "2026-01-08",
  tags: (

    blog-tags.programming,
    blog-tags.software,
    blog-tags.blog,
  
  ),
  lang: "en",
  i18nKey: "meta/2026/blog-update",
  sourceLang: "zh",
  translationSourceHash: "sha256:1ad121ccbcf0dca8c4482e73517b4ff7a1f7bb926d9c17fb8ec2645811fb2006",
  translationStatus: "machine",
)

= Style Update

Inspired by #link("https://www.yysuni.com/")[YYsuni Blog], I decided to update (copy) the blog style. The original black and red color scheme has been changed to the current frosted glass colorful background style, with red as the main color, fresh and bright.

= Typography Update

Inspired by #link("https://github.com/Yousa-Mirage/Tufted-Blog-Template")[Tufted-Blog-Template], I added Tufed style side notes and footnotes to the blog, which can change responsively. Side notes are displayed when the screen is wide, and footnotes are shown when the screen is narrow #footnote[This is a footnote, displayed beside the content on wide screens and at the bottom on narrow screens.].

*The tinkering never ends.*
