#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by HemiAssistMac
// prompt_version: manual-translation-v1
// source: content/article/zh/meta/2026/cloudflare-d1-typst-astro-blog-stack.typ
// source_sha256: sha256:1e4a016b58464e249d091fadaf556bccea34eb73b5f1df54f993396ce4d02c75

#show: main.with(
  title: "Wonderland Blog Stack and Copy-Deployment Guide",
  desc: [This article documents the repository structure and deployment path behind this site: Astro organizes the site, Typst owns the content, Cloudflare runs the runtime layer, and D1 stores only data that truly needs dynamic state.],
  date: "2026-06-25",
  tags: (
    blog-tags.blog,
    blog-tags.cloudflare,
    blog-tags.astro,
    blog-tags.typst,
    blog-tags.software,
  ),
  lang: "en",
  i18nKey: "meta/2026/cloudflare-d1-typst-astro-blog-stack",
  sourceLang: "zh",
  aiAuthored: true,
  translationSourceHash: "sha256:1e4a016b58464e249d091fadaf556bccea34eb73b5f1df54f993396ce4d02c75",
  translationStatus: "machine",
)

My current blog stack can be summarized in one sentence: *Astro organizes the website, Typst writes articles and generates content, Cloudflare hosts the runtime, and D1 stores only dynamic data such as comments.*

This article is not a from-zero tutorial for building an Astro blog. More precisely, it is a structure note and copy-deployment guide for the Wonderland repository: if you like this shape, the easiest path is not to recreate every dependency by hand. Copy the repository, change the site identity, Cloudflare bindings, D1 database, and PDF artifact configuration, then verify and deploy through the existing project scripts.

The configuration and commands below come from the current repository of this site. Code snippets are trimmed core shapes for explanation, not byte-for-byte copies of the complete files.#footnote[If you are deploying from this article, treat the repository files as the source of truth. The snippets intentionally omit surrounding fields so the explanation does not become a brittle copy checklist.]

= Where this site came from

Wonderland did not grow from an empty directory. The code base of this site came from #link("https://github.com/Myriad-Dreamin/tylant")[Myriad-Dreamin/tylant]. I copied the foundation from the Tylant project and gradually turned it into this personal blog.

That is also why Typst is not just a small add-on in this repository. It has been part of the content model and template system from the beginning: article sources are `.typ` files, templates live under `templates/`, Astro renders Typst content to HTML through `astro-typst` at build time, and PDFs are generated and published as separate artifacts through scripts.#footnote[Here, artifact means a tarball keyed by the PDF input hash and uploaded to GitHub Releases. The Cloudflare build downloads and extracts it; it does not compile the full PDF corpus on the spot.]

= Stack responsibilities

== Astro: the site orchestration layer

Astro handles routing, layouts, content collections, RSS, sitemap, and connecting rendered Typst output to pages. This site uses `output: "server"` with `@astrojs/cloudflare`, so one repository can contain all of these at the same time:

- prerendered article pages, list pages, tag pages, and archive pages;
- API routes that need Worker runtime;
- the Worker entry and static asset directory generated by the Cloudflare adapter.

The important dependencies are visible in `package.json`:

```json
{
  "@astrojs/cloudflare": "^12.6.6",
  "@astrojs/rss": "^4.0.12",
  "@astrojs/sitemap": "^3.5.0",
  "astro": "^5.13.2",
  "astro-typst": "^0.11.2",
  "@myriaddreamin/typst-ts-node-compiler": "^0.6.1-rc2",
  "drizzle-orm": "^0.44.5",
  "wrangler": "^4.33.1"
}
```

When deploying a copied repository, you do not need to `bun add` these dependencies manually. Just run `bun install`.

== Typst: the content and typography layer

The articles on this site are not Markdown files. They are `.typ` files. Every article imports the same template and tag enum:

```typst
#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

#show: main.with(
  title: "Article title",
  desc: [Article summary],
  date: "2026-06-25",
  tags: (
    blog-tags.blog,
    blog-tags.typst,
  ),
  lang: "en",
  i18nKey: "meta/2026/example",
  sourceLang: "en",
)
```

This Typst writing setup came from Tylant. When copying the repository, the important part is to preserve and understand these boundaries:

- `content/article/`: article sources, organized by language and category;
- `templates/blog.typ`: article HTML rendering entrypoint;
- `templates/enums.typ`: tag registry;
- `templates/article-pdf.typ` and `templates/archive.typ`: PDF export templates;
- `packages/mathyml/`: local Typst package for math-related rendering;
- `assets/fonts/noto-cjk-sc/`: Noto CJK fonts used by PDFs, managed through Git LFS.

Metadata can still be read by Astro content collections. This site uses `src/content.config.ts` to constrain fields such as `title`, `date`, `tags`, `lang`, `i18nKey`, and `translationStatus`, so article lists, RSS, archives, and language switching do not each maintain their own copy of the same facts.

== Cloudflare: the deployment and runtime layer

This site does not stop at generating a pile of purely static files. The core `astro.config.mjs` shape is:

```js
export default defineConfig({
  site: "https://dyz.io",
  output: "server",
  integrations: [
    typst({ target: "html" }),
    sitemap(),
  ],
  adapter: cloudflare({
    platformProxy: {
      enabled: true,
    },
  }),
});
```

`output: "server"` makes Astro generate a Cloudflare Worker entry. Individual pages can still be prerendered with `export const prerender = true`. On this site, article detail pages are prerendered; the comments component and submit endpoint are runtime code.

The matching `wrangler.toml` needs at least the Worker name, static asset binding, and D1 binding:

```toml
name = "wonderland"
compatibility_date = "2025-04-28"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js/index.js"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "wonderland"
database_id = "replace this with your own D1 database_id"
```

The `[assets]` block matters.#footnote[This is the key boundary in the Workers + Static Assets setup: Worker code owns runtime logic, while prerendered pages, CSS, images, and PDFs still need to be exposed to the Worker through the assets binding.] The Worker generated by the Cloudflare adapter uses `env.ASSETS.fetch(...)` to serve static assets and fallback requests. Without that binding, a production failure may not be a content bug at all; the Worker simply cannot reach the generated static assets.

== D1: store only dynamic state

My rule is: articles do not belong in D1. Articles, pages, archives, tags, and translation files belong in Git and are turned into a site by the build system. D1 is only for things that truly need runtime state, such as comments.

The D1 binding name of this site is `DB`, and the comments module uses `drizzle-orm/d1`. Migration files live under `migrations/` and currently include:

- `0001_init.sql`: creates the original `comments` table;
- `0002_harden_comments.sql`: adds `thread_key`, `status`, `email_hash`, `user_agent_hash`, `updated_at`, and indexes.

Comments are currently written directly as `approved`. The `status` field mainly reserves room for future moderation, spam handling, and deletion states.

= Where to look first in the repository

Before copying this repository, read it by responsibility rather than by following a framework tutorial.

```text
content/article/              # Article sources, zh/en aligned by i18nKey
content/page/                 # Page sources such as about
templates/                    # Typst HTML/PDF templates and tag enum
src/content.config.ts         # Astro content collection schema
src/i18n/                     # Locale, routing, messages, content selection
src/layouts/BlogPost.astro    # Article detail shell, comments, PDF link
src/components/comment/       # Comment UI
src/features/comments/        # D1 schema, reads/writes, form validation
src/pages/api/comments/       # Comment submit API
migrations/                   # D1 schema migrations
scripts/d1-reset-local.mjs    # Local D1 reset helper
scripts/pdf/                  # PDF version, generate, publish, fetch
assets/fonts/noto-cjk-sc/     # PDF fonts managed by Git LFS
astro.config.mjs              # Astro + Cloudflare adapter config
wrangler.toml                 # Cloudflare Worker, assets, D1 bindings
package.json                  # Unified script entrypoints
```

The boundary is the important part: `content/` and `templates/` are content sources; `src/pages/` decides which pages are prerendered and which endpoints run at runtime; `src/features/comments/` encapsulates D1; `scripts/pdf/` keeps heavy PDF generation out of Cloudflare builds.

= What to change after copying the repository

Assume you have forked or copied the repository. Change it in this order.

== 1. Clone and pull LFS fonts

```bash
git clone https://github.com/<your-name>/<your-repo>.git
cd <your-repo>
git lfs install
git lfs pull
bun install
```

Do not skip `git lfs pull`.#footnote[Git LFS pointer files are text files that can make it look as if the file exists, but they only contain object metadata. The PDF compiler needs the actual `.otf` / `.ttf` font data.] PDF generation depends on the Noto CJK fonts under `assets/fonts/noto-cjk-sc/`; if you only have Git LFS pointer files, `pdf:generate` will fail with a clear error.

== 2. Change the site identity

At minimum, inspect these files:

```text
astro.config.mjs          # site: "https://your-domain"
src/consts.ts             # SITE_TITLE / SITE_AUTHOR / SITE_DESCRIPTION
src/i18n/messages.ts      # Chinese/English site descriptions and UI text
content/page/zh/about.typ # Chinese About page
content/page/en/about.typ # English About page
scripts/pdf/lib.mjs       # siteAuthor / siteUrl, used by PDF metadata and source links
```

If you are only testing a copied deployment, changing the domain and author may be enough at first. If you plan to maintain it long-term, update the About pages, RSS text, and PDF metadata together; otherwise generated HTML, RSS, or PDFs can still contain the original site identity.

== 3. Change Cloudflare configuration

At minimum, edit `wrangler.toml`:

```toml
name = "your worker name"
account_id = "your Cloudflare account_id"

[[d1_databases]]
binding = "DB"
database_name = "your D1 database name"
database_id = "your D1 database_id"
```

I recommend keeping `binding = "DB"` unless you also update the code that reads `Astro.locals.runtime?.env.DB`.

Create the D1 database:

```bash
bunx wrangler login
bunx wrangler d1 create <your D1 database name>
```

Copy the resulting `database_id` back into `wrangler.toml`.

== 4. Initialize local and remote D1

For local development, use the project script:

```bash
bun run db:reset
```

Production migrations must explicitly target remote. The project has a script for that too:

```bash
bun run db:migrate:remote
```

Or use the equivalent Wrangler command:

```bash
bunx wrangler d1 migrations apply <your D1 database name> --remote
```

Do not put `DROP TABLE` into production migrations. If you need to clear the local database, use a clearly named local script such as `scripts/d1-reset-local.mjs`.

== 5. Configure comments and Turnstile

The comments area reads `Astro.locals.runtime?.env.DB` and queries D1 through Drizzle. If D1 is unavailable, the list shows “Comments are temporarily unavailable.” instead of crashing the whole article page.

Turnstile is an optional enhancement. The logic on this site is:

- with `TURNSTILE_SITE_KEY`, the frontend renders the Turnstile widget;
- with `TURNSTILE_SECRET_KEY`, the server verifies `cf-turnstile-response`.

Production should either set both or set neither.#footnote[`TURNSTILE_SITE_KEY` is for the browser widget; `TURNSTILE_SECRET_KEY` is server-only and verifies the submitted token with Cloudflare. Missing either side leaves you with an incomplete Turnstile setup.] Setting only the secret means the frontend has no token and submissions fail; setting only the site key displays the widget but does not make the server verify it.

Configure the secret with:

```bash
bunx wrangler secret put TURNSTILE_SECRET_KEY
```

`TURNSTILE_SITE_KEY` is not secret, so you can put it in Cloudflare dashboard variables or inject it through your deployment flow.

= Local verification flow

After copying and editing, run content checks first:

```bash
bun run validate
bun run i18n:check:strict
```

Then verify HTML and Worker output:

```bash
bun run build:site
```

If you need PDFs, verify the PDF artifact too:

```bash
bun run pdf:generate
```

The full production build is:

```bash
bun run build
```

This site's `build` script is:

```bash
astro build && node scripts/pdf/fetch.mjs
```

In other words, HTML is built by Astro, while PDF files are fetched through a separate artifact flow. This avoids compiling a large Typst PDF corpus during Cloudflare builds: HTML rendering can stay in the normal build, while heavy PDF generation belongs in local tooling or a separate CI step.

= PDF artifacts and GitHub Releases

This repository's PDF publishing flow depends on the GitHub remote. `scripts/pdf/lib.mjs` first reads `PDF_ARTIFACT_REPO`, then tries to infer the GitHub repository from `git remote get-url origin`, and only then falls back to `dyzdyz010/wonderland`.

After copying the repository, either point `origin` at your own GitHub repository or set:

```bash
export PDF_ARTIFACT_REPO=<your-name>/<your-repo>
```

Generate and publish the PDF artifact:

```bash
bun run pdf:prepare
```

It is equivalent to:

```bash
bun run pdf:generate
bun run pdf:publish
```

`pdf:publish` uses GitHub CLI `gh release`, so the machine running it must be logged in to GitHub and have release upload permission on the target repository.

There is an important precondition here: whenever articles, PDF templates, PDF scripts, or lockfiles change, the PDF version hash may change.#footnote[The hash intentionally changes when PDF inputs change. That prevents Cloudflare from reusing stale PDFs, but it also means every PDF-affecting change must publish a matching artifact first.] The `pdf:fetch` step inside `bun run build` looks for a tarball matching the current hash; if the GitHub Release does not have that artifact yet, it will fail with a 404. That is not usually an Astro or Cloudflare configuration problem. It means the PDF artifact must be generated and published first.

= Deploying to Cloudflare

Before the first deployment:

```bash
bunx wrangler login
bunx wrangler d1 create <your D1 database name>
bun run db:migrate:remote
```

Before deployment, make sure the PDF artifact has been published:

```bash
bun run pdf:prepare
```

Then build and deploy the Worker:

```bash
bun run build
bunx wrangler deploy
```

This repository is currently configured for Workers + Static Assets + `wrangler deploy`. If you move it to Cloudflare Pages Git integration, you need to configure D1 bindings and environment variables again in the Pages project, and you still need the build environment to download the already published PDF artifact. Do not assume the `wrangler.toml` in this article can be migrated unchanged.

= What to verify after deployment

Seeing the homepage load is not enough. At minimum, check:

- homepage, article pages, tag pages return 200;
- article detail HTML has the correct title, description, language switch, and canonical/hreflang links;
- the comments server island really loads, instead of leaving only a placeholder in the main HTML;
- failed comment submissions degrade gracefully;
- open one article PDF and one archive PDF;
- remote D1 migrations have been applied to the production database.

Pay special attention to comments. The main Astro article HTML can return 200 while the server island comments area still fails because of a missing D1 binding, unapplied migration, or Turnstile misconfiguration. Verify the comments area separately.#footnote[For automated smoke tests, extract the `/_server-islands/Comments?...` preload URL from the article HTML and request that island response directly, rather than trusting only the main page's HTTP 200.]

= Common pitfalls

== Forgetting to change PDF metadata

The `site` field in `astro.config.mjs` affects the Astro site. PDF `siteAuthor` and `siteUrl` currently also live in `scripts/pdf/lib.mjs`. If you copy the repository and only change Astro config, generated PDFs may still contain the original site author or source links.

== Forgetting Git LFS fonts

PDF generation depends on `assets/fonts/noto-cjk-sc/`. If a new machine only cloned LFS pointers and not the real font files, `bun run pdf:generate` will fail. Run this first:

```bash
git lfs pull
```

== Making everything runtime

The strength of this stack is not that everything is dynamic. The strength is that the dynamic boundary is small. The more articles and archives stay static, the lighter the Worker becomes, the more stable deployment is, and the simpler SEO becomes.

== Running native Typst PDF compilation in Cloudflare runtime

Typst HTML rendering and Astro building can happen at build time. Large-scale PDF generation should not be pushed into Cloudflare build or Worker runtime. This site uses an artifact flow to separate PDF generation from the normal site build, and the `build` script only fetches already published PDFs at the end.

If `astro build` succeeds but `bun run build` later fails in `pdf:fetch` with a 404, it is usually not an Astro or Cloudflare adapter problem. The current PDF version artifact has not been published yet. Run `bun run pdf:prepare` first, or use `bun run build:site` when you only need to verify site HTML.

== Forgetting the `[assets]` binding

The Worker generated by `@astrojs/cloudflare` needs access to static assets. If `wrangler.toml` is missing this block:

```toml
[assets]
directory = "./dist"
binding = "ASSETS"
```

some production routes can fail in confusing ways.

= Copy-deployment checklist

Here is the minimal checklist:

1. Fork or copy `dyzdyz010/wonderland` to your own GitHub repository.
2. After `git clone`, run `git lfs pull` and `bun install`.
3. Change site identity in `astro.config.mjs`, `src/consts.ts`, `src/i18n/messages.ts`, About pages, and `scripts/pdf/lib.mjs`.
4. Create a D1 database on Cloudflare and write the `database_id` into `wrangler.toml`.
5. Keep the D1 binding as `DB`, or update every `env.DB` usage in the code.
6. Locally run `bun run validate`, `bun run i18n:check:strict`, `bun run db:reset`, and `bun run build:site`.
7. If PDFs are needed, run `bun run pdf:generate`; before deployment, run `bun run pdf:prepare` to publish the artifact.
8. Run `bun run db:migrate:remote` for production.
9. Finally run `bun run build` and `bunx wrangler deploy`.
10. After deployment, verify article pages, comments, D1, PDF links, RSS, and sitemap.

The key to this architecture is not one particular library. It is the boundary: *content is source code, pages are as static as possible, Cloudflare hosts the runtime, and D1 stores only dynamic state.* When copying the repository, preserve that boundary instead of mixing content, runtime data, deployment configuration, and PDF artifacts together.
