#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2021/windows-git-proxy.typ
// source_sha256: sha256:f06ae80329bf1e0d52ab55755bfacfcc14dc238fce92791d75ba13b1a59831ad

#show: main.with(
  title: "Using a Proxy with Git on Windows",
  desc: [Using a Proxy with Git on Windows],
  date: "2021-08-02",
  tags: (

    blog-tags.windows,
    blog-tags.git,
  
  ),
  lang: "en",
  i18nKey: "tutorials/2021/windows-git-proxy",
  sourceLang: "zh",
  translationSourceHash: "sha256:f06ae80329bf1e0d52ab55755bfacfcc14dc238fce92791d75ba13b1a59831ad",
  translationStatus: "machine",
)

Reference link: #link("https://gist.github.com/UnluckyNinja/73a9c699fb807d57dad8b482fff57cb6")[Using Git with Clash's SOCKS proxy]

- *System:* Windows 10
- *Proxy Software:* Clash for Windows

Setting up a proxy on Windows can be really tricky... Git often acts up when not using a proxy, and it took me all night to clone a repository... Eventually, I found the link above, and after setting it up, Git finally started working. Once again, I have to complain about Windows' proxy settings; it's terrible.

```toml
[core]
	gitproxy = socks5://127.0.0.1:7890
[http]
	postBuffer = 524288000
	postBuffer = 524288000
	proxy = socks5://127.0.0.1:7890
[https]
	postBuffer = 524288000
	postBuffer = 524288000
	proxy = socks5://127.0.0.1:7890
```
