#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/life/2022/20220902-recent-thoughts.typ
// source_sha256: sha256:39355a14afedc1dec9fca6ca7e0dcf80ff4b5b0557ba021dd8325de0562ac8dd

#show: main.with(
  title: "Autumn Has Arrived",
  desc: [Autumn Has Arrived],
  date: "2022-09-02",
  tags: (

    blog-tags.life,
  
  ),
  lang: "en",
  i18nKey: "life/2022/20220902-recent-thoughts",
  sourceLang: "zh",
  translationSourceHash: "sha256:39355a14afedc1dec9fca6ca7e0dcf80ff4b5b0557ba021dd8325de0562ac8dd",
  translationStatus: "machine",
)

Autumn has come.

The previously scorching hot weather suddenly turned cold one day, as if there was no transition at all, dropping directly from over thirty degrees to just over ten degrees, with even nighttime lows reaching single digits.

The climate is so unreasonable—when the wind is most needed, it doesn’t come. Just when people are about to forget its existence, it returns to remind them. When the wind picks up, it adds to the already dropping temperatures, creating an illusion that winter is just around the corner.

Compared to visuals, scents evoke my past memories even more. The smell in the air changes with the seasons and is also related to geographical location. Every time I finish work and step outside after dinner, taking a deep breath feels like I’m transported back to a moment in the past, recalling every detail as I walk.

For example, right now, I’m sitting at a table by the window, writing this text. The cool breeze from outside occasionally blows in, and the sounds of cars passing by remind me of my middle school days, when I would finish my homework at night, feeling stifled and unable to vent my emotions, so I would ask my dad to take me out for a drive. The night, the cool wind, and the people on the road all give me a sense of tranquility. Seeing others rushing by helps me maintain the feeling that I am still alive in this world. From time to time, I would ask my dad to take me to the train station during our drives, watching the people departing and arriving, which would give me an inexplicable sense of peace, as if I were also part of the crowd.

After the memories fade, I feel much refreshed, as if I’ve just returned from somewhere else, experiencing a sense of relief. I remember that during my university days, I rarely reflected on the past, always focused on moving forward and what achievements tomorrow might bring. It seems that growing older does indeed influence one’s thoughts. Now, I often reminisce about past events and sometimes wonder: what if I had made a different decision back then, what would things be like now? This is just a hypothesis; I do not regret my past because I remember the feelings and thoughts I had each time I made a choice.

Now, I have a better grasp of the possibilities for the future than I ever did before. I have goals, motivation, and capability; perhaps I shouldn’t devote most of my mental energy to reminiscing about the past, but rather focus all my efforts on moving towards my goals. I dream almost every day, not sure if it’s a sign of mental overload.

Driven by clear goals, I sometimes become overly focused and neglect some people and things around me, resulting in others perceiving me as cold and distant. By the time I finish my tasks and come back to reality, the impression I’ve left on others has already solidified, making it harder for me to interact with them. After years of running around, it has already been difficult to develop relationships, and now in this place, it feels even harder to integrate. Every day gives me a sense of being an "outsider."

There’s no point in saying more; it feels like only I can truly feel this. In comparison, achieving my own goals is what truly matters. I should break free from living under the gaze of others and find ways to pursue my "self."
