#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/life/2022/20220620-about-weibo.typ
// source_sha256: sha256:96cc1483d4afaa31401cf94b55b2dc67640123ade4eb546d3c461ff3a0ac671d

#show: main.with(
  title: "About Weibo",
  desc: [About Weibo],
  date: "2022-06-20",
  tags: (

    blog-tags.life,
  
  ),
  lang: "en",
  i18nKey: "life/2022/20220620-about-weibo",
  sourceLang: "zh",
  translationSourceHash: "sha256:96cc1483d4afaa31401cf94b55b2dc67640123ade4eb546d3c461ff3a0ac671d",
  translationStatus: "machine",
)

Before the Weibo feature of the blog theme is set up, let's use a regular post as a substitute.

It’s really lonely when you’re alone, with emotions having no outlet and no one to confide in. Thoughts can't just stay in your head; you need to find a way to express them.
