#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/life/2022/20220520-thoughts-on-medical.typ
// source_sha256: sha256:cebb71bf0ce36ed1c0c57b68e1dbdd86d18e12de84cf3ccbea0709e39a318fa1

#show: main.with(
  title: "Reflections - On Healthcare",
  desc: [Reflections - On Healthcare],
  date: "2022-05-20",
  tags: (

    blog-tags.life,
  
  ),
  lang: "en",
  i18nKey: "life/2022/20220520-thoughts-on-medical",
  sourceLang: "zh",
  translationSourceHash: "sha256:cebb71bf0ce36ed1c0c57b68e1dbdd86d18e12de84cf3ccbea0709e39a318fa1",
  translationStatus: "machine",
)

Recently, my visits to the hospital for a check-up and an emergency made me more convinced of my belief that healthcare is not something we can take for granted in our daily lives; rather, it is akin to a luxury good and a random service that cannot be relied upon for major issues.

First, let's talk about the attitude of service. Some may argue that hospitals are only responsible for treatment and are not service industries, so there is no need to pay attention to how they treat others. However, I often wonder, since the placebo effect is real, why can't it be applied in doctor-patient communication? Isn't the goal of hospitals and doctors to help patients recover? If so, shouldn't all methods that can assist in achieving this goal be utilized as much as possible? I often see online that doctors tell cancer patients to maintain a positive mindset, relax, and manage their emotions, which helps in cancer treatment. So, I ask, does a good mood and mindset have no impact on other diseases? Is it only relevant for terminal patients? If it does affect other ailments, then why can't we find ways to help patients maintain a relatively stable mood during their medical consultations? My experience when communicating with hospital staff is that he/she seems to be venting their own frustrations or grievances while talking to patients, only to turn to colleagues and show a completely different demeanor, relaxed and cheerful. This scene feels very sad to me, a sense of condescension and arrogance. Not to mention that some patients may not fully understand certain aspects and when they inquire with doctors or nurses, it feels like a teacher reprimanding a primary school student.

In my view, the emotions conveyed through language are very valuable; a friendly tone is certainly more acceptable than a harsh one. Some might say, "I put in so much effort to speak kindly, yet no one gives me a raise; isn't that a waste?" However, from another perspective, aside from the unreasonable, some patients are emotionally impulsive, speaking harshly to doctors and nurses, even engaging in "medical disputes," which I believe is related to the tone of communication from some doctors and nurses. An angry, impatient, or dismissive tone is, in my opinion, tantamount to provocation, exacerbating the already low spirits of patients rather than improving them, at least stabilizing them is out of the question; it only adds fuel to the fire. This undoubtedly increases the instability of patients' emotions, and if someone has a fiery temper, it is not surprising that it escalates into verbal or physical conflict.

Currently, society is constantly condemning "medical disputes," and I also oppose them, but we cannot just shout slogans without exploring the root causes of the problem. We all know that combating crime is not just about punishing individuals who commit crimes; it requires analyzing macro data on crime in the area: why is the crime rate high here? Is it due to economic development levels? After identifying the causes, we should address them to reduce the crime rate. However, in the healthcare sector, for some reason, such discussions are rare; there are various calls for the healthcare industry to be noble and hardworking, and people should understand that anyone causing harm should be held accountable. Very few people analyze the deeper reasons for the prominent doctor-patient conflicts and tense relationships today; instead, they project their stereotypes, claiming that certain individuals are bad or malicious, and that patients should inherently understand all medical processes and procedures. I want to say that while holding individuals accountable is one aspect, preventing problems before they arise is another; we cannot neglect one for the other. Moreover, prevention is the fundamental way to resolve doctor-patient conflicts. During doctor-patient communication, if doctors can at least maintain a calm demeanor and a normal tone, it minimizes the negative emotions generated during the exchange, preventing the patient's mood from deteriorating further due to language, and reducing the likelihood of conflict between doctors and patients. Isn't that a win-win situation?

In addition, a good tone can also positively impact one's own mindset and emotions. Therefore, if the medical community has been in an environment overflowing with negative emotions for years, why not try to improve their own emotions? It might yield better results than merely venting.

Perhaps because I am not a fan of conflict and feel repulsed by such a tense atmosphere, I have always believed that the doctor-patient relationship should develop positively, rather than becoming increasingly fragmented as it is now. Everyone should strive for a better direction, so that society and life can improve. This mentality of "those not of my kind must have different intentions" is widespread across various industries, and I wonder if it is the result of more people losing their empathy. I believe that anyone with empathy would have the thought of "do not impose on others what you do not desire for yourself" and should not let their personality and way of dealing with things be alienated by their profession. We should possess the ability to transfer emotions to those around us, to empathize, to understand, and to express, not only in doctor-patient relationships but in any relationship between parties. Personally, I really do not want to live in a society where everyone is cold, guarded, distrustful, and ready to confront each other.

Secondly, regarding the content provided by the healthcare industry, namely healthcare itself. I do not want to call it *healthcare service* because I feel that healthcare and service are not on the same level. In my view, hospitals should not be purely profit-driven institutions, or the profit-making aspect and the healthcare provided should be in separate tracks. Healthcare is the last resort for protecting life, holding a special status; if it is allowed to be enveloped by the desire for profit, then the rights to life and health today will be no different from those in ancient times, both being unprotected castles in the air. In my opinion, the healthcare industry should learn from the recruitment strategies of the military; doctors and soldiers are alike, one defends national interests, while the other ensures individual life and health, both holding absolute honor. The entry standards for the healthcare system should also be relatively strict, with hospitals and medical professionals becoming units and personnel protected by the state, filtering out those who genuinely want to save lives rather than the current mixed bag. Such an important industry as healthcare should not be submerged in the vast ocean of market economy.

However, that being said, the communication process between doctors and patients is also part of providing healthcare content, after all, the chain of language - emotion - physical health is real. If some people cannot consider this factor, can I assume that their ultimate goal is not the health of patients? Is healthcare still healthcare if it does not take patient health as the ultimate goal? Or is healthcare really like a luxury good, not meant for the general public?

All of the above are thoughts that I can say are quite unrealistic, but my hope for society to become better is genuine. Before any changes occur, the current state of healthcare is as it is. On one hand, we want healthcare to improve, but on the other hand, we should not place all our hopes on the healthcare industry; we must take responsibility for our own health while eliminating false hopes. Doing our part and leaving the rest to fate is the way to navigate life; we should do what we can, whether it is exercising or living healthily; the rest should be left to destiny, rather than unrealistically fantasizing that hospitals can solve all your ailments.

*No, they cannot.*
