#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

#show: main.with(
  title: "Use Hugo with Github Pages and CircleCI",
  desc: [Use Hugo with Github Pages and CircleCI],
  date: "2019-03-28",
  tags: (
    blog-tags.blog,
    blog-tags.tooling,
  ),
)

This tutorial is to teach you how to make youre own hugo-generated static site served by Github Pages, within a single repo.

= Prerequisites

+ Github & CircleCI account
+ Newly-generated SSH key pair for safety reasons(#link("https://circleci.com/docs/2.0/add-ssh-key/")[reference])
+ Hugo installed locally

= Dive in

Generate site source with `hugo` command:

```bash
hugo new site <SITE_NAME>
```

Create a repo for your site: `<SITE_NAME>.github.io` *Be aware: this tutorial uses _User/Organization Pages_ rather than _Project Pages_(#link("https://help.github.com/en/articles/user-organization-and-project-pages")[reference])*, clone it, and create a new branch called `source`(whatever you like):

```bash
git clone https://github.com/<USERNAME/ORGANIZATION>/<SITE_NAME>.github.io.git
cd <SITE_NAME>.github.io
git checkout -b source
```

Copy everything from the folder created by hugo above into repo:

```bash
mv ../<SITE_NAME>/* .
```

Go to circleci.com and add your project. Goto `Project Settings`, under `SSH Permissions`, add SSH private key you just generated (#link("https://circleci.com/docs/2.0/add-ssh-key/")[reference]), copy the `Fingerprint` for use below.

Go to Github your project settings, under `Deploy Key`, add SSH public key you just generated.

Create config file for CircleCI:

```bash
mkdir .circleci
cd .circleci
touch config.yml
```

`config.yml`(Edit it with your own information):

```yaml
version: 2.0

jobs:
    build:
        docker:
            - image: felicianotech/docker-hugo:latest
        working_directory: ~/<SITE_NAME>.github.io
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "<FINGERPRINT_YOU_JUST_COPIED"
            - checkout
            - run:
                name: Get current site
                working_directory: ~/
                command: git clone -b master git@github.com:<USERNAME/ORGANIZATION>/<SITE_NAME>.github.io.git public
            - run:
                name: Generate site
                working_directory: ~/<SITE_NAME>.github.io
                command: HUGO_ENV=production hugo -d ~/public
            - deploy:
                name: Deploy to Github Pages
                working_directory: ~/public
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "<YOUR_EMAIL>"
                    git config user.name "Deployment Bot"
                    git add .
                    git commit --allow-empty -m "Trigger deployment"
                    git push -q git@github.com:<USERNAME/ORGANIZATION>/<SITE_NAME>.github.io.git master

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: source
```

Now push your files to Github:

```bash
git add .
git commit -m "first commit"
git push origin source
```

For every time you push to the `source` branch, CircleCI will always trigger a hugo generation to the `master` branch, where the site's static file generated by Hugo is placed.

Wait for CircleCI's job done, then visit `<SITE_NAME>.github.io` and enjoy!
