#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/en/tutorials/2019/hugo-with-github-pages.typ
// source_sha256: sha256:b46ddc296aa4049f0404b55de880df298ca85f660b2c3c4831f36e62550e12f5

#show: main.with(
  title: "在 Github Pages 和 CircleCI 上使用 Hugo",
  desc: [在 Github Pages 和 CircleCI 上使用 Hugo],
  date: "2019-03-28",
  tags: (

    blog-tags.blog,
    blog-tags.tooling,
  
  ),
  lang: "zh",
  i18nKey: "tutorials/2019/hugo-with-github-pages",
  sourceLang: "en",
  translationSourceHash: "sha256:b46ddc296aa4049f0404b55de880df298ca85f660b2c3c4831f36e62550e12f5",
  translationStatus: "machine",
)

本教程旨在教您如何在单个仓库中使用 Github Pages 提供您自己的 Hugo 生成的静态网站。

= 先决条件

+ Github 和 CircleCI 账户
+ 出于安全原因新生成的 SSH 密钥对 (#link("https://circleci.com/docs/2.0/add-ssh-key/")[reference])
+ 本地安装 Hugo

= 深入了解

使用 `hugo` 命令生成网站源代码：

```bash
hugo new site <SITE_NAME>
```

为您的网站创建一个仓库：`<SITE_NAME>.github.io` *请注意：本教程使用的是 _用户/组织页面_ 而不是 _项目页面_(#link("https://help.github.com/en/articles/user-organization-and-project-pages")[reference])*，克隆它，并创建一个名为 `source` 的新分支（您喜欢的任何名称）：

```bash
git clone https://github.com/<USERNAME/ORGANIZATION>/<SITE_NAME>.github.io.git
cd <SITE_NAME>.github.io
git checkout -b source
```

将 Hugo 上述创建的文件夹中的所有内容复制到仓库中：

```bash
mv ../<SITE_NAME>/* .
```

访问 circleci.com 并添加您的项目。转到 `项目设置`，在 `SSH 权限` 下，添加您刚刚生成的 SSH 私钥 (#link("https://circleci.com/docs/2.0/add-ssh-key/")[reference])，复制 `指纹` 以供后用。

转到 Github 的项目设置，在 `部署密钥` 下，添加您刚刚生成的 SSH 公钥。

为 CircleCI 创建配置文件：

```bash
mkdir .circleci
cd .circleci
touch config.yml
```

`config.yml`（用您自己的信息编辑）：

```yaml
version: 2.0

jobs:
    build:
        docker:
            - image: felicianotech/docker-hugo:latest
        working_directory: ~/<SITE_NAME>.github.io
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "<FINGERPRINT_YOU_JUST_COPIED"
            - checkout
            - run:
                name: 获取当前网站
                working_directory: ~/
                command: git clone -b master git@github.com:<USERNAME/ORGANIZATION>/<SITE_NAME>.github.io.git public
            - run:
                name: 生成网站
                working_directory: ~/<SITE_NAME>.github.io
                command: HUGO_ENV=production hugo -d ~/public
            - deploy:
                name: 部署到 Github Pages
                working_directory: ~/public
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "<YOUR_EMAIL>"
                    git config user.name "Deployment Bot"
                    git add .
                    git commit --allow-empty -m "触发部署"
                    git push -q git@github.com:<USERNAME/ORGANIZATION>/<SITE_NAME>.github.io.git master

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: source
```

现在将您的文件推送到 Github：

```bash
git add .
git commit -m "第一次提交"
git push origin source
```

每次您推送到 `source` 分支时，CircleCI 将始终触发对 `master` 分支的 Hugo 生成，Hugo 生成的静态文件将放置在该分支中。

等待 CircleCI 的任务完成，然后访问 `<SITE_NAME>.github.io` 并享受吧！
