#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/en/life/2017/acg-wallpaper-recommendation-0.typ
// source_sha256: sha256:0ee679dac65aad7aa2dd107ee115c1003c401aabf8f9d12fc8758c5401fd02ac

#show: main.with(
  title: "ACG壁纸推荐(0)",
  desc: [ACG壁纸推荐(0)],
  date: "2017-07-31",
  tags: (

    blog-tags.misc,
  
  ),
  lang: "zh",
  i18nKey: "life/2017/acg-wallpaper-recommendation-0",
  sourceLang: "en",
  translationSourceHash: "sha256:0ee679dac65aad7aa2dd107ee115c1003c401aabf8f9d12fc8758c5401fd02ac",
  translationStatus: "machine",
)

本文推荐一幅ACG壁纸作品。

#link("https://www.pixiv.net/member_illust.php?mode=medium&illust_id=58991926")[君の名は。] by #link("https://www.pixiv.net/member.php?id=3014645")[Masabodo] on #link("https://www.pixiv.net/")[pixiv]
