#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/en/life/2017/ss-module-for-surge.typ
// source_sha256: sha256:210d6d8ac80d2468420d1fc394fc43eeee5e2504c399a1d0e5afce4e13ce38f4

#show: main.with(
  title: "Surge 的 Shadowsocks 模块",
  desc: [Surge 的 Shadowsocks 模块],
  date: "2017-04-23",
  tags: (

    blog-tags.life,
    blog-tags.network,
  
  ),
  lang: "zh",
  i18nKey: "life/2017/ss-module-for-surge",
  sourceLang: "en",
  translationSourceHash: "sha256:210d6d8ac80d2468420d1fc394fc43eeee5e2504c399a1d0e5afce4e13ce38f4",
  translationStatus: "machine",
)

只是一个用于 `Surge` 应用的 ss 模块。

#link(
  "https://github.com/dyzdyz010/SSModule/raw/master/ss.module",
  "https://github.com/dyzdyz010/SSModule/raw/master/ss.module",
)
