#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2023/ffmpeg-merge-video-and-subtitles.typ
// source_sha256: sha256:0b3237a711e58609f06fb664268fdef9bb570812ab7840749042679b26de4d03

#show: main.with(
  title: "Merging Video and Subtitles with FFmpeg",
  desc: [Some players cannot recognize external subtitles or embedded tracks, so the subtitle content needs to be 'burned' into the video.],
  date: "2023-10-24",
  tags: (

    blog-tags.ffmpeg,
    blog-tags.tooling,
  
  ),
  lang: "en",
  i18nKey: "tutorials/2023/ffmpeg-merge-video-and-subtitles",
  sourceLang: "zh",
  translationSourceHash: "sha256:0b3237a711e58609f06fb664268fdef9bb570812ab7840749042679b26de4d03",
  translationStatus: "machine",
)

Some players cannot recognize external subtitles or embedded tracks, so the subtitle content needs to be 'burned' into the video.

Command:

= Embedded Subtitles

```bash
ffmpeg -i input.mp4 -vf "subtitles=input.mp4" output.mp4
```

= External Subtitles

```bash
ffmpeg -i input.mp4 -vf "subtitles=input.srt" output.mp4
```
