#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221214-mmo-server-from-scratch(23)-visualize-server-icon-facing-fix.typ
// source_sha256: sha256:5b1fe80e36322c2e9ee57a5ef470f31b94228651573d2f3b16cfd7aa6cec7bfb

#show: main.with(
  title: "MMORPG Game Server from Scratch (23) - Visualize Server (6) - Fixing Character Icon Orientation Issues",
  desc: [In the last section, we displayed the player's character indicator icon in the correct position on the webpage, but the icon's direction did not update with the direction of movement.],
  date: "2022-12-14",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.tooling,
    blog-tags.frontend,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221214-mmo-server-from-scratch(23)-visualize-server-icon-facing-fix",
  sourceLang: "zh",
  translationSourceHash: "sha256:5b1fe80e36322c2e9ee57a5ef470f31b94228651573d2f3b16cfd7aa6cec7bfb",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

In the last section, we displayed the player's character indicator icon in the correct position on the webpage, but the icon's direction did not update with the direction of movement; it remained fixed in one direction, which looked quite bad. In this section, we will solve this problem.

= Basic Idea

The arrow of the indicator icon should actually point in the direction of the character's movement. When updating the icon's position, we actually have two positions:

- Current position of the icon
- Next position to which the icon will update

With this, we can derive a method to calculate the direction: *subtract the previous position from the latter position to get a displacement vector*, and the direction of this vector is the direction the icon should point.

= Implementation

In `PIXI.js`, the rotation of a sprite can only be specified in degrees or radians, and does not support direction vector specification. Therefore, we also need to convert the direction vector into degrees or radians.

The `atan2` function in `JS` can convert the vector coordinates into the angle in radians with respect to the positive direction of the `x` axis. At this point, we can use `sprite.rotation` to set its rotation angle in radians. If we want degrees, we just need to transform it:

d

e

g

r

e

e

s

=

r

a

d

i

a

n

s

∗

180

π

degrees = \\frac(radians \* 180, \\pi)

d

e

g

rees

=

π

r

a

d

ian

s

∗

180

​

Then we can set it using `sprite.angle`:

```javascript
function getAngle(x, y) {
    var angle = Math.atan2(y, x);   // radians
    var degrees = 180 \* angle / Math.PI;  // degrees

    return degrees
}
```

After setting this, I found that the direction of the icon's arrow was opposite to our movement direction. This is because the arrow icon I used points in the negative direction of the `x` axis:

#figure(image("/public/assets/img/2022/20221214-mmo-server-from-scratch(23)-visualize-server-icon-facing-fix-1.png"), caption: "Pasted image 20221214205305.png")

Therefore, we need to add 180°180\\degree180° to the angle. For radians, we add π\\piπ.

Now the direction is correct. However, when our character stops moving, the arrow's direction returns to the positive direction of the `x` axis, rather than remaining consistent with the character's last movement direction. This is because when stationary, the difference between the sprite's two coordinates is 0, resulting in an angle of 0°0\\degree0°.

To solve this problem, we just need to check that we only calculate the angle when movement occurs:

```javascript
const dx = character.location.x \* ratio - players[character.cid].position.x
const dy = character.location.y \* ratio - players[character.cid].position.y

if (dx != 0 || dy != 0) {
	// Moving, update angle
    let angle = getAngle(dx, dy)
    players[character.cid].angle = angle + 180
}
```

= Next Steps

At this point, `Visualize Server` comes to a temporary conclusion, and we can simply check the server-side character coordinate status. Next, I will continue to focus on the addition of the physics engine and the logic of collision detection.
