#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221220-mmo-server-from-scratch(28)-scene-server-update-nif-interfaces.typ
// source_sha256: sha256:8d6b9e196244175857c847538f91ca5cd6faddee4774b310a536a6c04b109694

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (28) - Scene Server (17) - Updates on Related NIF Interfaces",
  desc: [In the last section, we completed the creation of the physics system. In this section, we will begin modifying the NIF functions related to movement using the physics system. The basic idea is to involve the physics operations.],
  date: "2022-12-20",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221220-mmo-server-from-scratch(28)-scene-server-update-nif-interfaces",
  sourceLang: "zh",
  translationSourceHash: "sha256:8d6b9e196244175857c847538f91ca5cd6faddee4774b310a536a6c04b109694",
  translationStatus: "machine",
)

#quote(block: true)[
  This series code repository: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

In the last section, we completed the creation of the physics system. In this section, we will begin modifying the `NIF` functions related to movement using the physics system.

The basic idea is to add a reference to the `PhySys` object in functions that involve physical operations to obtain a globally unique object. In addition, there is another aspect worth emphasizing.

= Obtaining Debug Data

Before introducing the physics engine, all fields in the character data structure were of simple types, so we could directly use the types provided by `Rustler`, allowing `Rust` types to be passed to `Elixir` code and vice versa. *However*, after introducing physics engine-related types, those physics-related fields could not be passed by `Rustler`, hindering our ability to debug the `NIF` code. Therefore, my approach is to create a twin structure that removes the physics-related fields and uses only simple fields. Taking the movement component `Movement` as an example:

```rust
pub struct Movement {
    physics_component: PhysicsComp,
    // pub location: Vector,
    pub velocity: Vector,
    pub acceleration: Vector,
    pub timestamp: u64,
    pub is_in_air: bool,
}
```

As you can see, we replaced the `location` field with `physics_component`, as the position is determined by it. This structure cannot be passed to `Elixir` code, so we create another structure:

```rust
pub struct MovementDebug {
    pub location: Vector,
    pub velocity: Vector,
    pub acceleration: Vector,
    pub timestamp: u64,
    pub is_in_air: bool,
}
```

The other parts are the same, except that we replaced `physics_component` back with `location`. This structure is initialized with the original data from above:

```rust
pub fn new(movement: &Movement, physys: &PhySys) -> MovementDebug {
    MovementDebug {
        location: movement.get_location(&physys),
        velocity: movement.velocity,
        acceleration: movement.acceleration,
        timestamp: movement.timestamp,
        is_in_air: movement.is_in_air,
    }
}
```

Obtaining `location` is also straightforward, simply using the `get_location` method from the original data, requiring only a `PhySys` object to be passed.

In this way, when we need to view debug data, we can simply return an object of type `MovementDebug`. The character data type `CharacterData` follows the same principle.

= Next Steps

The replacement of the physics engine is currently on hold. In the next phase, I need to rethink the client execution process for movement synchronization. The current method relying on `NavMesh` has issues when crossing terrains, and I need to find another way while also synchronizing the jump action.
