#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221216-mmo-server-from-scratch(24)-scene-server-rapier-introduction.typ
// source_sha256: sha256:1e814d2eeece6f6f4da633179b1a9ba9c2aab9c73502dd41ed7801c4c085092d

#show: main.with(
  title: "MMORPG Game Server from Scratch (24) - Scene Server (13) - Introduction to the Physics Engine Rapier",
  desc: [Let's continue with the writing of the scene server `scene_server`. As mentioned before, I plan to add a physics engine for client data validation.],
  date: "2022-12-16",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221216-mmo-server-from-scratch(24)-scene-server-rapier-introduction",
  sourceLang: "zh",
  translationSourceHash: "sha256:1e814d2eeece6f6f4da633179b1a9ba9c2aab9c73502dd41ed7801c4c085092d",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

Let's continue with the writing of the scene server `scene_server`. As mentioned before, I plan to add a physics engine for client data validation, and today we will look at the selection of the physics engine.

= Selection

The first one I learned about was the famous `PhysX`, which is also built into `UE`, demonstrating its powerful capabilities. However, for our code, compute-intensive tasks are handled using the `Rust` language, so there is no need to introduce a set of `C++` code that would increase the complexity of the project. Therefore, the question becomes which physics engine written in `Rust` is better?

There is a small website: #link("https://arewegameyet.rs/ecosystem/physics/")[Physics | Are we game yet?], where you can see what achievements `Rust` has made in the field of physics engines:

#figure(image("/public/assets/img/2022/20221216-mmo-server-from-scratch(24)-scene-server-rapier-introduction-1.png"), caption: "Pasted image 20221216203224.png")

As we can see, there are already many existing physics engine libraries. But which one is more reliable?

Interestingly, `PhysX` also has a `Rust port`. Unfortunately, this project is not yet complete and is still under construction. I still hope to choose a library that is currently more complete.

From the perspective of download volume, version, and other parameters, `rapier3d` undoubtedly stands out, with download numbers twice that of the second place, indicating that it is widely used and has a certain guarantee of quality.

= Rapier 3D

== Performance

Let's take a closer look at `Rapier 3D`. Its official website has a link to `Benchmark` #link("https://rapier.rs/benchmarks/")[Rapier physics engine | Rapier], where you can see the performance comparison between several physics engines:

#figure(image("/public/assets/img/2022/20221216-mmo-server-from-scratch(24)-scene-server-rapier-introduction-2.png"), caption: "Pasted image 20221216204719.png")

From the performance comparison of capsules in the chart, we can see that the performance of `rapier3d` is comparable to that of `PhysX`. When the number of entities is small, `rapier3d` even slightly outperforms `PhysX`; as the number of entities increases, `rapier3d` is only about 3 milliseconds slower than `PhysX`.

== Features

`Rapier 3D` provides various commonly used features, such as physics simulation, collision detection, and scene queries. It also supports `CCD (Continuous Collision Detection)`, which helps detect high-speed objects and avoid the occurrence of the *tunneling effect*.

= Conclusion

In conclusion, `Rapier 3D` is a good choice. For our project, I plan to use it only to detect existing data, so physics simulation is unnecessary; we only need collision detection and scene queries. `Rapier 3D` also provides `SIMD` optimization and parallel optimized versions, making its operation more efficient.

= Next Steps

Next, I will gradually find ways to integrate `Rapier 3D` into our scene server to serve the character movement functionality.
