#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221219-mmo-server-from-scratch(27)-scene-server-physics-system-manager.typ
// source_sha256: sha256:e36e2c7183d951496a7cdbc2014b85a79715c657ee03637c256c74a0b91671ad

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (27) - Scene Server (16) - Creating the Physics System and Its Manager",
  desc: [The previous section mentioned the physics system object `PhySys`. In this section, we will implement `PhySys` and the management process on the Elixir side.],
  date: "2022-12-19",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221219-mmo-server-from-scratch(27)-scene-server-physics-system-manager",
  sourceLang: "zh",
  translationSourceHash: "sha256:e36e2c7183d951496a7cdbc2014b85a79715c657ee03637c256c74a0b91671ad",
  translationStatus: "machine",
)

#quote(block: true)[
  This series code repository: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

The previous section mentioned the physics system object `PhySys`. In this section, we will implement `PhySys` and the management process on the `Elixir` side.

= PhySys

This is a custom structure used to store global information for the physics engine, such as rigid body/collider collections, pipelines, and collision phases (Broad Phase, Narrow Phase).

Choosing what to store is not difficult; we just need to look at what parameters are required when the pipeline executes the step method. For our project, we currently only consider using the `Collision Pipeline`, so we look at what parameters it needs:

```rust
/// Executes one step of the collision detection.
pub fn step(
    &mut self,
    prediction_distance: Real,
    broad_phase: &mut BroadPhase,
    narrow_phase: &mut NarrowPhase,
    bodies: &mut RigidBodySet,
    colliders: &mut ColliderSet,
    hooks: &dyn PhysicsHooks,
    events: &dyn EventHandler,
)
```

Among these parameters, except for the last two event handling functions, the others are global information that needs to be stored. The `prediction_distance` is provided in a structure called `IntegrationParameters` in `Rapier`.

In addition, we also need to perform scene queries for ray tests and other operations.

Therefore, our `PhySys` structure is as follows:

```rust
pub struct PhySys {
    pub integration_params: IntegrationParameters,
    pub pipeline: CollisionPipeline,
    pub queries: QueryPipeline,
    pub rigid_body_set: RigidBodySet,
    pub collider_set: ColliderSet,
    pub broad_phase: BroadPhase,
    pub narrow_phase: NarrowPhase,
}
```

Next, we need to provide a `NIF` function interface to create this structure. The structure is divided into two parts: the `Rust` part and the `Elixir` part. The code is omitted; just write it according to `Rustler` requirements.

= PhysicsManager

We need to create a process in the `Elixir` supervision tree to hold a global `PhySys` object for various entities to call during the server program's lifecycle. This process currently only needs two functions:

1. Hold a reference to the `PhySys` object
2. Provide an interface to get the `PhySys` object

We call this process `PhysicsManager` and create a separate supervisor for it. The supervisor code is omitted; the key code for `PhysicsManager` is as follows:

```elixir
@impl true
def handle_continue(
      :load,
      state
    ) do
  # Get the reference to the PhySys object from the NIF function
  {:ok, physys_ref} = SceneServer.Native.SceneOps.new_physics_system()
  
  {:noreply, %{state | physys_ref: physys_ref}}

end

@impl true
def handle_call(:get_physics_system_ref, _from, %{physys_ref: physys_ref} = state) do
  # Get the reference to the PhySys object
  {:reply, {:ok, physys_ref}, state}
end
```

= PlayerCharacter

For convenience, we currently stipulate that each player character process holds a reference to a `PhySys` object, which is obtained and stored in the process state during its initialization:

```elixir
{:ok, physys_ref} = SceneServer.PhysicsManager.get_physics_system_ref()

{:noreply,
  %{
    state
    | physys_ref: physys_ref,
      aoi_ref: aoi_ref,
      character_data_ref: cd_ref,
      movement_timer: movement_timer
  }}
```

With this, the preparation work for the physics engine is complete.

= Next Steps

Migrate the character movement logic to the physics engine.
