#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221205-mmo-server-from-scratch(21)-visualize-server-character-coordinate-sync.typ
// source_sha256: sha256:d9d51455de606c1b9685d381ead98081ff59c142a3c404d553cfd83a8b4c58d6

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (21) - Visualize Server (4) - Get Player Character Coordinates and Send to Frontend",
  desc: [In the previous section, we obtained the player's character `cid` and process list. In this section, we will retrieve all coordinate data and send it to the frontend. Get Position.],
  date: "2022-12-05",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.rust,
    blog-tags.tooling,
    blog-tags.software,
    blog-tags.frontend,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221205-mmo-server-from-scratch(21)-visualize-server-character-coordinate-sync",
  sourceLang: "zh",
  translationSourceHash: "sha256:d9d51455de606c1b9685d381ead98081ff59c142a3c404d553cfd83a8b4c58d6",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

In the previous section, we obtained the player's character `cid` and process list. In this section, we will retrieve all coordinate data and send it to the frontend.

= Get Position

Now that we have the `pid` of each player character process, we just need to send a request to that process to get the location. The player character process provides an interface:

```elixir
@impl true
def handle_call(:get_location, _from, %{character_data_ref: cd_ref} = state) do
  {:ok, location} = SceneServer.Native.SceneOps.get_character_location(cd_ref)

  {:reply, {:ok, location}, state}
end
```

Here, the coordinates are obtained from the `NIF` space, as we have previously placed all the data of the player character into the `Rust` code.

After that, we sequentially request all player characters:

```elixir
# Get player character list
{:ok, players_map} =
  GenServer.call(
    {SceneServer.PlayerManager, :"scene1@127.0.0.1"},
    :get_all_players
  )

# Get coordinates
characters =
  Enum.map(players_map, fn {cid, pid} ->
    {:ok, {x, y, _z}} = GenServer.call(pid, :get_location)
    %{
      cid: cid,
      location: %{x: x, y: y}
    }
  end)
```

Here, the `location` should originally be a `Tuple`: `{x, y, z}`, but `Phoenix` cannot convert the `Tuple` type to a `Json` object, so we need to use pattern matching to convert it into a `Map`, i.e., `%{x: x, y: y}`. Currently, the `z` coordinate is not needed, so we will not pass the value of `z` to the frontend.

Thus, the data structure we need to send to the frontend is a list of `Maps`:

#figure(image("/public/assets/img/2022/20221205-mmo-server-from-scratch(21)-visualize-server-character-coordinate-sync-1.png"), caption: "Pasted image 20221205213427.png")

Then we can send it to the frontend.

= Frontend Display

In the frontend event listener function, we can extract the data and prepare to display it on the page.

Before that, we need to determine the update strategy. Initially, I thought about clearing the previous sprites on the page and recreating them every time the data is refreshed. However, after looking through the documentation, it seems that this operation is not natively supported, and it would also consume a lot of resources. So I came up with *the second strategy:* maintain a global dictionary indexed by `cid`, with the value being the sprite object in the scene. If it does not exist, create a new one; if it exists, modify its position. This way, the resource consumption is lower than the first method.

```javascript
var players = {}

window.addEventListener(`phx:data`, (e) => {
    const clist = e.detail.characters

    clist.forEach(character => {
        if (players[character.cid] == null) {
            let sprite = PIXI.Sprite.from('/images/arrow_64.png')
            scene.addChild(sprite)
            sprite.position.set(character.location.x, character.location.y)
            sprite.scale.set(0.5)
            players[character.cid] = sprite
        } else {
           players[character.cid].position.set(character.location.x, character.location.y)
        }
    })
})
```

Effect:

#figure(image("/public/assets/img/2022/20221205-mmo-server-from-scratch(21)-visualize-server-character-coordinate-sync-2.png"), caption: "Pasted image 20221205213956.png")

As we can see, the coordinates of the sprites are not correct. This is due to the inconsistency between the coordinate systems of `PIXI.js` and `UE`, as well as the scaling factor.

= Next Steps

The next section will focus on solving the issue of incorrect coordinate display.
