#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221201-mmo-server-from-scratch(17)-visualize-server-tailwind-phoenix.typ
// source_sha256: sha256:a04327b5c08c149bf9ed4bbd93b304f76d0afaa1f796f0bf880836e59790ab8c

#show: main.with(
  title: "MMORPG Game Server from Scratch (17) - Visualize Server (0) - Integrating Tailwind with Phoenix",
  desc: [In the last section, I mentioned that I wanted to make the server-side player movement data intuitive, and the Web was the first method that came to mind. So starting from this section, I will build a Web server based on the Phoenix framework to display data graphically on the webpage.],
  date: "2022-12-01",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.tooling,
    blog-tags.software,
    blog-tags.frontend,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221201-mmo-server-from-scratch(17)-visualize-server-tailwind-phoenix",
  sourceLang: "zh",
  translationSourceHash: "sha256:a04327b5c08c149bf9ed4bbd93b304f76d0afaa1f796f0bf880836e59790ab8c",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

#link("/en/article/mmo-server-from-scratch/2022/20221130-mmo-server-from-scratch(16)-scene-server-movement-error-notes")[In the last section] I mentioned that I wanted to make the server-side player movement data intuitive, and `Web` was the first method that came to mind. So starting from this section, I will build a Web server based on the `Phoenix` framework to display data graphically on the webpage.

Creating the project is simple:

```bash
mix phx.new visualize_server --no-ecto
```

This server does not require a database connection, so the `--no-ecto` parameter is provided. Next, I will focus on how to integrate the `CSS` framework `Tailwind` into the project.

#line(length: 100%)

#link("https://tailwindcss.com/")[Tailwind CSS] is a very useful `CSS` framework that implements various styles using a combination of `class` names, making it very convenient and flexible. In this project for visualizing the scene, I will use it as the `CSS` framework for the entire project.

= 1. Clean Up Old Styles

To prevent contamination between different `CSS` contents, it is best to remove the old styles before adding new ones. The `Phoenix` framework uses `ESBuild` as the `JS` bundler, and its default style `app.css` is imported into `app.js`:

```js
// We import the CSS which is extracted to its own file by esbuild.
// Remove this line if you add your own CSS build pipeline (e.g postcss).
import "../css/app.css"
```

Since we need to use `Tailwind` to bundle `CSS` separately, we need to comment out this line.

Next, let's take a look at the contents of `app.css`:

```css
/* This file is for your main application CSS */
@import "./phoenix.css";

/* Alerts and form errors used by phx.new */
.alert {
  padding: 15px;
  margin-bottom: 20px;
  border: 1px solid transparent;
  border-radius: 4px;
}
.alert-info {
  color: #31708f;
  background-color: #d9edf7;
  border-color: #bce8f1;
}
.alert-warning {
  color: #8a6d3b;
  background-color: #fcf8e3;
  border-color: #faebcc;
}
...
```

Here, a `phoenix.css` file is referenced, which contains some initialization styles provided by the project. Since we want to start from scratch, we can delete it. The subsequent styles like `.alert` are part of the framework's built-in message prompt mechanism, which displays a `banner` to show the results of operations like data creation, deletion, and modification. Since we want to start clean, let's leave nothing and make `app.css` an empty file.

= 2. Add Dependencies

There are two ways to add the `Tailwind` library to the project:

1. Add it directly in `JS` via `NPM`
2. Add it through `Elixir` dependencies

Using method *1*, subsequent monitoring, packaging, and other functions would require additional management, which is not friendly for someone like me who is a beginner.

Using method *2*, since the `Tailwind` `Hex package` can not only include library files but also introduce some commands, such as build control and monitoring file changes in the development environment, this is undoubtedly more convenient, so I choose method *2*.

Add the dependency in the project's `mix.exs` file:

```elixir
defp deps do
    [
      ...,
      {:tailwind, "~> 0.1", runtime: Mix.env() == :dev}
    ]

  end
```

In addition, we also need to ensure that our written `CSS` files are bundled together with `Tailwind` during the final packaging, so we add the following content in the `aliases` function:

```elixir
defp aliases do
  [
    setup: ["deps.get"],
    "assets.deploy": [
      # Add this line
      "tailwind default --minify",
      "esbuild default --minify", 
      "phx.digest"
    ]
  ]
end
```

Execute the following command to refresh the dependencies:

```bash
mix deps.get
```

= 3. Add Configuration

Configure `Tailwind` in `config/config.exs`:

```elixir
# Tailwind config
config :tailwind, version: "3.1.6", default: [
  args: ~w(
    --config=tailwind.config.js
    --input=css/app.css
    --output=../priv/static/assets/app.css
  ),
  cd: Path.expand("../assets", __DIR__)
]
```

Here, we specify the version of `Tailwind`, the configuration file, the input file, and the output file paths. `3.1.6` can be replaced with the latest version of `Tailwind`.

Since we specified the configuration file `tailwind.config.js`, let's create it:

```javascript
// See the Tailwind configuration guide for advanced usage
// https://tailwindcss.com/docs/configuration

module.exports = {
  mode: 'jit',
  content: [
    './js/**/*.js',
    '../lib/*_web.ex',
    '../lib/*_web/**/*.*ex'
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms')
  ]
}
```

Here we specify the places where `Tailwind class` names might be used, namely `JS` files, some `Elixir` files, and `.*ex` template files. If you have other places that will use `Tailwind`, add their paths as well.

We also want `Tailwind` to monitor changes to our files and recompile the modified parts so that we can see the effects in real-time. Add the following content in the `config/dev.exs` configuration file:

```elixir
config :visualize_server, VisualizeServerWeb.Endpoint,
  ...,
  watchers: [
    # Add the following line
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]},
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]
```

At this point, we have completed all configurations. You can freely add a `class` in the template and run it to see the webpage, but you will notice that there is no effect. This is because we have not yet included `Tailwind` in the `CSS` file.

= 4. Include Tailwind in CSS

Add the following content in `app.css`:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Now, when you check the webpage again, you will see that the previously added `class` styles are now effective:

#figure(image("/public/assets/img/2022/20221201-mmo-server-from-scratch(17)-visualize-server-tailwind-phoenix-1.png"), caption: "Pasted image 20221201165547.png")

At this point, the configuration work for `Tailwind` is complete, and you can freely utilize it in the future :-P

= Next Steps

Next, we will choose a suitable front-end `2D` rendering library and discuss the methods for data acquisition and pushing.
