#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221128-mmo-server-from-scratch(14)-scene-server-player-process-reorg-2.typ
// source_sha256: sha256:71cfeb95d2b9590aa983890f4182efc7e8fe678d80aee585c18cd0522c17ad87

#show: main.with(
  title: "MMORPG Game Server from Scratch (14) - Scene Server (11) - Character Process Reorganization (2)",
  desc: [In the previous section, I explained why I chose Rustler as part of the architecture. This section details how to move character movement calculations to Rust NIF.],
  date: "2022-11-28",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221128-mmo-server-from-scratch(14)-scene-server-player-process-reorg-2",
  sourceLang: "zh",
  translationSourceHash: "sha256:71cfeb95d2b9590aa983890f4182efc7e8fe678d80aee585c18cd0522c17ad87",
  translationStatus: "machine",
)

#quote(block: true)[
  This series code repository: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

In the previous section, I explained why I chose Rustler as part of the architecture. This section details how to move character movement calculations into `Rust NIF`.

In #link("/en/article/mmo-server-from-scratch/2022/20221126-mmo-server-from-scratch(12)-scene-server-player-process-reorg-1")[MMORPG Game Server from Scratch (12) - Scene Server (10) - Character Process Reorganization (1) - Juejin (juejin.cn)], I have already shown everyone how to execute timed tasks, and movement calculations are precisely a type of task that needs to be executed on a schedule.

= Execution Process

1. When the `PlayerCharacter` process is created, it also creates the timed task `movement_tick` and its own data in the `NIF` space.
2. The `movement_tick` is triggered, passing a reference to its own data into the `NIF` function for movement calculations.
3. The `NIF` function unpacks the data reference, updates the movement parameters, and returns the new position.
4. The `PlayerCharacter` receives the new position and notifies the `AoiItem` process to record and broadcast the new position.
5. The `AoiItem` receives the message, first updating the new position in the `CoordinateSystem`, and then broadcasting to other players within the current `AOI` range.

= Data Structure

Player character data exists in `Rust` in the form of a struct:

```rust
pub struct CharacterData {
    pub cid: u64,
    pub nickname: String,
    pub movement: Movement,
    pub dev_attrs: DevAttrs,
}
```

- cid - Player character ID
- nickname - Nickname, currently unused
- movement - Movement component, details below
- dev\_attrs - Growth attributes, currently unused

The movement component is also a struct, containing properties such as position, velocity, and acceleration, used to calculate the player character's position and state at a given moment:

```rust
pub struct Movement {
    pub location: Vector,
    pub velocity: Vector,
    pub acceleration: Vector,
    pub timestamp: u64,
    pub is_in_air: bool,
}
```

- location - Position
- velocity - Velocity
- acceleration - Acceleration, currently not used, uncertain if it will be used in the future
- timestamp - The time when the movement parameters take effect, generally updated when the movement state changes
- is\_in\_air - Used to determine whether the player character is in the air, to decide whether to apply gravity effects. Currently unused.

When the `PlayerCharacter` executes `movement_tick`, it is essentially updating the values of the `movement` component.

The data reference passed by `PlayerCharacter` to the `NIF` function is an object of type `ResourceArc`:

```rust
pub struct CharacterDataResource(Mutex<CharacterData>);
pub type CharacterDataArc = ResourceArc<CharacterDataResource>;
```

`ResourceArc` can wrap a resource into a reference form, allowing the same persistent data to be passed between `Elixir` and `Rust`, making it possible for the `Elixir` process to retain `NIF` space data.

At the same time, we can see that the resource type we pass is not the direct `CharacterData`, but one that is locked (Mutex). This is because the resource referenced by `ResourceArc` is by default *immutable*, and to make it mutable, the resource type must be wrapped in a `Mutex`. Additionally, this is also for cross-thread read-write safety considerations. Currently, the logic involving player character data is relatively simple, so it may not be apparent, but in the future, *thread safety* may become a necessary consideration.

= AoiItem Execution Logic

Previously, the `AoiItem` process was responsible for both movement calculations and `AOI` related tasks. After the restructuring, the logic related to movement calculations has been moved to the `PlayerCharacter` process, and the `AoiItem` process only needs to handle `AOI` related logic. We only need to add an interface to `AoiItem` for the `PlayerCharacter` to call after completing the movement calculation logic:

```elixir
@impl true
def handle_cast({:self_move, location}, %{cid: cid, subscribees: subscribees} = state) do
  broadcast_action_player_move(cid, location, subscribees)

  {:noreply, %{state | location: location}}
end
```
