#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221126-mmo-server-from-scratch(12)-scene-server-player-process-reorg-1.typ
// source_sha256: sha256:1f75fad1e57df7b1cda81738725069d76e5d787d93411d18e6ed2c2661c9b177

#show: main.with(
  title: "MMORPG Game Server from Scratch (12) - Scene Server (10) - Character Process Restructuring (1)",
  desc: [This section mainly discusses how to restructure character-related functionalities.],
  date: "2022-11-26",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221126-mmo-server-from-scratch(12)-scene-server-player-process-reorg-1",
  sourceLang: "zh",
  translationSourceHash: "sha256:1f75fad1e57df7b1cda81738725069d76e5d787d93411d18e6ed2c2661c9b177",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

This section mainly discusses how to restructure character-related functionalities.

= Character Attributes

Our characters possess various attributes that need to be called in real-time on the server, such as position, attack power, defense power, etc. The mathematical calculations for these attributes need to be as efficient as possible, so I plan to place them in `Rust NIF` to leverage `Rust`'s computational performance, as `Elixir` is relatively less efficient for such calculations.

In #link("/en/article/mmo-server-from-scratch/2022/20221016-mmo-server-from-scratch(5)-scene-server-aoi-supervision-tree\#heading-0")[MMORPG Game Server from Scratch (4) - Scene Server (2) - AOI - Supervision Tree - Juejin (juejin.cn)] we mentioned that data in `NIF` can exist as references in `Elixir`, so in the `Elixir` code, we only need to let the player character process hold a reference to various state data. After all, almost all calculations exist in the `NIF` space, so it doesn't matter if `Elixir` doesn't hold the actual data.

= Timed Tasks

In addition to saving data, the player character process also needs to periodically update some of its data, such as updating its position during uniform linear motion, buff calculations, etc. I also want to place these tasks in `NIF` to improve computational speed.

Since `NIF` does not handle concurrent programming well, the *timed* tasks still need to be handled by `Elixir` code. `Elixir` allows sending messages to processes at regular intervals, thus achieving timed tasks. The basic calling flow is as follows:

```mermaid
sequenceDiagram

participant P as PlayerCharacter
participant N as NIF Space

P ->> P: Process.send_after(self, 100ms, tick_function)

rect rgb(200, 150, 255)
note right of P: Tick function
P ->> P: tick_function()
activate P
P ->> N: TickFunction in NIF
activate N
N -->> P: Reply
deactivate N
deactivate P
end
```

Returning data from the timed function in `NIF` is necessary; for example, in position updates, the `Elixir` code needs to obtain the updated position for `AOI` broadcasting.

= Next Steps

The next step will detail the code structure in `NIF` and how to modify the already written movement synchronization code logic.
