#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221218-mmo-server-from-scratch(26)-scene-server-physics-component.typ
// source_sha256: sha256:c07978e6dfad8dcd573ef9426bedfa5be5799ca1070413628cb6cfb8bf8a6e08

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (26) - Scene Server (15) - Creating Character Physics Component",
  desc: [In this section, we will begin to modify the existing movement component. The current movement component stores the position directly as a field within a struct: but],
  date: "2022-12-18",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221218-mmo-server-from-scratch(26)-scene-server-physics-component",
  sourceLang: "zh",
  translationSourceHash: "sha256:c07978e6dfad8dcd573ef9426bedfa5be5799ca1070413628cb6cfb8bf8a6e08",
  translationStatus: "machine",
)

#quote(block: true)[
  This series code repository: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

In this section, we will begin to modify the existing movement component.

The current movement component stores the position directly as a field within a struct:

```rust
pub struct Movement {
    pub location: Vector,
    pub velocity: Vector,
    pub acceleration: Vector,
    pub timestamp: u64,
    pub is_in_air: bool,
}
```

However, since the next step is to use the physics component's position to represent the player's character position, this `location` field needs to be replaced. What should it be replaced with?

= Physics Movement Component PhysicsComp

We will create a new struct to exist as a field of the `Movement` component. This struct will hold class objects related to the `Rapier 3D` physics engine, such as the `Character Controller`:

```rust
pub struct PhysicsComp {
    character_controller: KinematicCharacterController,
    collider_handle: ColliderHandle,
}
```

Here we are only storing two things:

- `character_controller` - the character controller responsible for movement
- `collider_handle` - a handle for a collider, used to manipulate the collision events, position, etc., of the character's collider

Next, we will write an initialization function:

```rust
pub fn new(location: Vector, physys: &mut PhySys) -> PhysicsComp {
    let collider = ColliderBuilder::capsule_z(0.3, 0.15)
        .translation(Vector3::new(location.x, location.y, location.z))
        .build();
    let collider_handle = physys.collider_set.insert(collider);
    let character_controller = KinematicCharacterController::default();

    PhysicsComp {
        character_controller,
        collider_handle
    }
}
```

Here, we create a capsule-shaped collider in the `z` direction, assign a position, and add it to the collider set, storing the returned `handle` in the struct for future use.

We also need a position update function to update the collider's position:

```rust
pub fn controller_move(&mut self, translation: Vector, physys: &mut PhySys) -> Vector {
    let collider = &physys.collider_set[self.collider_handle];
    let desired_translation = Vector3::new(translation.x, translation.y, translation.z);

    let corrected_movement = self.character_controller.move_shape(
        physys.integration_params.dt,
        &physys.rigid_body_set,
        &physys.collider_set,
        &physys.queries,
        physys.collider_set[self.collider_handle].shape(),
        collider.position(),
        desired_translation,
		QueryFilter::default().exclude_collider(self.collider_handle),
        |_| {},
    );

    let collider = &mut physys.collider_set[self.collider_handle];
    collider.set_translation(collider.translation() + corrected_movement.translation);

    return self.get_location(&physys);
}
```

Here, we use the `Character Controller`'s `move_shape` to determine if the character's collider can move to the target coordinates, checking for any obstacles in the way. If there are none, it can smoothly move to the target position; if blocked, this function will return the position that can be reached in front of the obstacle, stopping at the edge of it. After obtaining the new target position, we simply update the collider's position.

Note the parameter `translation`, which is a translation parameter representing the distance moved, not the coordinates of the target position, as the `move_shape` function requires a movement distance vector.

In this function, we use a parameter of type `PhySys`, which is a pointer to the entire physics system. All operations we perform on physical entities need to be done on the data within this system.

Additionally, since the coordinate calculations used in the above function are in matrix form, which is not friendly for data transfer between `Rustler` and `Elixir`, we need to convert it into a more suitable data type, which is our own defined type `Vector`. We will write a function to achieve this:

```rust
pub fn get_location(&self, physys: &PhySys) -> Vector {
    let collider = &physys.collider_set[self.collider_handle];

    return Vector{x: collider.position().translation.x, y: collider.position().translation.y, z: collider.position().translation.z};

}
```

= Next Steps

Create the aforementioned `PhySys` type, and add a process and supervisor in the `Elixir` code to maintain related data, while integrating the physics component from this section into the existing `Movement` component.
