#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221204-mmo-server-from-scratch(20)-visualize-server-character-list.typ
// source_sha256: sha256:eb440eec21b7101b471a55340a94db23f4e501b2ae585b0c190f75140394dd4d

#show: main.with(
  title: "MMORPG Game Server from Scratch (20) - Visualize Server (3) - Get Player Character List",
  desc: [In this section, I will create an interface for SceneServer to provide data to VisualizeServer.],
  date: "2022-12-04",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.frontend,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221204-mmo-server-from-scratch(20)-visualize-server-character-list",
  sourceLang: "zh",
  translationSourceHash: "sha256:eb440eec21b7101b471a55340a94db23f4e501b2ae585b0c190f75140394dd4d",
  translationStatus: "machine",
)

#quote(block: true)[
  This series code repository: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

In this section, I will create an interface for `SceneServer` to provide data to `VisualizeServer`.

In `SceneServer`, each player character exists as a process, so there is no natural structure to uniformly store all character data. My plan is to create a new process called `PlayerManager` to store all player character processes and their corresponding `cid`. Whenever a character enters the scene, the gateway server sends a request to `PlayerManager`, which creates the character process and stores it in its state. Similarly, when a player disconnects, the character process first notifies `PlayerManager` to remove itself from the character process list before completing its destruction.

So the idea is formed. `PlayerManager` holds the index of all player characters, and we can get the complete list from here, then separately fetch specific data from each character process. We just need to add an interface to `PlayerManager`:

```elixir
@impl true
def handle_call(:get_all_players, _from, %{players: players} = state) do
  {:reply, {:ok, players}, state}
end
```

Very simple. Let's have `VisualizeServer` call it and see. First, run a few clients so that the server has data; otherwise, what we get will be empty. Then, call the interface in the `:data_update` message handler we created earlier:

```elixir
result =
      GenServer.call(
        {SceneServer.PlayerManager, :"scene1@127.0.0.1"},
        :get_all_players
      )
Logger.debug("Player retrieval result: #{inspect(result, pretty: true)}")
```

Here, `:"scene1@127.0.0.1"` is the *node name* of the scene server `SceneServer`. According to the `BEAM` node cluster requirements, for one node to access another, it must first know the *node name*, and secondly, its own node's `cookie` must match that of the node it wants to connect to.

#figure(image("/public/assets/img/2022/20221204-mmo-server-from-scratch(20)-visualize-server-character-list-1.png"), caption: "Pasted image 20221204203535.png")

It can be seen that the player character list has been perfectly retrieved, structured as a `Map`, with keys as `cid` and values as the corresponding character process `ID`, i.e., `pid`.

= Next Steps

Next, we will retrieve specific data based on the process list we have obtained and package the data to send to the frontend for display.
