#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20220610-mmo-server-from-scratch(1)-beacon-server.typ
// source_sha256: sha256:5ecc9db0e50aa98e8e95f83737431f3ea051705f7836e1108b5d50810a7864e4

#show: main.with(
  title: "MMO Server From Scratch(1) - Beacon Server",
  desc: [MMO Server From Scratch(1) - Beacon Server],
  date: "2022-10-15",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.server,
    blog-tags.game,
    blog-tags.elixir,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20220610-mmo-server-from-scratch(1)-beacon-server",
  sourceLang: "zh",
  translationSourceHash: "sha256:5ecc9db0e50aa98e8e95f83737431f3ea051705f7836e1108b5d50810a7864e4",
  translationStatus: "machine",
)

Today we will implement the first component of the server - *beacon_server*.

= Function Analysis

To establish an Elixir cluster, all Beam nodes need to know a fixed node to connect to at startup. After that, Beam will automatically complete the connections between nodes, which is the default `full connection` mode, where all nodes are connected to each other. I haven't deeply considered whether adjustments are necessary for this; we will see how it goes later 🤪

Therefore, to allow all nodes in the server cluster to connect to a fixed node at startup to form the cluster, this fixed node is the `beacon_server`.

What functionalities does `beacon_server` need? After some simple thought, it should at least have the following functionalities:

1. Accept connections from other nodes
2. Accept registration information from other nodes
3. Respond to requests from other nodes and return information about the requested nodes

There are two important concepts here: `Resource` and `Requirement`. `Resource` refers to the type of content of a node itself, which is the role it plays in the cluster. For example, the resource of a gateway server is the gateway (gate_server); `Requirement` refers to other nodes that a node needs. For instance, a gateway node needs a *gateway management node (gate_manager)* to register itself, and a data service node needs a *data contact node (data_contact)* to synchronize the database to itself.

When a node registers with the `beacon_server`, we hope it can provide its node name, resource, requirement, and other data to the `beacon_server`, making it easier for the `beacon_server` to return already registered nodes as requirements to other nodes when it receives registration from other nodes.

= Data Structure

I will use a `GenServer` thread to handle all the aforementioned tasks, utilizing the thread's `state` to store the information of the nodes. Currently, I have roughly defined the information storage format as follows:

```elixir
%{
  nodes: %{
    "node1@host": :online,
    "node2@host": :offline
  },
  requirements: [
    %{
      module: Module.Interface,
      name: [:requirement_name],
      node: :"node@host"
    }
  ],
  resources: [
    %{
      module: Module.Interface,
      name: :resource_name,
      node: :"node@host"
    }
  ]
}
```

I use a dictionary to store all information, divided into `nodes`, `requirements`, and `resources`.

`nodes` stores all connected nodes and their statuses, where `:online` indicates a normal connection, and `:offline` indicates a disconnection;

`requirements` stores the requirement information provided by each node during registration. It uses a list to store each item representing a node. Each item is a dictionary that stores module (module), name (name), and node (node) information. The `name` field is a list because some nodes may have more than one `requirement`. The `module` field is reserved for future use and is currently not utilized... The `node` field is essential for sending messages to the target node.

`resources` stores the resource information provided by each node during registration, with fields identical to `requirements`, except that the data type of the `name` field is no longer a list but an atom, as each node can only belong to one unique resource and cannot belong to more than one.

= Brief Implementation

== Create Project

This is the first implementation. Before we implement it, we first create an `umbrella` project to store all subsequent code:

```bash
mix new cluster --umbrella
```

Then create the `beacon_server` project for this section:

```bash
cd apps/
mix new beacon_server --sup
```

`--sup` is used to generate a supervision tree.

Once we have the project, we need to create a `GenServer` to serve as the communication interface for other nodes, which we will call `Beacon`.

== Functional Functions

Based on the previous considerations, we need the following functions:

- register(credentials, state) - Used to record the registered node information in `state` and return the new `state`.
- get_requirements(node, requirements, resources) - Used to return the requirements of registered nodes.

Below is the rough implementation of my code; of course, this will not be the final version, and there is still room for optimization in the future:

```elixir
@spec register({node(), module(), atom(), [atom()]}, map()) :: {:ok, map()}
defp register(
        {node, module, resource, requirement},
        state = %{nodes: connected_nodes, resources: resources, requirements: requirements}
      ) do
  Logger.debug("Register: #{node} | #{resource} | #{inspect(requirement)}")

  {:ok,
    %{
      state
      | nodes: add_node(node, connected_nodes),
        resources: add_resource(node, module, resource, resources),
        requirements:
          if requirement != [] do
            add_requirement(node, module, requirement, requirements)
          else
            requirements
          end
    }
  }
end

@spec get_requirements(node(), list(map()), list(map())) :: list(map())
defp get_requirements(node, requirements, resources) do
  req = find_requirements(node, requirements)
  offer = find_resources(req, resources)
  offer
end
```

I won't include the other private functions used in the above code; in short, it returns new data using the data in the thread's `state`.

In addition to these two necessary functions, I also want to add two functions to monitor the connectivity of nodes. These two functions are implemented through `handle_info`. First, we need to enable this feature when initializing the thread:

```elixir
:net_kernel.monitor_nodes(true)
```

Then implement two callbacks:

```elixir
# ========== Node monitoring ==========

@impl true
def handle_info({:nodeup, node}, state) do
  Logger.debug("Node connected: #{node}")

  {:noreply, state}
end

@impl true
def handle_info({:nodedown, node}, state = %{nodes: node_list}) do
  Logger.critical("Node disconnected: #{node}")

  {:noreply, %{state | nodes: %{node_list | node => :offline}}}
end
```

Not modifying the node status to `:online` in the `:nodeup` callback is because the registration function has already changed the node's status to `:online` during registration.

== Interface Functions

With functionalities in place, we also need to provide external interfaces. `GenServer` has already provided the relevant callback functions for us to implement. Here, I use `handle_call/3` because the registration process needs to be *synchronous*; only after registration is completed can the corresponding node start functioning normally.

Similarly, there are two external interfaces: `:register` and `:get_requirements`:

```elixir
@impl true
# Register node with resource and requirement.
def handle_call(
      {:register, credentials},
      _from,
      state
    ) do
  Logger.info("New register from #{inspect(credentials, pretty: true)}.")

  {:ok, new_state} = register(credentials, state)

  Logger.info("Register #{inspect(credentials, pretty: true)} complete.", ansi_color: :green)

  {:reply, :ok, new_state}
end

@impl true
# Reply to caller node with specified requirements
def handle_call(
      {:get_requirements, node},
      _from,
      state = %{nodes: _, resources: resources, requirements: requirements}
    ) do
  Logger.debug("Getting requirements for #{inspect(node)}")

  offer = get_requirements(node, requirements, resources)

  {:reply,
    case length(offer) do
      0 -> nil
      _ -> 
        Logger.info("Requirements retrieved: #{inspect(offer, pretty: true)}", ansi_color: :green)
        {:ok, offer}
    end, state}
end
```

At this point, the `Beacon` functionality module is basically complete. Finally, we need to add it to the supervision tree to make it run. In `application.ex`:

```elixir
def start(_type, _args) do
  children = [
    # Starts a worker by calling: BeaconServer.Worker.start_link(arg)
    {BeaconServer.Beacon, name: BeaconServer.Beacon}
  ]

  # See https://hexdocs.pm/elixir/Supervisor.html
  # for other strategies and supported options
  opts = [strategy: :one_for_one, name: BeaconServer.Supervisor]
  Supervisor.start_link(children, opts)
end
```

By adding the `Beacon` module to the supervisor's child thread list like this, the `beacon_server` is temporarily complete.

= Effect Testing

Let's run it and see:

```bash
iex --name beacon1@127.0.0.1 --cookie mmo -S mix
```

To allow other nodes to connect, the `name` and `cookie` must be set correctly.

I wrote some test code to call it and see:

#figure(image("/public/assets/img/2022/20220611_beacon_server_output.png"), caption: "Beacon Server Output")

Finally, let's take a look at what the `state` of the `Beacon` module looks like:

#figure(image("/public/assets/img/2022/20220611_beacon_state.png"), caption: "Beacon State")

That's it for now; we will continue to implement other servers based on this foundation.
