#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221129-mmo-server-from-scratch(15)-physics-engine-notes.typ
// source_sha256: sha256:42a9a58a75d11d91ea8b648e576a963da8feb592d0b4a3822907cce044f57ff9

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (15) - Thoughts on the Physics Engine",
  desc: [In the past few days, while migrating the movement calculation logic to NIF, I have been pondering a question: should we add a physics engine to the server?],
  date: "2022-11-29",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221129-mmo-server-from-scratch(15)-physics-engine-notes",
  sourceLang: "zh",
  translationSourceHash: "sha256:42a9a58a75d11d91ea8b648e576a963da8feb592d0b4a3822907cce044f57ff9",
  translationStatus: "machine",
)

#quote(block: true)[
  This series code repository: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

In the past few days, while migrating the movement calculation logic to `NIF`, I have been pondering a question: should we add a physics engine to the server?

The main considerations for adding a physics engine to the server are as follows.

= Movement Validation

The physics engine can not only perform physical simulations but also detect relationships between colliders, such as collision detection and raycasting. For *physical simulation* and *collision detection*, this is an excellent means to effectively prevent cheating by the client in terms of displacement. After the server receives movement-related packets from the client, it can simulate based on the authoritative data on the server according to the new state update. If the simulation result is inconsistent with the request, it can be considered that the client is cheating.

For *physical simulation*, although the accuracy is high, simulating all objects in the scene would consume a significant amount of computational resources due to the large number of objects, which is not cost-effective. Therefore, we can settle for *collision detection*, simplifying the motion process by discarding the parts that involve forces and only retaining simple constant acceleration or uniform motion, thus saving a considerable amount of overhead.

Of course, there are other options for validation. We can also use the *walkable area* of `NavMesh` to verify the player's position. However, the business scenarios I am considering involve not only checking if the player is wall-hacking but also verifying *projectile* objects, such as whether they are blocked or hit, which cannot be achieved through `NavMesh`. Hence, this leads to the following consideration.

= Hit Detection

My idea is to bring the players of this `MMORPG` as close as possible to the `ARPG` direction, using a non-locking or semi-locking method for combat. This requires us to perform hit-related calculations on the server.

For example, in melee skills, we need to determine if there are targets within the range of a sword swing to calculate damage; in the case of a ranged fireball skill, we launch a fireball in a direction, and as the fireball travels in a straight line, we need to check if it hits a target or if it gets blocked by objects in the scene, resulting in a miss. At this point, collision detection methods such as `Ray Casting` or `Shape Casting` are needed.

Although I could implement these detection algorithms myself, I am not confident in my abilities and fear that even if I implement them, the results may not be good. Moreover, I have always adhered to a principle—*never reinvent the wheel*—so I can directly utilize the physics engine to achieve this functionality.

= Requirement Allocation

In addition to *movement validation* and *hit detection*, the server also needs *pathfinding functionality*, which can be directly implemented using `NavMesh`, making it useful. If we discuss these concentrated requirements together, we do not have to be constrained by the idea that a certain function must be implemented by a specific technology; rather, we can use whichever implementation is more convenient and efficient. If there is no *pathfinding* requirement, then we have no need to introduce the concept of `NavMesh` at all, and implementing everything with the *physics engine* would be perfect. However, now that we see that `NavMesh` definitely exists and is used, we might reconsider the implementation method for *movement validation*. For `NavMesh`, the validation method is straightforward; we only need to check if the character's position falls within the *walkable area*, which involves very little computation. As for the *physics engine*, since I am not very familiar with its internal implementation, I am unsure about the size of its collision calculation load, but I blindly guess it should be less efficient than directly comparing with `NavMesh`. So, should we also consider using `NavMesh` for the functionality of *movement validation*?

*Consideration Plan:*

- Movement Validation: Physics Engine/NavMesh
- Hit Detection: Physics Engine
- Pathfinding: NavMesh
