#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221016-mmo-server-from-scratch(2)-gate-server.typ
// source_sha256: sha256:8a7a3555aef58f5f77074fb4b2a903192e5915f81f2f272f3dced01f83274bfc

#show: main.with(
  title: "MMO Server From Scratch(2) - Gate Server",
  desc: [MMO Server From Scratch(2) - Gate Server],
  date: "2022-10-17",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.server,
    blog-tags.game,
    blog-tags.elixir,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221016-mmo-server-from-scratch(2)-gate-server",
  sourceLang: "zh",
  translationSourceHash: "sha256:8a7a3555aef58f5f77074fb4b2a903192e5915f81f2f272f3dced01f83274bfc",
  translationStatus: "machine",
)

Today we implement the second component of the server - **gate_server**

= Function Analysis

According to the ideas in the [initial architecture design](/posts/mmo-server-from-scratch/2022/20220608-mmo-server-from-scratch(0)-introduction.md), the `gate_server` is a server used to accept user connections. Clients connect to the `gate_server` via **TCP Socket**, and the `gate_server` is responsible for forwarding messages sent by the client to the specified business-related servers and sending back messages generated by the servers to the client.

Therefore, based on the above description, the `gate_server` needs to have at least the following functions:

1. Connect to the `beacon_server`, register itself, and obtain other server resources it needs.
2. Listen on a TCP port and accept connections.
3. Accept client messages and forward them to other servers.
4. Send messages to clients.

In `Erlang/Elixir`, the use of processes is extremely cheap. The processes mentioned here are not system processes, but rather `Beam` virtual machine processes, which are user processes. Therefore, I plan to allocate a `GenServer` for each `Socket` connection from the client for message exchange and state preservation.

For the message protocol, I chose #link("https://github.com/protocolbuffers/protobuf")[Protobuf], so the `gate_server` also needs to have the capability to encode and decode messages.

= Brief Implementation

== Establishing the Project

First, create the `gate_server` project for this section:

```bash
cd apps/
mix new gate_server --sup
```

== Module Division

To achieve the above functions, several modules need to be divided: an `Interface` module responsible for cluster-related operations, such as registration, joining the cluster, obtaining other server nodes, etc.; a `TcpAcceptor` module responsible for listening to ports and accepting TCP connections; and a `TcpConnection` module responsible for communication with clients.

According to this design, the supervision tree of the `gate_server` application is as follows:

```text
                            application
                           /     |     \
                          /      |      \
                         /       |       \
           TcpAcceptorSup   InterfaceSup  TcpConnectionSup
                  |              |               |  
                  |              |               |  
                  |              |               |  
              Interface     TcpAcceptor   TcpConnection x N

```

Where:

- application - `gate_server` main program
- TcpAcceptorSup - `TCP` listener process supervisor
- InterfaceSup - `Interface` module supervisor
- TcpConnectionSup - `TcpConnection` module supervisor
- Interface - cluster interface module process
- TcpAcceptor - `Tcp` listener module process
- TcpConnection - user connection process

== Interface

I won't go into the creation of the supervisor process; you can find methods in various documents. Let's first implement the functionality of the `Interface`.

The initialization process of the `Interface` process:

1. Create `GenServer`
2. Connect to the given `beacon_server` node
3. After a successful connection, call the `register` interface of `beacon_server` to register itself
4. Request other nodes required by `beacon_server`

Due to the limitations of the previously implemented `beacon_server`, this process will be kept simple for now, and we will continue to optimize it later.

I do not perform the above actions in the `init` function; instead, I place the logic in the `timeout` message handler to allow the process to complete initialization quickly and start receiving messages. The code is as follows:

```elixir
@impl true
def init(_init_arg) do
    {:ok, %{auth_server: [], server_state: :waiting_requirements}, 0}
end

@impl true
def handle_info(:timeout, state) do
    send(self(), :establish_links)
    {:noreply, state}
end

@impl true
def handle_info(:establish_links, state) do
    Logger.info("===Starting #{Application.get_application(__MODULE__)} node initialization===", ansi_color: :blue)

    join_beacon()
    register_beacon()
    new_state = get_requirements(state)

    Logger.info("===Server initialization complete, server ready===", ansi_color: :blue)
    {:noreply, %{new_state | server_state: :ready}}
end
```

I won't show the three functions `join_beacon/0`, `register_beacon/0`, and `get_requirements/1`, but the basic required elements are `Node.connect/1` and `GenServer.call/3`.

Running effect:

#figure(image("/public/assets/img/2022/20221016_interface.png"), caption: "Interface running effect")

At this point, the `state` data of the `beacon_server` is:

#figure(image("/public/assets/img/2022/20221016_beacon_state.png"), caption: "beacon_server state content")

At this point, if you enter:

```elixir
Node.list
```

in `iex`, you can find that our `gate_server` has already established a connection with the `beacon_server`:

#figure(image("/public/assets/img/2022/20221016_node_list.png"), caption: "beacon_server state content")

== TcpAcceptor

`TcpAcceptor` is used to receive incoming `TCP` connections and is also a `GenServer`. The logic of this process is very simple; let's look at the code:

```elixir
defp listen(port) do
    {:ok, socket} = :gen_tcp.listen(port, [:binary, packet: 0, active: true, reuseaddr: true])

    Logger.debug("Accepting connections on port #{port}")
    loop_acceptor(socket)
end

defp loop_acceptor(socket) do
    {:ok, client} = :gen_tcp.accept(socket)

    {:ok, pid} =
        DynamicSupervisor.start_child(
        GateServer.TcpConnectionSup,
        {GateServer.TcpConnection, client}
        )

    :ok = :gen_tcp.controlling_process(client, pid)

    loop_acceptor(socket)
end
```

The `listen/1` function is used to listen on a specified port, and after success, it starts accepting incoming `TCP` connections; the `loop_acceptor/1` function is used to continuously accept `TCP` connections. Once a connection is accepted, it creates a `TcpConnection` process for it and hands over the control of the connection's `socket` to the newly created `TcpConnection` process. In `Elixir`, tail recursion can be optimized, so it does not occupy stack space indefinitely, allowing for recursive calls at the end of the function to achieve continuous acceptance of `TCP` connections.

== TcpConnection

This is the core functional module of this section, responsible for all communication with the client.

`TcpConnection` is also a `GenServer`, used to store some state and transmit `TCP` data. Its initialization function is as follows:

```elixir
@impl true
def init(socket) do
    Logger.debug("New client connected.")
    {:ok, %{socket: socket, status: :waiting_auth}}
end
```

As you can see, we store the `socket` information in the process's `state` for easy retrieval later. The `status` attribute here is temporarily set aside for future user authentication, which will not be discussed in this section.

Next is the core function of this process - the `TCP` message receiving function:

```elixir
@impl true
def handle_info({:tcp, _socket, data}, %{socket: socket} = state) do
    result = "You've typed: #{data}"
    send_data(senddata, socket)

    {:noreply, state}
end
```

Here, for testing convenience, I first write a simple **echo** function. `GenServer` also conveniently provides handling for changes in `TCP` connection status, requiring only the implementation of the following two functions:

```elixir
@impl true
def handle_info({:tcp_closed, _conn}, state) do
    Logger.error("Socket #{inspect(state.socket, pretty: true)} closed unexpectedly.")
    DynamicSupervisor.terminate_child(GateServer.TcpConnectionSup, self())

    {:stop, :normal, state}
end

@impl true
def handle_info({:tcp_error, _conn, err}, state) do
    Logger.error("Socket #{inspect(state.socket, pretty: true)} error: #{err}")
    DynamicSupervisor.terminate_child(GateServer.TcpConnectionSup, self())

    {:stop, :normal, state}
end
```

Here we can test the establishment of `TCP` connections and the functionality of sending and receiving messages. Assuming my `gate_server` runs on local port `29000`, we run `Telnet`:

```powershell
telnet 127.0.0.1 29000
```

to start communicating with the server. Test results:

#figure(image("/public/assets/img/2022/20221016_echo_test.png"), caption: "beacon_server state content")

= Next Steps

The `gate_server` is now at a pause, and a server capable of accepting `TCP` client connections and conducting high-concurrency communication is basically complete. Next, we will continue to implement message protocol-related content, introduce the `Protobuf` message library, and carry out message distribution, further improving the gateway server functionality. This part will be revisited after implementing the scene server `scene_server` in the next step, so stay tuned!
