#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221202-mmo-server-from-scratch(18)-visualize-server-pixijs-scene-setup.typ
// source_sha256: sha256:575d435c7913a2b414344925c076f9f2d13a9199c0ea8cb524231a13f9cd7136

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (18) - Visualize Server (1) - PIXI.js Scene Setup",
  desc: [This section begins to focus on front-end visualization implementation. Rendering Library I searched a lot of keywords like 2D, Web, engine, and found that PixiJS],
  date: "2022-12-02",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.ue5,
    blog-tags.tooling,
    blog-tags.software,
    blog-tags.frontend,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221202-mmo-server-from-scratch(18)-visualize-server-pixijs-scene-setup",
  sourceLang: "zh",
  translationSourceHash: "sha256:575d435c7913a2b414344925c076f9f2d13a9199c0ea8cb524231a13f9cd7136",
  translationStatus: "machine",
)

#quote(block: true)[
  This series code repository: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

This section begins to focus on front-end visualization implementation.

= Rendering Library

I searched a lot of keywords like `2D, Web, engine` and found that #link("https://pixijs.com/")[PixiJS] always appears at the top, so it’s the one. Although it is not a complete game engine, our requirement is simply to display data on the page without any advanced applications, so a pure renderer feels sufficient.

#quote(block: true)[
  If there are other needs later, we can talk about it 🙄
]

`PIXI.js` is a `Web` 2D renderer that can achieve basic scene element management, resource management, and other functions, supporting `WebGL/Canvas` rendering, with `WebGL` as the default.

*Warning*: After a day of searching and stumbling, I found that the documentation for this thing is not very good, some functions are vaguely explained, and many features are not mentioned at all. If you want to use it heavily, be prepared to wear out your search engine 🙃

= Scene Setup

For `PIXI.js`, its scene management is a tree structure, from the top-level *Container* to the bottom-level *Sprite*, where the upper layer contains the lower layer, thus forming the entire scene.

For our scene, for convenience, we are currently using the range shown in the image below:

#figure(image("/public/assets/img/2022/20221202-mmo-server-from-scratch(18)-visualize-server-pixijs-scene-setup-1.png"), caption: "scene.png")

This is actually a top view of the third-person template scene that comes with `UE5`. For simplicity, we are currently only displaying the `X, Y` two-dimensional coordinates.

*Step One*, is to add the top-level object `Application` of `PIXI` to the `DOM tree`, which is essentially a `canvas` tag. For convenience, I let it occupy the full screen (putting it under an adaptive child element would cause various size issues that I can't solve; I'm a newbie).

*Step Two*, is to create our scene container. This step is for easier management; later there may be multiple scenes combined together, so we can aggregate the elements of a single scene under the same container element for easier unified operations like moving and scaling.

*Step Three*, is to add a *Sprite* to the scene container as the scene background, which is the image above. In *PIXI.js*, a *Sprite* is essentially just loading an image, nothing special, just pay attention to the size.

At this point, the scene initialization process is complete. However, since I used `Phoenix Liveview`, there is a page loading issue that affects the loading of the `PIXI` scene. Therefore, the above code needs to be executed after the page has finished loading:

```javascript
window.addEventListener('phx:page-loading-stop', (info) => {
    makeScene()
    document.body.appendChild(app.view)

    app.renderer.backgroundColor = 0xbcbcbc;

    window.addEventListener('resize', resize);

    resize()

})
```

Here, `phx:page-loading-stop` represents that the page has finished loading. I let the page listen for the `resize` event to adjust the `PIXI` scene size when the window size changes.

= Scene Dragging

Clearly, the page size is sometimes not enough to display the entire scene, only part of it can be shown. We need to be able to drag the scene to view different areas. I implemented this feature by referring to the #link("https://pixijs.io/examples/#/events/dragging.js")[Dragging - PixiJS Examples] in the official documentation. Overall, there are no issues, but there is one thing that I find quite annoying: no matter where the mouse is pressed, once dragging starts, it always uses the top-left corner of the dragged element as the drag point, because the origin of the `PIXI` coordinate system is by default the top-left corner.

I want the effect that when I drag from where I press, it directly uses that point as the drag point, rather than jumping to the top-left corner and following the drag, so I need to make some small modifications to the example in the link.

```javascript
function onDragStart(event) {
    this.alpha = 0.7
    dragTarget = this

    // Store the global coordinates of the click point when dragging starts
    dragTarget.offCoord = event.global.clone()

    app.stage.on('pointermove', onDragMove)
}

function onDragMove(event) {

    if (dragTarget) {
        let movement = new PIXI.Point()

	// Calculate the drag displacement
        movement.x = event.global.x - dragTarget.offCoord.x
        movement.y = event.global.y - dragTarget.offCoord.y

	// Update the position of the dragged element
        dragTarget.position.x += movement.x
        dragTarget.position.y += movement.y

	// Record the new global coordinates of the drag point
        dragTarget.offCoord = event.global.clone()
    }
}
```

I won't paste the callback function code for the end of the drag; there’s nothing particularly noteworthy.

This way, we just need to let our scene container listen for the mouse down event:

```javascript
scene.on('pointerdown', onDragStart, scene)
```

We can drag our scene container, and the contents inside will move along with it.

= Next Steps

Next, we will display the *Sprite* object representing the player character while looking for a way to implement server-timed data pushing.
