#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221125-mmo-server-from-scratch(11)-scene-server-player-process-reorg-0.typ
// source_sha256: sha256:c786179d4890fd602f0de999c022f402faf99be1017fee86fb978dc2d151407c

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (11) - Scene Server (9) - Character Process Reorganization (0)",
  desc: [This article mainly discusses the data storage and logical structure adjustments related to the PlayerCharacter process. In the previous article \[\[📄Starting from Zero: MMORPG Game Server (9) - Scene Server (7) - Movement Sync (3) - Player Movement - Server Part - Juejin (juejin.cn)\]],
  date: "2022-11-25",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221125-mmo-server-from-scratch(11)-scene-server-player-process-reorg-0",
  sourceLang: "zh",
  translationSourceHash: "sha256:c786179d4890fd602f0de999c022f402faf99be1017fee86fb978dc2d151407c",
  translationStatus: "machine",
)

#quote(block: true)[
  This series code repository: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

This article mainly discusses the data storage and logical structure adjustments related to the `PlayerCharacter` process. In the previous article #link("/article/mmo-server-from-scratch/2022/20221123-mmo-server-from-scratch(9)-scene-server-movement-sync-3-player-movement-server")[Starting from Zero: MMORPG Game Server (9) - Scene Server (7) - Movement Sync (3) - Player Movement - Server Part - Juejin (juejin.cn)], I mentioned that the current code structure of `PlayerCharacter` and `AoiItem` is not very clear, with unclear responsibilities, which is not conducive to subsequent development. Therefore, I rethought the responsibilities of the processes, the storage locations of the data, and which process should execute certain logic.

= Process Responsibility Allocation

At the beginning of the design, my original idea was to fully utilize the advantages of `Elixir`'s multithreading by assigning different functions of a player character to different processes, such as `Movement` responsible for movement, `Combat` responsible for combat-related logic, etc. However, as I wrote the code, I gradually felt that this approach was a waste of computational resources: *First*, there is interdependence between different types of attributes of the player character; for example, when a player casts a displacement skill, it changes the player's movement state, which increases the inherent message sending and receiving traffic between different processes; *Second*, inter-process communication has costs, such as latency and CPU time, which do not meet the basic design requirements of a game server. Too many processes can lead to resource waste caused by inter-process communication; *Third*, the original intention of introducing multiple processes was to allow different functional logics to run in parallel to improve efficiency, but in this case, most logics are _serial_, making multithreading feel counterproductive. Of course, there are some logics that can run in parallel, but they can be alternated through scheduled tasks without interference, which can save the cost of cross-process communication, and I currently feel this is worthwhile.

After the above considerations, I decided to allocate the roles of the player character-related processes as follows:

1. `PlayerCharacter` is responsible for its entire data storage (including attributes, movement, status, combat-related, etc.) and uses `scheduled tasks` and `Rust NIF` for calculations related to movement and combat, updating its own attributes;
2. The `AoiItem` process is only responsible for regularly obtaining nearby players and broadcasting messages to them. The broadcast messages are mainly triggered by the `PlayerCharacter` process, with a few other situations such as channel chat also able to trigger it.

= PlayerCharacter Process Layout Design

According to the current plan, `PlayerCharacter` needs to store the following information:

1. Movement - Movement-related data, such as position, speed, direction, etc.
2. Attrs - Attributes, including growth attributes and panel attributes
3. Equipments - Equipment list
4. BattleOps - Combat-related data, such as available skill list, current status, targets, etc.
5. Bag - Bag data

The logic that needs to be calculated regularly mainly includes the following two types:

1. Movement, which requires frequent calculation of player coordinates
2. Combat, which requires real-time calculation of various damages and effects

As shown in the figure below:

#figure(image("/public/assets/img/2022/20221125-mmo-server-from-scratch(11)-scene-server-player-process-reorg-0-1.png"), caption: "Drawing 2022-11-12 21.59.01.excalidraw.png")

All the above data and logic are placed in `NIF`, implemented using `Rust`, to improve operational efficiency.

= Next Steps

In the next article, I will gradually implement the above content while not affecting the already implemented movement synchronization effect.
