#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221203-mmo-server-from-scratch(19)-visualize-server-push-mechanism.typ
// source_sha256: sha256:d2464ba40c72b915c5eaca3365f3a8cc9075039853e8731014a380537a9c97b5

#show: main.with(
  title: "MMORPG Game Server from Scratch (19) - Visualize Server (2) - Server Data Push Mechanism",
  desc: [In this section, we explore how data is periodically pushed from the server to the client. For Phoenix Liveview,],
  date: "2022-12-03",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.software,
    blog-tags.frontend,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221203-mmo-server-from-scratch(19)-visualize-server-push-mechanism",
  sourceLang: "zh",
  translationSourceHash: "sha256:d2464ba40c72b915c5eaca3365f3a8cc9075039853e8731014a380537a9c97b5",
  translationStatus: "machine",
)

#quote(block: true)[
  This series code repository: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

In this section, we explore how data is periodically pushed from the server to the client.

For `Phoenix Liveview`, since the front-end and back-end are already connected via `WebSocket` by the framework mechanism, the communication back and forth becomes very convenient; we just need to send and receive messages through `WebSocket`, without needing to make requests like `AJAX` to fetch information.

= Server

The server of `Phoenix Liveview` can actively send events to the front-end, meaning it can send custom data.

Reference link: #link("https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html\#push_event/3")[Phoenix.LiveView — Phoenix LiveView v0.18.3 (hexdocs.pm)]

There is a function called `push_event/3`, which can send an event to the front-end via `socket`, along with a segment of `json` data associated with the event.

Since the server can actively push data to the front-end, we just need to have the server periodically fetch the latest data and then push it to the front-end using the `push_event` function, which the front-end can parse and display.

We also need to turn this action of sending events into a scheduled task, exactly like the way scheduled tasks are created in `SceneServer`:

```elixir
@impl true
def mount(_params, _session, socket) do
  # Create a scheduled task
  if connected?(socket), do: Process.send_after(self(), :data_update, 1000)

  {:ok, assign(socket, :data, [])}
end
```

This means sending a `:data_update` message to its own process after 1 second. You can see that I checked whether the `socket` is connected; the reason is that the `mount/3` function will #link("https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html\#c:mount/3")[be called twice] during the initialization process of the same page, and we do not want two identical scheduled tasks to exist simultaneously.

Our data processing and sending will take place in this `:data_update` message handling function:

```elixir
@impl true
def handle_info(:data_update, socket) do
  Process.send_after(self(), :data_update, 1000)

  {:noreply, push_event(socket, "data", %{
    characters: [%{
      cid: 1101,
      location: %{x: 5.0, y: 10.0}
    }]
  })}
end
```

Here, I just send a sample data to test. You can see that I called the scheduled task creation function `Process.send_after/3` again in the handling function `handle_info/2`; the reason is that the scheduled task created by this function is one-time only. To make it execute continuously, we need to create another identical scheduled task every time the scheduled task is triggered.

In this way, the server can periodically send data to the front-end.

= Front-end

Our message transmission mechanism follows a `publish-subscribe` model, where the server publishes events and the client subscribes to events. Therefore, we now need to subscribe to the `data` event on the client side.

Reference link: #link("https://hexdocs.pm/phoenix_live_view/js-interop.html\#event-listeners")[JavaScript interoperability — Phoenix LiveView v0.18.3 (hexdocs.pm)]

We subscribe to the `data` event in our front-end `js` file according to the documentation, so we can receive the data pushed from the server:

```javascript
window.addEventListener(`phx:data`, (e) => {
    console.log("Custom event:", e)
})
```

Let's check the output on the front-end:

#figure(image("/public/assets/img/2022/20221203-mmo-server-from-scratch(19)-visualize-server-push-mechanism-1.png"), caption: "Pasted image 20221203215416.png")

You can see that our data is under the `detail` field.

At this point, our data exchange process between the front-end and back-end is complete 🥳

= Next Steps

Next, I will add an interface for `SceneServer` to allow `VisualizeServer` to obtain player character movement data.
