#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221016-mmo-server-from-scratch(5)-scene-server-aoi-supervision-tree.typ
// source_sha256: sha256:9cd54a94b45b60874e403eba00004e53142a2f7f1e69b5827b1cee0f55a01686

#show: main.with(
  title: "MMO Server From Scratch(5) - Scene Server(2) - AOI - Supervision Tree",
  desc: [Today, we will determine the Elixir interface part of NIF and the structure of the corresponding supervision tree.],
  date: "2022-10-22",
  tags: (

    blog-tags.game,
    blog-tags.mmo,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221016-mmo-server-from-scratch(5)-scene-server-aoi-supervision-tree",
  sourceLang: "zh",
  translationSourceHash: "sha256:9cd54a94b45b60874e403eba00004e53142a2f7f1e69b5827b1cee0f55a01686",
  translationStatus: "machine",
)

Today, we will determine the `NIF` part of the `Elixir` interface and the structure of the corresponding supervision tree.

= NIF - Elixir Part

In the previous article, I briefly implemented the `Rust` part of the coordinate management system `coordinate_system`. In addition, we need its other half, the `Elixir` interface.

This process is quite simple. The `mix rustler.new` command generates `Rust` code and writes a template in the `README.md` file:

```elixir
defmodule SceneServer.Native.SortedSet do
  use Rustler, otp_app: :scene_server, crate: "coordinate_system"

  # When your NIF is loaded, it will override this function.
  def add(_a, _b), do: :erlang.nif_error(:nif_not_loaded)
end
```

As you can see, I only need to create a new `.ex` file and write the corresponding module name and function prototypes as in `Rust`. There are two places that need to correspond with the `Rust` code:

+ The `crate:` parameter needs to match the `package name` in the `Cargo.toml` file.
+ The `defmodule module name` needs to match the parameter in the `rustler::init!` function call in `lib.rs`.

After creating it, I need to add the interfaces from the `Rust` code one by one, for example:

```elixir
@spec new_system(integer(), integer()) :: {atom(), Types.coordinate_system()}
def new_system(_set_capacity, _bucket_capacity), do: error()

@spec add_item_to_system(Types.coordinate_system(), integer(), {number(), number(), number()}) :: {:ok, Types.item()} | {:err, atom()}
def add_item_to_system(_system, _cid, _coord), do: error()

@spec remove_item_from_system(Types.coordinate_system(), Types.item()) :: {:ok, {integer(), integer(), integer()}} | {:err, atom()}
def remove_item_from_system(_system, _item), do: error()

@spec update_item_from_system(Types.coordinate_system(), Types.item(), tuple()) :: {{integer(), integer(), integer()}, atom()}
def update_item_from_system(_system, _item, _new_position), do: error()

defp error, do: :erlang.nif_error(:nif_not_loaded)
```

As you can see, some of the interface type specifications `@spec` I wrote have unreasonable return values, but currently, it is not a big issue.

Sharp-eyed friends may have also noticed the two types `Types.item()` and `Types.coordinate_system()`, which are custom types:

```elixir
defmodule SceneServer.Native.CoordinateSystem.Types do
  @type item :: reference()
  @type coordinate_system :: reference()
end
```

Here, the `reference()` type is used, which is quite interesting. Referring to the code mentioned in the previous article #link("https://github.com/discord/sorted_set_nif")[Discord code], I copied this code because the `Elixir` side wants to keep only the *reference* to the corresponding resource, rather than the content itself, so that the content only exists in the `NIF` space, avoiding resource waste and efficiency reduction caused by copying and passing content back and forth.

At this point, the `NIF` part of the coordinate system is basically complete and can be called as a complete module by other modules.

= AOI Process Structure Design

Initially, the idea was to have `AOI` exist as a single process that accepts requests from all `PlayerCharacter` processes and returns relevant data. However, this would lead to a large number of `PlayerCharacter` processes sending messages to a single process, inevitably causing *message congestion*, resulting in some players having to wait a long time to receive return data, greatly affecting the player experience.

Therefore, I came up with another method: creating an `AoiItem` process for each player, which only holds the `AOI` information related to the current player. At the same time, the `Aoi` module maintains a mapping from `user ID` to `AOI process ID`, making it easier to send `AOI` messages to other players.

In this way, the user logic and the `AOI` related logic are decoupled to a certain extent. The `AoiItem` focuses only on updating its own `interest list` and `sending and receiving broadcast messages`, while the player process only needs to notify its own `AoiItem` process to perform various operations. Sending a message does not affect the logic in its own process from being blocked by `AOI` related operations.

As a result, the entire supervision tree of the `scene_server` currently looks like this:

```
SceneServer
├── InterfaceSup
│   └── Interface
├── PlayerSup
│   ├── PlayerManager
│   └── PlayerCharacterSup
│       └── PlayerCharacter (1:N)
└── AoiSup
    ├── AoiManager
    └── AoiItemSup
        └── AoiItem (1:N)

PlayerCharacter -.-> AoiItem
```

Where:

+ AoiManager - The module responsible for maintaining the mapping from `user ID` to `AOI process ID`.
+ AoiItem - The individual player `AOI` process corresponding to `PlayerCharacter`, held by `PlayerCharacter`.

== Current Considerations

The attributes that the `AoiItem` process should have, in addition to `user ID` and `player process ID`, should it also hold the `gateway connection process ID`? If `AoiItem` needs to send updates about surrounding players to the client, should it go through the `player process` or be sent directly to the `gateway connection process`? I haven't figured this out yet. If sent directly to the gateway, would holding the `gateway connection process ID` cause data consistency issues? Currently, it is unknown.

= Next Steps

The next step is to analyze and implement the initialization process of the `AOI` process tree, while preparing to add the client and `Proto` protocol for testing.
