#import "/templates/blog.typ": *
#import "/templates/enums.typ": *
#import "/templates/mod.typ": code-image
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221016-mmo-server-from-scratch(3)-scene-server-intro.typ
// source_sha256: sha256:ab896638f8fca6fd7e181bf3c97a412bcf976ec0946a94a48ec6c2b2665ad803

#show: main.with(
  title: "MMO Server From Scratch(3) - Scene Server(0) - Overview",
  desc: [MMO Server From Scratch(3) - Scene Server(0) - Overview],
  date: "2022-10-19",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.server,
    blog-tags.game,
    blog-tags.elixir,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221016-mmo-server-from-scratch(3)-scene-server-intro",
  sourceLang: "zh",
  translationSourceHash: "sha256:ab896638f8fca6fd7e181bf3c97a412bcf976ec0946a94a48ec6c2b2665ad803",
  translationStatus: "machine",
)

Today we start implementing the third component of the server - *scene_server*, which is the scene server. This section focuses only on the content that will be simply implemented in the near future, rather than a complete scene server. The scene server contains a lot of content, and we will implement it step by step.

= Function Analysis

The scene server `scene_server` is used to provide scene services for players, meaning that everything related to the scene after players enter the map is provided by the scene server, such as movement synchronization, updates on surrounding players' statuses, combat settlements, player behavior validation, etc.

Messages from `scene_server` can come from various other servers, such as the gateway server `gate_server`, world server `world_server`, user agent server `agent_server`, etc. However, if we consider all the functional points at once, I fear it will be overwhelming, so for now, let's focus on the most basic function of the scene server: *movement synchronization*.

Of course, we cannot neglect the most fundamental function: `players entering/leaving the scene`

== Movement Synchronization

What is movement synchronization? Simply put, in multiplayer games, you need to see other players around you, whether they are teammates or enemies, and you want to be able to see various actions of other players nearby; the position and movement of characters are also one of these actions. To achieve this effect, when your character is moving, you need to send your movement information to all nearby players so that they can update your character's performance on their clients, ensuring that what they see is *consistent* with what you see.

This involves two conditions:

1. Sending your information to multiple other players
2. The target of the information sent is within a certain range around yourself

That is: search for players around you among all players and broadcast your movement message to them. This function has a specific term called `AOI (Area Of Interest)`. As the name suggests, each player has their own area of interest, and only events occurring within this range will be communicated to the client, while events outside this range will be ignored (though it’s not always so absolute).

Therefore, to achieve the visibility of other players' movements in the game, we need to implement an `AOI` system. After some research, there are currently three main ways to implement `AOI`:

1. Lighthouse
2. Grid
3. Cross-linked list

You can search for these three methods on your own. Here, I have chosen the `cross-linked list` for a rough initial implementation, which also allows me to understand the related concepts.

== Players Entering/Leaving the Scene

There are multiple scenarios for players entering or leaving the scene. Currently, I can think of the following:

1. Players entering/leaving the game
2. Players moving to other scene servers
3. Players leaving/entering the open world due to certain gameplay mechanics (like dungeons, teleportation, etc.)

For now, to simplify, we will only consider the first scenario, and the other two will be implemented after the code is refined later.

= Brief Design

== Computational Planning

As the scene management server, `scene_server` integrates multiple functions, most of which are computation-intensive. While `Elixir` may excel in concurrency, it falls short in mathematical computations compared to languages like `C/C++`. Fortunately, `Elixir`, like `Erlang`, allows communication with external programs in various ways:

1. C Node
2. NIF
3. Port Driver
4. Port

Each method has different characteristics and suitable environments. In this project, we need significant computational power and relatively low latency, and among the four methods mentioned, `NIF` has the lowest message passing latency. Additionally, there is a fantastic `NIF` library that makes the development process of `NIF` more efficient and robust - `Rustler`. This library uses `Rust` as the development language for `NIF` functions, combining memory safety and efficiency, making it a perfect choice.

Therefore, we will delegate heavy computational tasks to `Rust`, such as `AOI` data management and various validation calculations, while the concurrent message passing will be handled by `Elixir`, such as player interactions and message broadcasting.

== Initial Supervision Tree

To keep the initial code as simple as possible, the early functional planning currently includes the following parts:

1. Player process module `PlayerCharacter`, where each player is a process, and player interactions are implemented through inter-process message passing.
2. Player management module `PlayerManager`, used to manage the mapping between player `ID` and processes, facilitating other processes to query and send messages to target player processes.
3. `AOI` management module `Aoi`, used to communicate with `NIF` and manipulate the `AOI` data structure (cross-linked list).
4. Cluster operation module `Interface`, similar to other servers.

The supervision tree structure is roughly as follows:

#figure(
  code-image.with(class: "center")(theme => [
    #set text(font: "DejaVu Sans Mono", size: 12pt)
    #let nodebox = (position, text, fill) => node(position, text, fill: fill, inset: 8pt)
    #let edge-box(body) = box(fill: rgb("#10aec2"), inset: 4pt, text(white, body))
    // #set page(width: auto, height: auto, margin: 5mm, fill: white)
    #let node-text = text.with(white)
    #let colors = (green.darken(20%), eastern, blue.lighten(20%))
    #let edge = edge.with(stroke: theme.main-color)

    #diagram(
      edge-stroke: 1pt,
      node-corner-radius: 5pt,
      edge-corner-radius: 8pt,
      mark-scale: 100%,

      nodebox((1, 0), node-text[Application], colors.at(0)),

      nodebox((0, 1), node-text[InterfaceSup], colors.at(1)),
      nodebox((1, 1), node-text[PlayerManagerSup], colors.at(1)),
      nodebox((2, 1), node-text[PlayerCharacterSup], colors.at(1)),

      nodebox((0, 2), node-text[Interface], colors.at(2)),
      nodebox((1, 2), node-text[PlayerManager], colors.at(2)),
      nodebox((2, 2), node-text[PlayerCharacter], colors.at(2)),
      // node((2, 0), align(center)[arithmetic & logic \ unit (ALU)], fill: colors.at(1)),
      // node((2, -1), [control unit (CU)], fill: colors.at(1)),
      // node((4, 0), [output], fill: colors.at(2), shape: fletcher.shapes.hexagon),

      edge((1, 0), (0, 1), "-}>"),
      edge((1, 0), (1, 1), "-}>"),
      edge(
        (1, 0),
        (2, 1),
        "-}>",
      ),

      edge((0, 1), (0, 2), "-}>"),
      edge((1, 1), (1, 2), "-}>"),

      edge(
        (2, 1),
        (2, 2),
        "-}>",
        label: edge-box[1:N],
        label-anchor: "center",
        // label-angle: -10deg,
      ),
    )
  ]),
  caption: "Scene Server Supervision Tree",
)

Where:

- application - `scene_server` main program
- InterfaceSup - `Interface` module supervisor process
- AoiSup - `AOI` management module supervisor process
- PlayerManagerSup - player management `PlayerManager` module supervisor process
- PlayerCharacterSup - player process `PlayerCharacter` module supervisor process
- Aoi - `AOI` management module process
- PlayerManager - player management module process
- PlayerCharacter - player process

= Upcoming Work

The initial extremely simple `scene_server` is planned to stop here, and more features will be added in the future. The next article will focus on implementing the `NIF` part of `Aoi`, written in `Rust`. Stay tuned.
