#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221127-mmo-server-from-scratch(13)-rustler-introduction.typ
// source_sha256: sha256:1426558bed39500f8f5155a74d1803894e5b6a8fd0ee2c8af0e5b4294ffa6582

#show: main.with(
  title: "Starting from Scratch: MMORPG Game Server (13) - Introduction to Rustler",
  desc: [Rustler is a library for writing Erlang NIF functions in the Rust language.],
  date: "2022-11-27",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221127-mmo-server-from-scratch(13)-rustler-introduction",
  sourceLang: "zh",
  translationSourceHash: "sha256:1426558bed39500f8f5155a74d1803894e5b6a8fd0ee2c8af0e5b4294ffa6582",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

#link("https://github.com/rusterlium/rustler")[Rustler] is a library for writing `Erlang NIF` functions in the `Rust` language.

`NIF (Native Implemented Function)` refers to a type of function implemented natively in languages like C. These functions are loaded and called by the `Erlang` virtual machine as dynamic link libraries, achieving the execution speed of native code. `NIF` does not involve context switching during calls, making it the *fastest* method among all ways `Erlang` calls C-like code (including Port, PortDriver, etc.).

For `NIF`, while it is fast and efficient, it also has its own issues:

*First*, due to the lack of context switching, the execution of a `NIF` function will continuously occupy the CPU. If the function #link("https://www.erlang.org/doc/man/erl_nif.html\#lengthy_work")[takes too long to execute], it can lead to abnormal scheduling of the virtual machine and cause the program to become unresponsive. Therefore, the execution time of `NIF` functions needs to be as short as possible, or a large computational task should be divided into several smaller tasks.

*Second* is a *fatal flaw* — if there is an error in the `NIF` code that causes a crash (such as a memory error), it will crash the entire runtime environment (Beam, Erlang runtime virtual machine), leading to the entire program crashing and exiting. This is generally unacceptable, and developers need to write `NIF` functions as safely as possible, but this is a challenging task, as the situations one can consider are always fewer than those that could actually occur. At this point, `Rust` can demonstrate its advantages.

The `Rust` language has a wealth of safety designs that can prevent a significant portion of programming errors. In general business, this design may seem trivial, but it becomes crucial here. The characteristics of `Rust` can largely avoid `NIF` crashes, making the use of `NIF` safer and significantly mitigating the aforementioned fatal flaw. Thus, `Rust NIF` has become a powerful tool for improving the execution efficiency of `Erlang/OTP` code. *Therefore*, I chose this solution in the `Elixir`-based server framework to enhance code execution speed and reduce latency.

Although this solution is appealing in terms of performance, we still have to face some other issues in reality, such as the ecological situation. As a still relatively niche language, `Rust` is lacking in ready-made libraries. Although more and more people are porting some `C++` libraries to `Rust`, progress is slow, and they are basically in an unusable state. For example, I recently planned to deploy a physics engine on the server, but there is no mature and complete physics engine like `Physx` in the `Rust` ecosystem; I can only choose a project that seems to have comprehensive features and decent documentation, and silently hope that this project can continue to develop steadily in the future.

In summary, `Rustler` is a powerful tool for enhancing the execution efficiency of `Erlang/OTP` code, which is also the reason I am using it in this series. Game servers require high computational loads and low latency, making the speed of code execution extremely important, and the emergence of `Rustler` undoubtedly becomes the best solution. Although I have not encountered many issues so far, we will be able to determine whether this choice was right or wrong when we look back after the server's functionality is relatively complete.
