#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221123-mmo-server-from-scratch(9)-scene-server-movement-sync-3-player-movement-server.typ
// source_sha256: sha256:e72258cbcdd507bbd632106f1cc0745385d4a5ccd78030bc8cf94f6bd1c27058

#show: main.with(
  title: "MMORPG Game Server from Scratch (9) - Scene Server (7) - Movement Synchronization (3) - Player Movement - Server Part",
  desc: [Today we implement the highlight - *movement synchronization*. When a player moves, the server needs to be notified, which stores the movement states of all clients. The server periodically synchronizes the player's position changes to other players within the `AOI` range.],
  date: "2022-11-23",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221123-mmo-server-from-scratch(9)-scene-server-movement-sync-3-player-movement-server",
  sourceLang: "zh",
  translationSourceHash: "sha256:e72258cbcdd507bbd632106f1cc0745385d4a5ccd78030bc8cf94f6bd1c27058",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

Today we implement the highlight - *movement synchronization*. When a player moves, the server needs to be notified, which stores the movement states of all clients. The server periodically synchronizes the player's position changes to other players within the `AOI` range.

== Function Analysis

The basic process after the player's movement status is uploaded to the server is as follows:

1. The gateway receives the `movement` message and dispatches it to the corresponding `PlayerCharacter`;
2. The `PlayerCharacter` process receives the message and immediately notifies the corresponding `AoiItem` process to update the movement parameters and return, including parameters such as `position`, `velocity`, etc.;
3. The `AoiItem` process receives the message and updates its stored movement information;
4. The `coordinate update` scheduled task of `AoiItem` calculates the new coordinates of the player character based on the currently stored movement information and stores it in the `process state` and `AOI` coordinate system data structure, broadcasting the updated coordinate information to other players;
5. The gateway process sends the return value from the `PlayerCharacter` process back to the client.

```mermaid
sequenceDiagram

participant C as Client
participant G as GateServer
participant P as PlayerCharacter
participant A as AoiItem

C ->> G: Movement message
activate G
G ->> P: Transfer movement information
activate P
P ->> A: Update movement information
P -->> G: Return update result
deactivate P
G ->> C: Movement message reply
deactivate G

A ->> A: Movement Tick
```

As can be seen, the reporting of movement status and server calculations are decoupled, and the data updates of both do not affect each other. This can reduce the computational load of movement data, avoiding excessive consumption of server resources when the movement state changes frequently.

At the same time, the gateway server receiving the `Movement` message and sending reply messages is asynchronous for the client, meaning that the client does not need to wait for a server response after sending, which can slightly save resources for the client.

== Brief Implementation

=== GateServer.Message

This module is responsible for message dispatching and processing. When it receives a `Movement` message from the client, this module is responsible for forwarding the message to the `SceneServer.PlayerCharacter` process and sending a response message to the client based on the return value.

```elixir
def dispatch(

      %Packet{

        id: id,

        timestamp: timestamp,

        payload: {:entity_action, %Entity.EntityAction{action: {:movement, movement}}}

      },

      %{scene_ref: spid} = state,

      connection

    ) do

  # Deconstruct the message packet structure
  %Types.Movement{
    location: %Types.Vector{x: lx, y: ly, z: lz},
    velocity: %Types.Vector{x: vx, y: vy, z: vz},
    acceleration: %Types.Vector{x: ax, y: ay, z: az}
  } = movement

  # Send the message content to SceneServer.PlayerCharacter
  {:ok, _} =
    GenServer.call(spid, {:movement, timestamp, {lx, ly, lz}, {vx, vy, vz}, {ax, ay, az}})

  # Wrap the response message
  payload = {:result, %Reply.Result{packet_id: id, status_code: :ok, payload: nil}}

  # Send the response message to the client
  GenServer.cast(connection, {:send_data, payload})

  {:ok, state}

end
```

=== SceneServer.PlayerCharacter

Currently, the role of the `PlayerCharacter` process is merely to forward messages to the `AoiItem` process for processing, with no other logic. This situation will change significantly in the future.

```elixir
@impl true
def handle_call(
      {:movement, client_timestamp, location, velocity, acceleration},
      _from,
      %{aoi_ref: aoi} = state
    ) do
  GenServer.cast(aoi, {:movement, client_timestamp, location, velocity, acceleration})
  
  {:reply, {:ok, ""}, state}
end
```

=== SceneServer.AoiItem

This process is currently the main process for handling movement logic, which also includes the management and broadcasting functions of `AOI`. As mentioned earlier, the processing logic in this part will change in the near future, and for now, it serves as a testing function.

First is the function to receive `Movement` messages:

```elixir
@impl true
def handle_cast(
      {:movement, timestamp, location, velocity, acceleration},
      state
    ) do
  new_state = update_movement(timestamp, location, velocity, acceleration, state)

  {:noreply, new_state}

end

@spec update_movement(integer(), vector(), vector(), vector(), map()) :: map()
defp update_movement(
        timestamp,
        location,
        velocity,
        acceleration,
        %{system_ref: system, item_ref: item} = state
      ) do
  # Update the player's position in the coordinate management system
  {:ok, _} = CoordinateSystem.update_item_from_system(system, item, location)

  # Return the updated movement information for process state preservation
  %{
    state
    | movement: %{
        client_timestamp: timestamp,
        server_timestamp: :os.system_time(:millisecond),
        location: location,
        velocity: velocity,
        acceleration: acceleration
      }

  }

end
```

Next is the scheduled task for position updates:

```elixir
@impl true
def handle_info(
      :update_coord_tick,
      %{cid: cid, system_ref: system, item_ref: item, movement: movement, subscribees: subscribees} =
        state
    ) do
  # Calculate the new coordinates of the player character
  new_location =
    update_location(
      system,
      item,
      movement.server_timestamp,
      movement.location,
      movement.velocity
    )

  # If the position changes, broadcast the update
  if new_location != movement.location and subscribees != [] do
    broadcast_action_player_move(cid, new_location, subscribees)
  end

  {:noreply,
    %{state | coord_timer: make_coord_timer(), movement: %{movement | location: new_location, server_timestamp: :os.system_time(:millisecond)}}}

end
```

This scheduled task calculates the new coordinates based on the currently stored movement information and broadcasts to surrounding players.

Next is the scheduled task for obtaining surrounding players:

```elixir
@impl true
def handle_info(
      :get_aoi_tick,
      %{
        cid: cid,
        movement: %{location: location},
        system_ref: system,
        item_ref: item,
        subscribees: subscribees
      } = state
    ) do

  # Get the AoiItem process pids of surrounding players
  aoi_pids = refresh_aoi_players(system, item, cid, location, subscribees)

  {:noreply, %{state | aoi_timer: make_aoi_timer(), subscribees: aoi_pids}}
end
```

Broadcast function:

```elixir
@spec broadcast_action_player_move(integer(), vector(), [pid()]) :: any()
defp broadcast_action_player_move(cid, location, pids) do
  pids
  |> Enum.map(&Task.async(fn -> GenServer.cast(&1, {:player_move, cid, location}) end))
  |> Enum.map(&Task.await(&1))
end
```

Function to receive broadcast messages:

```elixir
@impl true
def handle_cast({:player_move, cid, location}, %{connection_pid: connection_pid} = state) do
  # Send broadcast message to the gateway server
  GenServer.cast(connection_pid, {:player_move, cid, location})
  
  {:noreply, state}
end
```

== Next Steps

After some consideration, I feel that the current position of the movement synchronization logic is not reasonable enough, and in order to leave space for other logic, I plan to reorganize the responsibilities and functions of the `PlayerCharacter` and `AoiItem` processes.
