#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221213-mmo-server-from-scratch(22)-visualize-server-frontend-coordinate-correction.typ
// source_sha256: sha256:c5066ea64e2260aa270153f683df55e526de73fd07456f2cbf1d9a1653083e0f

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (22) - Visualize Server (5) - Frontend Coordinate Correction",
  desc: [In the last section, we mentioned that the player's character position is now displayed on the webpage, but the position is misaligned. Therefore, in this section, we will analyze the cause of this issue and solve it.],
  date: "2022-12-13",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.tooling,
    blog-tags.frontend,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221213-mmo-server-from-scratch(22)-visualize-server-frontend-coordinate-correction",
  sourceLang: "zh",
  translationSourceHash: "sha256:c5066ea64e2260aa270153f683df55e526de73fd07456f2cbf1d9a1653083e0f",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

In the last section, we mentioned that the player's character position is now displayed on the webpage, but the position is misaligned. Therefore, in this section, we will analyze the cause of this issue and solve it.

After comparison, the coordinate axis direction of `PIXI.js` is consistent with the coordinate direction of my screenshot, where the `x` axis goes from left to right and the `y` axis goes from top to bottom, meaning the origin of the coordinates is at the top left corner.

That leaves us with one problem: the scale ratio between the actual scene size and the scene screenshot size.

In the webpage, the range of the scene is actually the range of our scene screenshot, which is also the resolution of the image.

In `PIXI.js`, the size of the image is actually the size of the sprite:

```javascript
console.log(bg.width, bg.height)
```

Thus, we have the true size of the scene (obtained from UE) and the size of the scene in the webpage. We just need to map them, which is essentially obtaining a ratio between the two:

```javascript
ratio = bg.width / 3000.0
```

Here, `3000.0` is the width of the scene in `UE`.

With the ratio, we can convert the coordinates of the character in the real scene to the coordinates of the scene in the browser:

```javascript
clist.forEach(character => {
    if (players[character.cid] == null) {
        let sprite = PIXI.Sprite.from('/images/arrow_64.png')
        scene.addChild(sprite)

		// Apply ratio
        sprite.position.set(character.location.x \* ratio, character.location.y \* ratio)
        sprite.scale.set(0.5)
        players[character.cid] = sprite
    } else {
		// Apply ratio
        players[character.cid].position.set(character.location.x \* ratio, character.location.y \* ratio)
    }
});
```

When setting the sprite coordinates, we transformed the coordinates, so now the player's character position in the scene on the webpage is correct:

#figure(image("/public/assets/img/2022/20221213-mmo-server-from-scratch(22)-visualize-server-frontend-coordinate-correction-1.png"), caption: "Pasted image 20221213211648.png")

Although there is still some error, it is not significant; the screenshot might be slightly skewed.

= Next Steps

From the image, we can see that I used a *small arrow* to represent the player's character. Intuitively, the direction of the arrow should align with the character's orientation, but currently, there is no related logic, so the arrow always points to the left. In the next step, we will implement this logic to make the character's state on the webpage look more complete.
