#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20220608-mmo-server-from-scratch(0)-introduction.typ
// source_sha256: sha256:6f82f8125f4b7c3ec05bdd57460c2ab6c4bea88759417e1d2e6dfe5dc624f14d

#show: main.with(
  title: "MMO Server From Scratch(0) - Introduction",
  desc: [MMO Server From Scratch(0) - Introduction],
  date: "2022-10-12",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.server,
    blog-tags.game,
    blog-tags.elixir,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20220608-mmo-server-from-scratch(0)-introduction",
  sourceLang: "zh",
  translationSourceHash: "sha256:6f82f8125f4b7c3ec05bdd57460c2ab6c4bea88759417e1d2e6dfe5dc624f14d",
  translationStatus: "machine",
)

= Introduction

I have always wanted to create an MMORPG game and have been learning along the way. I am starting a series to document the process of server development.

I have searched for a lot of information, but it has been fragmented and lacks a complete and detailed concept. Some discussions are too general about architecture, while others are merely theoretical about specific algorithms. As a pure outsider, these abstract materials have not provided me with particularly important guidance, so I have to try to reconstruct everything myself.

= Basic Concept

After reviewing numerous materials, I have a basic understanding of the overall architecture of an MMORPG server. Coincidentally, I previously delved into `Erlang` and `Elixir`, and I was deeply impressed by their inherent support for high concurrency, supervision trees, and the philosophy of failing fast. Therefore, I decided to implement the various components of the server using `Elixir`.

The rough architecture of the server in my mind is as follows:

```
                                        |----------|
                                        |  client  | x N
                                        |----------|

-----------------------------------------|-----|----------------------------------------------

|-------------|	        |--------------|         |-------------|        |--------------|
| auth_server | x N     | auth_manager | x 1     | gate_server | x N    | gate_manager | x 1
|-------------|         |--------------|         |-------------|        |--------------|

-----------------------------------------|-----|----------------------------------------------


                        |--------------|            |---------------|
                        | agent_server | x N	    | agent_manager | x 1
                        |--------------|            |---------------|

-----------------------------------------|-----|----------------------------------------------


                    |-------------------|            |--------------|
                    | scene_server(TBD) | x N	     | world_server | x 1
                    |-------------------|            |--------------|

-----------------------------------------|-----|----------------------------------------------

                |--------------|         |------------|         |--------------|
                | data_service | x N     | data_store | x N     | data_contact | x 1
                |--------------|         |------------|         |--------------|

-----------------------------------------|-----|----------------------------------------------

                                        |---------------|
                                        | beacon_server | x 1
                                        |---------------|
```

+ auth_server - For user login to the game
+ auth_manager - For managing `auth_server`, performing load balancing
+ gate_server - Gateway server, used to accept TCP connections from clients, encrypt and decrypt messages, and forward traffic
+ gate_manager - For managing `gate_server`, performing load balancing
+ agent_server - For executing non-scene user logic (TBD)
+ agent_manager - For managing `agent_server`, performing load balancing
+ scene_server - For executing scene logic, such as AOI, map chunk management, etc.
+ world_server - For overall management of the allocation of `scene_server` and handling world-level logic
+ data_service - In-memory storage node for the database, providing services to other servers
+ data_store - Persistent storage node for the database, used to save database data
+ data_contact - Data contact node for connecting various database nodes, while allocating database nodes to other servers for load balancing
+ beacon_server - Beacon server, used to connect various servers, exchange resources, and establish connections between nodes

*Database* is planned to use `Mnesia`, which inherently has clustering capabilities and can dynamically scale horizontally.

Client connections are planned to use `one process per client`, fully utilizing BEAM's lightweight thread capabilities to improve logic writing efficiency. Of course, these are just my guesses, and the actual performance remains to be seen.

= Project Address

#link("https://github.com/dyzdyz010/ex_mmo_cluster")[https://github.com/dyzdyz010/ex_mmo_cluster]

Since I cannot find like-minded individuals, I am fighting alone and do not know how long I can persist, but I hope someone can join me. Let's cherish the journey.
