#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221124-mmo-server-from-scratch(10)-scene-server-movement-sync-4-player-movement-client.typ
// source_sha256: sha256:057c8bba3e43b7462956ece8b4c7354234ef6796e83166c8342ad0157b5a3fc7

#show: main.with(
  title: "MMORPG Game Server from Scratch (10) - Scene Server (8) - Movement Synchronization (4) - Movement Synchronization - Player Movement - Client Side",
  desc: [Starting from this section, I decided to avoid posting code unless I find parts of the logic particularly complex and hard to explain. Since we are currently in the idea validation phase, the code is changing frequently, and what is written now may look completely different after a while, which could cause unnecessary trouble for readers. So everyone can focus on the implementation ideas 🤟],
  date: "2022-11-24",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.protobuf,
    blog-tags.ue5,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221124-mmo-server-from-scratch(10)-scene-server-movement-sync-4-player-movement-client",
  sourceLang: "zh",
  translationSourceHash: "sha256:057c8bba3e43b7462956ece8b4c7354234ef6796e83166c8342ad0157b5a3fc7",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

Starting from this section, I decided to avoid posting code unless I find parts of the logic particularly complex and hard to explain. Since we are currently in the idea validation phase, the code is changing frequently, and what is written now may look completely different after a while, which could cause unnecessary trouble for readers. So everyone can focus on the implementation ideas 🤟

Today we will discuss the *client side* of the movement synchronization implementation.

== Function Analysis

On the client side, the basic process of movement synchronization is as follows:

1. Check for speed changes; if there is a change, send a movement event.
2. The movement event callback function extracts the movement data and sends it to the server, while storing the event in the command queue. After receiving confirmation from the server, the event is removed from the event queue.
3. Other clients' `TcpConnection` modules receive the character movement broadcast messages sent by the server and call the corresponding module (`PlayerManager`) with it as a callback parameter for processing.
4. `PlayerManager` receives the movement synchronization message and retrieves the reference of the character in the scene based on `cid`. If it exists, it sends a movement status update event to it.
5. The moved character object receives the event and moves itself to the target coordinates.

== Brief Implementation

=== Sending Own Movement

First, to detect changes in the player's character movement, I created a component called `NetEntityActionComponent` (I know this is not a good name; I will change it later 😋) inside the character blueprint `ThirdPersonPlayerCharacter`. This component is responsible for storing the movement state changes of the player-controlled character in the command queue and sending them to `TcpConnection`. When the player moves the character using WSAD, the `ThirdPersonPlayerCharacter` class checks whether the current and previous frame speeds have changed. If there is a change, it sends the current character's `position`, `velocity`, `acceleration`, and other information to `NetEntityActionComponent`;

After receiving the movement message, `NetEntityActionComponent` sends the movement message to `TcpConnection` to further send the movement information to the server, while also receiving a return value (a protobuf package) and storing it in the command queue;

`TcpConnection` sends the movement information to the server. After receiving the message, the server updates the movement state of the player character on the server side and returns a response message to the client. After `TcpConnection` receives the response message, it queries the registered callback list and sends the message to the callback object, which is `NetEntityActionComponent`. After receiving the response message, `NetEntityActionComponent` removes the corresponding movement message from the command queue, indicating that the movement has been confirmed by the server. This process can be out of order; if a command that enters the queue later is confirmed first, it is assumed that all commands prior to that command are confirmed as well.

=== Receiving Other Players' Character Movements

The server sends movement messages of other players to the client, which are received by `TcpConnection`. Similarly, it queries the callback list and sends the message to the callback object, which is `PlayerManager` in this case.

After receiving the movement message, `PlayerManager` queries its stored dictionary of other players' characters based on the `cid` in the message. If it exists, it sends the new destination coordinates to that character. Upon receiving the coordinates, the character updates its target position and uses `AIController` to move towards the target coordinates. At this point, the client can see the movements of other players.

== Next Steps

After some thought, I feel that the current position of the movement synchronization logic is not reasonable enough. To leave space for other logic, I plan to reorganize the responsibilities and functions of the `PlayerCharacter` and `AoiItem` processes.
