#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221122-mmo-server-from-scratch(8)-scene-server-movement-sync-2-enter-scene-client.typ
// source_sha256: sha256:c8541bf60bb49432d18e6406963f259957810107104d1de5721f6c8676e3b9fa

#show: main.with(
  title: "MMORPG Game Server from Scratch (8) - Scene Server (6) - Movement Sync (2) - Player Entering Scene - Client Side",
  desc: [Today we will discuss how the client handles when a player enters the AOI range. In the previous section - MMORPG Game Server from Scratch (6)],
  date: "2022-11-22",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.ue5,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221122-mmo-server-from-scratch(8)-scene-server-movement-sync-2-enter-scene-client",
  sourceLang: "zh",
  translationSourceHash: "sha256:c8541bf60bb49432d18e6406963f259957810107104d1de5721f6c8676e3b9fa",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

Today we will discuss how the client handles when a player enters the `AOI` range. In the previous section - #link("/en/article/mmo-server-from-scratch/2022/20221028-mmo-server-from-scratch(7)-scene-server-movement-sync-1-enter-scene-server\#heading-2")[MMORPG Game Server from Scratch (6) - Scene Server (4) - Movement Sync (1) - Player Entering Scene - Server Side - Juejin (juejin.cn)] - the server's response to a player entering the range is immediate, and when other players send an enter message to oneself, the process will immediately return to the server. Later, we may consider designing a scheduled task to return multiple data items at once, which is a potential optimization direction to note.

== Function Analysis

For the client, it is purely a subscriber, only needing to wait for the server to return data for processing, without polling.

When the `TcpConnection` module of the client receives a message, it needs to determine the type of the message payload. If it is a `Player Enter` type message, it will call the correct callback object based on its stored `callback hash table`.

After the callback method receives the message, it unpacks the data to obtain the entering player's `CID` and `Location`, then notifies `GameMode` to generate a character in the scene, and stores the `CID` and character object reference in a dictionary for handling other messages such as `Movement`, `Player Leave`, etc.

== Brief Implementation

The content of this section is relatively simple, with the basic flow as follows:

```mermaid
sequenceDiagram

participant S as Server
participant T as TcpConnection
participant P as PlayerManager
participant G as GameMode

P ->> T: Bind Callback (self)
S ->> T: Packet (Player Enter)
T ->> P: Callback
P ->> G: Generate Character in Scene (Cid, Location)
G -->> P: Generated Character Reference

P ->> P: Store in Dictionary (Cid, Character Reference)
```

=== Binding Callback

Binding a callback simply means notifying the `TcpSocketConnection` module to store the message type and its own object reference in a dictionary:

```cpp
// PlayerManager.cpp

void APlayerManager::BeginPlay()
{
   Super::BeginPlay();

   // Player's own request to enter the scene
   TcpConnection->BindReplyDelegate(reply::Result::kEnterScene, this);
   
   // AOI broadcast message
   TcpConnection->BindMessageDelegate(Packet::kBroadcastAction, this);
}
```

```cpp
// MP5DemoTcpSocketConnection.cpp

void AMP5DemoTcpSocketConnection::BindMessageDelegate(Packet::PayloadCase PC, FMessageDelegateBase* MD)
{
   MessageDelegates.Add(PC, MD);
}
```

=== Handling Player Enter Messages

`PlayerManager` defines a `BlueprintImplementable` event that can be implemented in blueprints for subsequent logic:

```cpp
UFUNCTION(BlueprintImplementableEvent)
void OnPlayerEnter(int64 Cid, FVector3f Location);
```

Here is the callback function:

```cpp
void APlayerManager::OnMessageReceived(Packet* P)
{
   switch (P->payload_case())
   {
   case Packet::kResult:
      {
         types::Vector Location1 = P->result().enter_scene().location();
         EnterSceneCallback.Execute(FVector3f(Location1.x(), Location1.y(), Location1.z()));
         break;
      }
   case Packet::kBroadcastAction:
      {
         switch (P->broadcast_action().action_case())
         {
         case broadcast::player::Action::kPlayerEnter:
            {
               // Player enters range
               types::Vector Location2 = P->broadcast_action().player_enter().location();
               int64 Cid = P->broadcast_action().player_enter().cid();
               OnPlayerEnter(Cid, FVector3f(Location2.x(), Location2.y(), Location2.z()));
               break;
            }
         case broadcast::player::Action::kPlayerLeave:
            {
               // Player leaves range
               int64 Cid = P->broadcast_action().player_leave().cid();
               OnPlayerLeave(Cid);
               break;
            }
         default:
            break;
         }
      }
   default:
      break;
   }
}
```

Blueprint custom event implementation:

#figure(image("/public/assets/img/2022/20221122-mmo-server-from-scratch(8)-scene-server-movement-sync-2-enter-scene-client-1.png"), caption: "image.png")

== Next Steps

Next, we will implement the main feature - player movement synchronization, and the `multiplayer` aspect of the multiplayer game will finally take shape.
