#import "/templates/blog.typ": *
#import "/templates/enums.typ": *
#import "/templates/mod.typ": code-image
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221021-mmo-server-from-scratch(4)-scene-server-aoi-algorithm.typ
// source_sha256: sha256:8a9655bab6a4f725e39c47061c4a6abae91cf682d9ba52aa648dc4cc16bafd70

#show: main.with(
  title: "MMO Server From Scratch(4) - Scene Server(1) - AOI - Algorithm and Data Structure",
  desc: [This section focuses on the NIF part of the AOI module in the scene server, determining interfaces, algorithms, and data structures.],
  date: "2022-10-21",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.server,
    blog-tags.game,
    blog-tags.elixir,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221021-mmo-server-from-scratch(4)-scene-server-aoi-algorithm",
  sourceLang: "zh",
  translationSourceHash: "sha256:8a9655bab6a4f725e39c47061c4a6abae91cf682d9ba52aa648dc4cc16bafd70",
  translationStatus: "machine",
)

This section focuses on the `NIF` part of the `AOI` module in the scene server, determining interfaces, algorithms, and data structures.

= Function Analysis

`AOI (Area Of Interest)` is a module used to manage the positional relationships between various entities in a large world. It can accept requests from an entity to *query nearby other entities*, while also maintaining the data structure of positional relationships between entities. When an entity moves in the large world, the `AOI` module needs to update the entity's position in the data structure so that the business process returns the updated list of nearby entities when requested.

From the description, it is clear that this module requires frequent operations for querying, inserting, and deleting lists, which involves a considerable amount of computation. Therefore, if this functionality were to be implemented in `Elixir`, it might struggle, leading to delays in synchronization operations between clients due to insufficient computational speed, thus affecting the gaming experience. Hence, we choose to implement this module using a faster approach—`NIF (Native Implemented Functions)`, which allows us to implement the most computationally intensive parts in a more efficient language while providing a calling interface in `Elixir`, thereby linking the code of both languages and leveraging their strengths.

After some time searching online, we finally selected the #link("https://github.com/rusterlium/rustler", "Rustler") library, which uses `Rust` as the language for writing `NIF` functions and provides runtime safety guarantees, ensuring that errors in `NIF` functions do not crash the entire `BEAM` virtual machine. This is an important flaw of `NIF`, and `Rustler` addresses this issue. Additionally, `Rust` also provides safe memory management features, allowing me not to constantly worry about memory allocation and deallocation as I would in `C++`.

= Algorithm and Data Structure Analysis

The operations we need can be categorized into three types: *search*, *insert*, and *delete*. The data structures we can choose from are primarily two: `array` and `linked list`. Below, we will discuss the characteristics of both structures.

== Array

An array is a contiguous block of memory space, accessed via index subscripts.

For *searching*, the time complexity in different scenarios is shown in the table:

#figure(caption: "Array Search Time Complexity")[
  #table(
    columns: (1fr, 1fr, 1fr),
    inset: 4pt,
    align: (center, center, center),

    table.header("Has Index", "Is Ordered", "Time Complexity"),
    [Yes], [-], [O(1)],
    [No], [No], [Linear Search O(n)],
    [No], [Yes], [Binary Search O(log(n))],
  )]

For `insert` and `delete`, assuming the index of the element is already determined, the complexity is `O(n)` because all subsequent elements need to be moved as a whole when inserting or deleting an element.

It can be seen that the `array` structure is more efficient for `searching`, but less efficient for `inserting/deleting` elements.

== Linked List

A linked list is a chain structure formed by pointers within elements pointing to other elements.

For linked lists, since `searching` can only traverse the structure, its time complexity is `O(n)`. However, if the querying party holds the element and the linked list is ordered, the complexity can be relatively reduced, but in the worst case, it remains `O(n)`.

For `inserting` and `deleting`, if we do not consider the searching process, a linked list only needs to modify the pointers of the element itself and its neighboring elements, so its time complexity is `O(1)`.

== Summary

In the context of `AOI`, the typical flow is *player moves -> `AOI` updates element positions -> player retrieves other elements within a certain radius*. When `AOI` updates element positions, it means that the order of elements will frequently change, which causes the array to lose its greatest advantage—*indexing*. If an array structure is used, then every operation performed on the elements will have a prerequisite operation—*binary search*. In this case, compared to `linked lists`, the efficiency should be slightly inferior.

Both `arrays` and `linked lists` can be optimized by establishing a *layer* mechanism to further reduce time costs. As for which optimized structure is superior, I will compare them after implementing everything when I have time.

As for this series, since I am not very familiar with linked lists due to not using them for a long time, and I found a #link("https://discord.com/blog/using-rust-to-scale-elixir-for-11-million-concurrent-users", "Discord article") on a similar issue, which used a mechanism similar to `skip lists` to turn the array into two layers, improving the speed of operations on it. For convenience, I have temporarily chosen to use the `data` form and modify it based on the `Discord` code.

= Brief Implementation

First, we need to add dependencies to our `scene_server`, adding the dependency to the `deps` function in the `mix.exs` file:

```elixir
{:rustler, "~> 0.26.0"}
```

Then use the command to create the `NIF` module:

```bash
mix rustler.new
```

Follow the prompts to enter the module names in `Elixir` and `Rust`. I used `SceneServer.Native.CoordinateSystem` and `coordinate_system`.

This command will generate a `native` folder under the `scene_server` project folder and place the `NIF` module file inside it:

#figure(caption: "Rustler Structure")[
  #image("/public/assets/img/2022/20221021_rustler_structure.png")
]

== SortedSet Analysis

The above `Discord` article implemented an array structure called `SortedSet`, which contains an array of elements as `Bucket`, and each `Bucket` contains an array of elements as `Item`, thus defining an array as two layers. In this section, I will also use these names to modify the code.

== Item

`Item` is the most basic element structure, containing three properties: `entity ID`, `coordinates`, and `axis type`:

```rust
// Axis enumeration type
#[derive(NifUnitEnum, Clone, Debug, Copy)]
pub enum OrderAxis {
    X,
    Y,
    Z,
}

// Coordinate structure type
#[derive(NifTuple, Clone, Debug, Copy)]
pub struct CoordTuple {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

// Item structure type
#[derive(NifStruct, Clone, Debug, Copy)]
#[module = "Item"]
pub struct Item {
    pub cid: i64,
    pub coord: CoordTuple,
    pub order_type: OrderAxis,
}
```

The `NifUnitEnum`, `NifTuple`, and `NifStruct` are used to convert types within `Rust` to `Elixir` types so that they can be passed.

To allow `Item` instances to be compared and sorted, we need to implement several `Traits`:

1. PartialEq
2. PartialOrd
3. Eq
4. Ord

The implementation details will not be shown here; interested readers can implement them on their own. Here, we will discuss how to compare `Item` instances.

For `sorting`, we need a value that can be compared for size, which in this case is the coordinate value `coord`. But how do we determine the order of the three directions? This is where `order_type` comes into play; if `order_type` indicates which axis, we will use the value from that axis in the coordinates for comparison.

For `searching`, having the above comparison is not enough; we must not forget our `cid` property. Equal coordinate values do not imply that two `Item` elements are equal. Think about when we need to search for an element? There is only one unique scenario, which is to find the corresponding player/entity's `Item`, and the distinction between entities is made using `cid`. Therefore, we also need to include the logic for `cid` equality in the equality condition.

In addition, we need a `distance` method to calculate the distance between two `Item` instances, which can be done using simple Pythagorean theorem.

After that, we can write a few unit test cases to check if the `Item` functionality is working correctly.

== Bucket

`Bucket` is a structure that contains an array of `Item`:

```rust
#[derive(NifStruct, Clone, Debug)]
#[module = "Bucket"]
pub struct Bucket {
    pub data: Vec<Item>,
}
```

As a type that contains a list of elements, `Bucket` needs to implement methods for searching, inserting, and deleting elements. However, the thoughtful `Rust` has already implemented *binary search* for us; the delete method is also implemented by the built-in `Vec` type in `Rust`; for insertion, we need to implement it ourselves, wrapping the insertion method of `Vec`. This is because we want to keep the length of `Bucket` fixed. According to #link("https://doc.rust-lang.org/std/vec/struct.Vec.html\#guarantees", "Rust official documentation"), `Vec` has a `capacity` property, which represents the size of pre-allocated memory for `Vec`. If the length of `Vec` exceeds its `capacity`, `Rust` will need to allocate additional memory for it, causing unnecessary computational overhead; moreover, when we need to `insert/delete` elements, we prefer the array length to be as short as possible. Therefore, considering the above factors, we need `Bucket` to have a fixed length.

Thus, in the method for inserting elements, we need to check the length of the list. If it exceeds the set length, we need to `split` the list, dividing one `Vec` into two equal halves.

As an element of `SortedSet`, `Bucket` also needs to have comparison capabilities. However, the special aspect is that the comparison target of `Bucket` is `Item`, because the objects we generally search for are `Item`, and when searching in `SortedSet`, we need to determine which `Bucket` the given `Item` is in.

Finally, `Bucket` also needs a function to return a list of other `Item` instances within a certain range of a given `Item`. The implementation is straightforward; we can use the `filter` method to traverse the elements in the list, and this process can be optimized for parallel execution using the `Rayon` library.

== SortedSet

`SortedSet` is the outermost true element array. It is a structure that contains an array of `Bucket`, and it also includes properties such as capacity and the number of elements:

```rust
#[derive(Debug, NifStruct, Clone, Copy)]
#[module = "Configuration"]
pub struct Configuration {
    // Maximum capacity of Bucket
    pub bucket_capacity: usize,

    // Maximum capacity of SortedSet
    pub set_capacity: usize,
}

#[derive(Debug, NifStruct, Clone)]
#[module = "SortedSet"]
pub struct SortedSet {
    configuration: Configuration,
    buckets: Vec<Bucket>,
    size: usize,
}
```

Similar to `Bucket`, we also want `SortedSet` to have a maximum length to avoid additional memory allocation overhead, but it does not need to split; just a maximum capacity will suffice.

The method implementations are similar to those of `Bucket`, requiring methods for `creating lists`, `searching for elements`, `inserting elements`, `deleting elements`, and `finding a list of Items within a certain range`. For `SortedSet`, all operations on elements need to first find the `Bucket` and then operate on the `Item` within the corresponding `Bucket`.

== CoordinateSystem

Finally, we have our top-level structure `CoordinateSystem`, which contains three `SortedSet` members for the X, Y, and Z axes:

```rust
#[derive(Debug, NifStruct, Clone)]
#[module = "CoordinateSystem"]
pub struct CoordinateSystem {
    configuration: Configuration,
    axes: Vec<SortedSet>,
}
```

Here, `SortedSet` is stored in a list form for future parallel optimization. For example, the `insert element` method:

```rust
pub fn add(&mut self, item: &Item) -> AddResult {
    let mut jobs: Vec<SetAddResult> = Vec::with_capacity(3);

    self.axes
        .par_iter_mut()
        .enumerate()
        .map(|(idx, ss)| {
            return ss.add(Item {
                cid: item.cid,
                coord: item.coord.clone(),
                order_type: OrderAxis::axis_by_index(idx),
            });
        })
        .collect_into_vec(&mut jobs);

    let result = match (jobs[0], jobs[1], jobs[2]) {
        (SetAddResult::Added(ix), SetAddResult::Added(iy), SetAddResult::Added(iz)) => {
            AddResult::Added(ix, iy, iz)
        }
        (rx, ry, rz) => AddResult::Error((rx, ry, rz)),
    };

    result
}
```

The `par_iter_mut()` method converts the elements of a `Vec` into a parallel iterator, allowing the `map` method to run in parallel on each element.

The methods that `CoordinateSystem` needs to implement are all the methods required by the interface. Currently implemented are:

1. Establish structure
2. Insert element
3. Delete element
4. Update element position
5. Find a list of `Item` within a certain range

= Next Steps

The `NIF` part is basically complete here; we have a rudimentary but relatively complete `AOI NIF` library. The next step is to continue integrating it into the `Elixir` program so that it can be called by player processes.
