#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221024-mmo-server-from-scratch(5)-scene-server-timesync.typ
// source_sha256: sha256:b70200b34eda1063098a5efdeca6b89cc91c7d70bd06946c6cf4ef6fe41747e4

#show: main.with(
  title: "MMORPG Game Server from Scratch (5) - Scene Server (3) - Time Synchronization",
  desc: [Today, we implemented a simple feature - time synchronization. Time synchronization does not mean making the clocks of the client and server completely consistent, but rather calculating the delay between the client and server through a round-trip.],
  date: "2022-10-24",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221024-mmo-server-from-scratch(5)-scene-server-timesync",
  sourceLang: "zh",
  translationSourceHash: "sha256:b70200b34eda1063098a5efdeca6b89cc91c7d70bd06946c6cf4ef6fe41747e4",
  translationStatus: "machine",
)

Today, we implemented a simple feature - *time synchronization*.

== Time Synchronization

Time synchronization does not mean making the clocks of the client and server completely consistent, but rather calculating the delay between the client and server through a round-trip, which facilitates both parties in verifying and predicting data.

The message sending process for time synchronization between the server and client is as follows:

```mermaid
sequenceDiagram

participant C as Client
participant S as Server
Note over C: client_timestamp1
C ->>+ S: TimeSync()
Note over S: server_timestamp1
S -->> C: TimeSync()
Note over C: client_timestamp2
Note over C: delay = (client_timestamp2 - client_timestamp1) / 2
C ->> S: TimeSync()
Note over S: server_timestamp2
Note over S: delay = (server_timestamp2 - server_timestamp1) / 2
```

1. The client initiates a time synchronization request by sending the *first* `TimeSync` packet to the server, storing its current timestamp.
2. The server receives the *first* `TimeSync` packet from the client, stores its current timestamp, and immediately sends the *first* `TimeSync` packet to the client.
3. The client receives the *first* `TimeSync` packet from the server, obtains its current timestamp, calculates the *network delay* based on the current and the two previous timestamps, stores it, and immediately sends the *second* `TimeSync` packet to the server.
4. The server receives the *second* `TimeSync` packet from the client, obtains its current timestamp, calculates the *network delay* based on the current and the two previous timestamps, stores it, and the time synchronization process ends.

This process can be repeated multiple times to average the values for improved accuracy.

== Implementation Logic

The implementation of this feature involves both the `gate_server` and `scene_server`, as the content requiring network delay compensation generally resides within large map scenes. Therefore, the `time synchronization` process is currently designed to be completed on the `scene_server`.

The basic process for server-side time synchronization is as follows:

1. The `gate_server` receives the packet for parsing, determines whether it is a `TimeSync` packet, and if so, retrieves the `PlayerCharacter` process ID and sends a `time_sync` message to it.
2. The `PlayerCharacter` process receives the `time_sync` message, obtains the current timestamp, checks if it is the first time receiving the `time_sync` message, and if so, stores the current timestamp in the process state; if not, it retrieves the last timestamp from the process state and calculates the network delay. Depending on the situation, it returns different responses to the `gate_server`.
3. The `gate_server` receives the response and determines whether it should send a `TimeSync` packet to the client based on the response.

== Brief Code

First, here is the message parsing and packet sending part for the `gate_server`:

```elixir
def dispatch(
      %Packet{id: id, payload: {:time_sync, _}},
      %{scene_ref: spid} = state,
      connection
    ) do
  {:ok, new_timestamp} = GenServer.call(spid, :time_sync)

  if new_timestamp != :end do
    packet = %Packet{id: id, timestamp: new_timestamp, payload: {:time_sync, %TimeSync{}}}
    GenServer.cast(connection, {:send_data, packet})
  end

  {:ok, state}
end
```

Then, here is the time synchronization logic part for the `PlayerCharacter` process in the `scene_server`:

```elixir
def handle_call(
      :time_sync,
      _from,
      %{old_timestamp: old_timestamp, net_delay: old_delay} = state
    ) do
  new_timestamp = :os.system_time(:millisecond)

  case old_timestamp do
    nil ->
      {true, %{state | old_timestamp: new_timestamp}}
      {:reply, {:ok, new_timestamp}, %{state | old_timestamp: new_timestamp}}

    _ ->
      temp_delay = div(new_timestamp - old_timestamp, 2)
      Logger.debug("CS delay: #{temp_delay}")

      new_delay =
        if old_delay != 0 do
          div(temp_delay + old_delay, 2)
          # ((new_timestamp - old_timestamp) / 2 + old_delay) / 2
        else
          temp_delay
        end

      {false, %{state | old_timestamp: nil, net_delay: new_delay}}

      {:reply, {:ok, :end}, %{state | old_timestamp: nil, net_delay: new_delay}}
  end
end
```

With this, the game's `time synchronization` feature is complete. The next step focuses on implementing the display of other players on the client side.
