#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221026-mmo-server-from-scratch(6)-scene-server-movement-sync-0.typ
// source_sha256: sha256:d1c1c387d1e7e99df93874d07bff705b943fd9634aabf208909c0179cdff5955

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (6) - Scene Server (4) - Movement Synchronization (0)",
  desc: [This section begins to explore the issue of character movement synchronization between the client and server. Function Analysis The reason why multiplayer games are multiplayer is that every player's actions can be seen by other players, creating an atmosphere where everyone is in the same world. Among them, the synchronization of player movement is the most fundamental and important, as it represents the proximity relationship between players and also delineates the range in which players can affect the world.],
  date: "2022-10-26",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.rust,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221026-mmo-server-from-scratch(6)-scene-server-movement-sync-0",
  sourceLang: "zh",
  translationSourceHash: "sha256:d1c1c387d1e7e99df93874d07bff705b943fd9634aabf208909c0179cdff5955",
  translationStatus: "machine",
)

This section begins to explore the issue of character movement synchronization between the client and server.

== Function Analysis

The reason why multiplayer games are multiplayer is that every player's actions can be seen by other players, creating an atmosphere where everyone is in the same world. Among them, the synchronization of player movement is the most fundamental and important, as it represents the proximity relationship between players and also delineates the range in which players can affect the world.

In the early stages, I consulted various materials but found no clear implementation methods; they were all theoretical, and my skills were limited to put them into practice. However, a few days ago, I came across the article #link("https://juejin.cn/post/7041560950897377293")[2 Days to Create a Real-Time Multiplayer Battle, 200ms Delay Can Still Be Smooth? - Juejin (juejin.cn)], which detailed the potential issues that may arise in position synchronization, such as stuttering and lack of smoothness in movement on both the client and other players' ends. It also proposed a solution that I think is quite good, which is the `command queue`.

=== Command Queue

The article mentioned a reconciliation formula:

*Predicted State = Authoritative State + Predicted Input*

Where `Authoritative State` can be considered as the server's state, because in multiplayer games, the server's data is authoritative. `Predicted State` is the state displayed by the client, as the client's state takes time to be sent to the server and confirmed. Therefore, to prevent the player's character from stuttering, the client performs actions in advance instead of waiting for the server's response before proceeding to the next action, which would greatly affect the player experience. `Predicted Input` refers to the state changes of the client's character movement.

It can be seen that the client only needs to continuously store the events of movement state changes in a queue structure and perform real-time display on the front end. Once the server confirms a certain state change, the event is removed from the queue. Overall, this is equivalent to a `producer-consumer` structure.

#figure(image("/public/assets/img/2022/20221026-mmo-server-from-scratch(6)-scene-server-movement-sync-0-1.png"))

Under normal circumstances, this method can ensure that the display effect on the player's end is very smooth. However, when the delay is high, this command queue may be interrupted by some actions of other players towards the current player, such as being immobilized during combat. This leads to a conflict between the predicted state on the client and the authoritative state from the server. At this point, to ensure consistency between the client's and the server's authoritative data, the predicted state change events in the queue must be discarded, resulting in the player being pulled back to the position that is consistent with the server's state. Although this may not seem like a good experience, it is indeed the cost of latency.

=== Server Coordinate Calculation

To reduce network transmission volume, I plan to only send events when the movement state changes, rather than sending displacements at fixed time intervals. For example, changes in acceleration and velocity. I intend to implement variable acceleration motion on the server, but for now, to simplify, I will only consider uniform motion.

When the player's movement state changes, a data packet will be sent to the server. The server's `AOI` module receives the movement state data and stores it, and it has a timed task to periodically update the position data of the player's character on the server.

The calculation principle is that the `AoiItem` process associated with a single player stores the movement state data while also storing the timestamps from the client and server. Currently, the client timestamp is not used but is planned for future validation. When the timed task is triggered, a time interval can be obtained based on the current and previously stored server timestamps. With time and velocity, the current position of the player's character can be calculated. After the calculation is complete, the current timestamp is overwritten onto the stored timestamp, preparing for the next timed trigger.

== Brief Implementation

=== Client Movement Submission & Command Queue

The client defines a new *Component* to implement a method for sending movement states and a queue structure:

```arduino
UCLASS( ClassGroup=(Custom), meta=(BlueprintSpawnableComponent) )
class MP5DEMO_API UNetEntityActionActorComponent : public UActorComponent, public FMessageDelegateBase
{
   GENERATED_BODY()

public:    
   // Sets default values for this component's properties
   UNetEntityActionActorComponent();

   // Character movement component reference
   UPROPERTY(EditAnywhere, BlueprintReadWrite)
   UCharacterMovementComponent *MoveComp;

   // TCP message module reference
   UPROPERTY(EditAnywhere, BlueprintReadWrite)
   AMP5DemoTcpSocketConnection *TcpConnection;

   // Send movement message
   UFUNCTION(BlueprintCallable)
   void SendMovement(FVector3f Location, FVector3f Velocity, FVector3f Acceleration);

   // Get command queue length
   UFUNCTION(BlueprintCallable)
   int32 MoveQueueLength();

   // Server response handling callback
   virtual void OnMessageReceived(Packet *P) override;

protected:
   // Called when the game starts
   virtual void BeginPlay() override;

   // Command queue and manual count
   TQueue<Packet*> MovementQueue;
   int32 QueueCounter = 0;

public:    
   // Called every frame
   virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
};
```

As can be seen, this class also inherits from the `FMessageDelegateBase` class to register message handling functions with `AMP5DemoTcpSocketConnection`. The following command queue uses a technique with an additional variable because the FIFO structure `TQueue` in UE is implemented as a linked list and does not provide a default length method. Therefore, I used an `int` variable, incrementing it by +1 when adding elements and decrementing it by -1 when removing elements, thus achieving manual length tracking.

The elements stored in the command queue are of type `Proto`, which facilitates obtaining the message response ID during callbacks and restoring the previous movement state in case of prediction conflicts.

=== Server Movement Calculation

On the server side, to achieve efficient calculations, the mathematical operations are also placed in `NIF`, currently together with `coordinate_system`. The code:

```rust
pub fn calculate_coordinate(
    old_timestamp: i64,
    new_timestamp: i64,
    location: Vector,
    velocity: Vector,
) -> Vector {
    let mut result: Vector = location.clone();

    if velocity == (Vector{x: 0.0, y: 0.0, z: 0.0}) {
        result = location;
    } else {
        // Get time interval and convert units to seconds
        let time = (new_timestamp - old_timestamp) as f64 / 1000.0;
        result.x = location.x + velocity.x \* time;
        result.y = location.y + velocity.y \* time;
        result.z = location.z + velocity.z \* time;
    }

    return result;
}
```

A timed task is created within the `AoiItem` process, performing calculations at fixed time intervals:

```elixir
# Create timer
defp make_coord_timer() do
  Process.send_after(self(), :update_coord_tick, @coord_tick_interval)
end

# Timed task message handling
@impl true
def handle_info(
      :update_coord_tick,
      %{system_ref: system, item_ref: item, movement: movement} = state
    ) do

  # Get new position
  new_location = if movement.velocity != {0.0, 0.0, 0.0} do
    new_location = CoordinateSystem.calculate_coordinate(movement.server_timestamp, :os.system_time(:millisecond), movement.location, movement.velocity)
    CoordinateSystem.update_item_from_system(system, item, new_location)
    new_location
  else
    movement.location
  end

  # Update new position to state
  {:noreply, %{state | coord_timer: make_coord_timer(), movement: %{movement | location: new_location}}}
end
```

== Next Steps

The next step will focus on generating other players in the scene on the client side, taking another step towards multiplayer networking.
