#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221130-mmo-server-from-scratch(16)-scene-server-movement-error-notes.typ
// source_sha256: sha256:e58918811d801c5c105f25c7cc57558b8a0fbc8cdb292aba8fc8ebc5c70e9e08

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (16) - Scene Server (12) - Thoughts on Movement Error",
  desc: [Today I had a sudden idea to see how much the player character's position on the server differs from that on the client.],
  date: "2022-11-30",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
    blog-tags.software,
    blog-tags.frontend,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221130-mmo-server-from-scratch(16)-scene-server-movement-error-notes",
  sourceLang: "zh",
  translationSourceHash: "sha256:e58918811d801c5c105f25c7cc57558b8a0fbc8cdb292aba8fc8ebc5c70e9e08",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

Today I had a sudden idea to see how much the player character's position on the server differs from that on the client.

= Movement Error

The error is essentially the comparison of the position sent from the *client* at a certain moment with the current position on the *server*.

The error objectively exists because, influenced by factors such as latency, the two coordinates being compared are not strictly from the same moment in time.

For the error caused by *latency*, the client sends the current coordinates to the server, which have already experienced a delay. When the server compares, it is comparing with coordinates from some time ago, which will certainly result in a non-zero difference.

For the error caused by *server scheduled tasks*, since the current server is set to execute every `100ms`, if the moment of comparison is not the execution moment, a time difference will form within that `100ms`, causing an error. For example, if the server receives a displacement message at the current moment, and the server's movement calculation scheduled task has `10ms` until the next call, it means that the coordinates currently stored on the server are from `90ms` ago. At this point, if we calculate the difference between the client and server coordinates, there will definitely be an error.

= Error Control

We certainly hope that the data between the client and server can be completely consistent with no errors, but unfortunately, this is impossible. There is latency in communication between the client and server, and this latency is not entirely controllable. Even in a stable network condition, the value of latency is constantly changing. Even a change of `1ms` can lead to differences in data on both ends, and if the fluctuations are more severe, the differences will be significantly visible.

Since the error cannot be completely eliminated, let's change our approach. Although the error is caused by these uncontrollable factors, their differences are limited.

Let's take an example. Suppose the character's movement speed is `500/s`, then the maximum error caused by *scheduled tasks* would be:

5001000∗100=50\\frac(500, 1000) \* 100 = 501000500​∗100=50

That is, the maximum error per second in any axis direction is `50`. This error is influenced by the time interval of the scheduled task; the longer the interval, the greater the maximum error.

For the error caused by *latency*, assuming the latency is `150ms`, then the maximum error would be:

5001000∗150=75\\frac(500, 1000) \* 150 = 751000500​∗150=75

That is, the maximum error per second in any axis direction is `75`. This error is influenced by the latency time; the greater the latency, the larger the maximum error.

We only need a maximum value, so we take the larger of the two as the maximum tolerable error. If the error obtained from the comparison exceeds this maximum value, it likely indicates that there are some issues on the client side, such as cheating.

= Visualization

We can set up a `Web` server on the server side to display the real-time changes of object coordinates on the server in a browser page.

Create a `Phoenix` framework project, which is also developed in the `Elixir` language, making it very convenient to connect with the scene server without needing additional protocols; we can simply use the existing `BEAM` inter-node communication method.

The web backend periodically pulls the object list and their coordinates from the scene server and pushes them to the frontend via `WebSocket`. The frontend uses a 2D rendering framework to render the data. This way, we can have a more intuitive understanding of the motion state of objects on the server.

= Next Steps

Next, we will implement this `Web` server to make the object data on the server more intuitive.
