#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/mmo-server-from-scratch/2022/20221028-mmo-server-from-scratch(7)-scene-server-movement-sync-1-enter-scene-server.typ
// source_sha256: sha256:ff7d69ebdc9c6af314063cc75982a3f5001805430ef3381d6c3cbefe88db3597

#show: main.with(
  title: "Starting from Zero: MMORPG Game Server (7) - Scene Server (5) - Movement Synchronization (1) - Player Entering Scene - Server Part",
  desc: [There are many things that need to be synchronized for movement synchronization. Today, we will first study how to synchronize when a player enters the scene to other players.],
  date: "2022-10-28",
  tags: (

    blog-tags.programming,
    blog-tags.mmo,
    blog-tags.game,
    blog-tags.server,
    blog-tags.elixir,
  
  ),
  lang: "en",
  i18nKey: "mmo-server-from-scratch/2022/20221028-mmo-server-from-scratch(7)-scene-server-movement-sync-1-enter-scene-server",
  sourceLang: "zh",
  translationSourceHash: "sha256:ff7d69ebdc9c6af314063cc75982a3f5001805430ef3381d6c3cbefe88db3597",
  translationStatus: "machine",
)

#quote(block: true)[
  Code repository for this series: #link("https://github.com/dyzdyz010/ex_mmo_cluster")[Stargazers · dyzdyz010/ex\_mmo\_cluster (github.com)]
]

There are many things that need to be synchronized for movement synchronization. Today, we will first study how to synchronize when a player enters the scene to other players.

== Function Analysis

When a player enters the scene, they need to be visible to nearby players, and the current player also needs to see the nearby players. This requires each player to send and receive messages of `player entering`, along with the player's `ID` and `location`.

In addition to sending and receiving messages, it is also necessary to decide when to send and receive these messages. Initially, my idea was that when the user sends an `EnterScene` message to the server, the server would immediately search for nearby players and then return the player list to the client with the `response`. However, after thinking it over, this approach greatly slowed down the initialization process of the player's `PlayerCharacter` and the corresponding `AoiItem` processes, which could lead to unexpected consequences causing initialization failures; moreover, it is not a big deal if the player sees the surrounding people a little later when they just enter the scene, which has minimal impact on the gaming experience.

Then I came up with another method where each process only *actively* sends messages to other player processes and *passively* receives messages from other player processes, avoiding actively pulling information from other player processes. Due to the high concurrency and communication through message sending and receiving, pulling information could lead to a situation where both sides have sent messages and are waiting for responses, resulting in a deadlock.

In the previous article #link("/en/article/mmo-server-from-scratch/2022/20221026-mmo-server-from-scratch(6)-scene-server-movement-sync-0")[Starting from Zero: MMORPG Game Server (6) - Scene Server (4) - Movement Synchronization (0) - Juejin (juejin.cn)], I mentioned that a scheduled task was designed in the `aoi_item` process to periodically query the set of other players within a certain radius based on its own coordinates from the `coordinate_system` module. I found that I could make use of this process. I can leverage the list of nearby players stored in the process; when the scheduled task is triggered and a new player list is obtained, I can compare it with the old list to get two lists: the `entering scene` list and the `leaving scene` list. Assuming that everyone's `AOI` range is consistent, having these two lists allows me to know my status with respect to other players because when I can see another person, that person can also see me. This way, I can transform `collecting information about other players` into `sending my own information to other players`.

Therefore, when a new player enters the map, they only need to notify the server to create the relevant process, and the task of broadcasting the status is handed over to the scheduled task. If the time interval is set small enough, the impact on the client experience can be almost negligible.

== Brief Implementation

=== SceneServer.AoiItem

I previously mentioned that I was not quite sure whether it was a good idea for the `aoi_item` process to hold the `PID` of the gateway process, but now for convenience, I chose to store it:

```elixir
# aoi_item.ex

# Process state initialization
@impl true
def init({cid, client_timestamp, location, connection_pid, player_pid, system}) do
  {:ok,
    %{
      cid: cid,
      player_pid: player_pid,
      connection_pid: connection_pid,
      system_ref: system,
      item_ref: nil,
      movement: %{
        client_timestamp: client_timestamp,
        server_timestamp: :os.system_time(:millisecond),
        location: location,
        velocity: {0.0, 0.0, 0.0},
        acceleration: {0.0, 0.0, 0.0}
      },
      subscribees: [],
      interest_radius: 500,
      aoi_timer: nil,
      coord_timer: nil
    }, {:continue, {:load, location}}}
end
```

Here, `subscribees` represents the list of subscribed players, i.e., other players around the player; `connection_pid` is the `ID` of the player's gateway process.

For the scheduled task, I used `Process.send_after/3` to create the timer. In the scheduled task, I need to obtain the list of nearby players and the changes to it:

```elixir
# Scheduled task
@impl true
def handle_info(
      :get_aoi_tick,
      %{
        cid: cid,
        movement: %{location: location},
        system_ref: system,
        item_ref: item,
        subscribees: subscribees
      } = state
    ) do
  aoi_pids = refresh_aoi_players(system, item, cid, location, subscribees)

  {:noreply, %{state | aoi_timer: make_aoi_timer(), subscribees: aoi_pids}}
  # {:noreply, state}
end

@spec refresh_aoi_players(
        CoordinateSystem.Types.coordinate_system(),
        CoordinateSystem.Types.item(),
        integer(),
        vector(),
        [pid()]
      ) :: no_return()
defp refresh_aoi_players(system, item, cid, location, subscribees) do
  # Get the list of player PIDs within a radius of 10000
  aoi_pids = get_aoi_players(system, item, 10000.0)
  leave_pids = subscribees -- aoi_pids
  enter_pids = aoi_pids -- subscribees

  # Broadcast state changes
  broadcast_action_player_leave(cid, leave_pids)
  broadcast_action_player_enter(cid, location, enter_pids)

  aoi_pids
end
```

As the number of players increases later, the number of targets for broadcasting will also rise. Therefore, to allow broadcast messages to be sent out in parallel to everyone, I currently use the following method for convenience (taking player entering the scene as an example), which may later be changed to `Poolboy`:

```elixir
# Broadcast function
@spec broadcast_action_player_enter(integer(), vector(), [pid()]) :: any()
defp broadcast_action_player_enter(cid, location, pids) do
  pids
  |> Enum.map(&Task.async(fn -> GenServer.cast(&1, {:player_enter, cid, location}) end))
  |> Enum.map(&Task.await(&1))
end

# Corresponding receiving function
@impl true
def handle_cast({:player_enter, cid, location}, %{connection_pid: connection_pid} = state) do
  # Send message to the gateway process
  GenServer.cast(connection_pid, {:player_enter, cid, location})

  {:noreply, state}
end
```

=== GateServer.TcpConnection

After the gateway process receives messages from the player process, it needs to package the messages and send them to the client. Without further ado, here’s the code:

```elixir
# Gateway process receives messages from player process
@impl true
def handle_cast({:player_enter, cid, location}, state) do
  GateServer.Message.send_player_enter(cid, location, self())

  {:noreply, state}
end

# Send player enter message to the client
@spec send_player_enter(integer(), SceneServer.Aoi.AoiItem.vector(), pid()) :: no_return()
def send_player_enter(cid, {x, y, z} = _location, connection) do
  action = %Broadcast.Player.Action{action: {:player_enter, %Broadcast.Player.PlayerEnter{cid: cid, location: %Types.Vector{x: x, y: y, z: z}}}}
  payload = {:broadcast_action, action}

  GenServer.cast(connection, {:send_data, payload})
end
```
