#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/meta/2022/vitepress-theme-oblivion.typ
// source_sha256: sha256:02f65745604fe5aeffc6b564e3e48d7cdb0243cff49c4ad09b5347aa626eec3f

#show: main.with(
  title: "Oblivion - A Vitepress Theme",
  desc: [My new blog debut, with a new theme and a new look.],
  date: "2022-10-16",
  tags: (

    blog-tags.blog,
    blog-tags.theme,
    blog-tags.vitepress,
    blog-tags.vue,
  
  ),
  lang: "en",
  i18nKey: "meta/2022/vitepress-theme-oblivion",
  sourceLang: "zh",
  translationSourceHash: "sha256:02f65745604fe5aeffc6b564e3e48d7cdb0243cff49c4ad09b5347aa626eec3f",
  translationStatus: "machine",
)

The previous theme #link("https://github.com/vuepress-reco/vuepress-theme-reco-1.x")[reco] has been used for quite some time, and recently I became interested in *Vitepress*, which I find quite good, so I had the idea of creating a new theme myself.

= Current Features

- toc
- Katex
- Tags and Collections
- Almost all Markdown features supported by Vitepress's default theme

= Problems Encountered While Adding Various Features

During the development process, I referred to many existing themes, including Vitepress's `default-theme`, #link("https://github.com/vuepress-reco/vuepress-theme-reco-1.x")[reco], #link("https://github.com/clark-cui/vitepress-blog-zaun")[vitepress-blog-zaun], and others.

I encountered many issues, such as the performance of Vue animations on first load, the distinction between SSR and client-side code, and Katex build issues, all of which have been resolved so far.

= Katex

I must say that the addition of Katex brought me quite a bit of trouble; custom tags would throw errors during the build:

#figure(image("/public/assets/img/2022/20220518katex-vitepress-build-error.png"), caption: "Katex Build Error")

I searched for a lot of information but couldn't find the point. In the end, I resolved the issue by adding an item in Vitepress's own configuration file. Add the following content in `.vitepress/config.ts`:

```typescript
// List of custom Tags used by Katex. Reference: [](https://github.com/KaTeX/KaTeX/blob/main/src/mathMLTree.js\#L23)
const mathTags = [
  "math", "annotation", "semantics",
  "mtext", "mn", "mo", "mi", "mspace",
  "mover", "munder", "munderover", "msup", "msub", "msubsup",
  "mfrac", "mroot", "msqrt",
  "mtable", "mtr", "mtd", "mlabeledtr",
  "mrow", "menclose",
  "mstyle", "mpadded", "mphantom", "mglyph"
]

// Add vue field in config
export default {
  vue: {
    template: {
      compilerOptions: {
          isCustomElement: tag => mathTags.includes(tag)
      }
    }
  },
}
```

*Reference Links:*

1. #link("https://github.com/KaTeX/KaTeX/blob/main/src/mathMLTree.js\#L23")[KaTeX]
2. #link("https://github.com/vuejs/vitepress/blob/main/src/node/config.ts\#L44")[Vitepress]

== Server-side Rendering (SSR)

Vitepress uses server-side builds. Although the official documentation states to distinguish between client-side js code and server-side js code as much as possible, in practice, since I had hardly ever dealt with Vue before, I was completely in the dark about the specific implementation methods. After reviewing a lot of information, my solution was that if there was js code that could only be executed on the client side (like the `window` object that only exists in the browser), I would place it in the `onMounted` method.

For example, in the Tags component:

```vue
<script setup lang="ts">
import { useData } from "vitepress"
import { ref, computed, watchEffect, onMounted } from "vue"
import { getStorageTag, getPostsByTag } from "../helpers/tags.ts"
import { getStoragePage } from "../helpers/pagination.ts"

// Set default values, can be executed on the server side
const currentPage = ref(1)
const allPosts = useData().theme.value.posts
const currentTag = ref('')
const postsByTag = computed(() => getPostsByTag(currentTag.value))
const watchFun = ref(() => { })
const show = ref(false)

// Call browser API, only executed on the client side
onMounted(() => {
    currentPage.value = getStoragePage()
    currentTag.value = getStorageTag()

    watchEffect(() => {
        if (window.location.hash) {
            currentTag.value = window.location.hash.replace('#', '');
        }
    })

    show.value = true
})
</script>
```

This avoids the issue of the object not being found during the build process.

== Transition Animation Not Working on First Page Load

After successfully building and running to check the effect, I found that the `transition` effects added to the page did not work when clearing the cache and refreshing the page. After #link("https://stackoverflow.com/questions/59627195/vue-js-transition-doesnt-apply-on-page-first-load")[searching for information], my solution was to add `v-if` to the child elements of each `transition` element, making them default to `false` and not displayed, and then setting them to `true` in `onMounted` to display:

```vue
<template>
  <transition appear enter-active-class="transition ease-out duration-300"
      enter-from-class="transform opacity-0 scale-95" enter-to-class="opacity-100 scale-100">
      <h1 v-if="show">Tags</h1>
  </transition>
</template>

<script setup lang="ts">
  const show = ref(false)
  onMounted(() => {
    show.value = true
  })
</script>
```

This way, even on the first visit to the page, the animation effect will be present.

= Next Steps to Add Features

The current features can only be said to meet basic writing needs, but the types are not rich enough and are still quite general. The next step is to implement more features:

1. *Timeline* - This goes without saying, it’s like a Facebook timeline, for reviewing oneself.
2. *Contribution Heatmap* - Just like the GitHub contribution graph, I plan to implement one using svg.
3. *Weibo* - To conveniently record some content, currently the idea is to add a new category to existing articles, with a structure completely consistent with normal articles, and further ideas will be discussed later.

= For Those Who Want to Use It

If anyone wants to try using this theme, just copy the content of #link("https://github.com/dyzdyz010/vitepress-theme-oblivion")[vitepress-theme-oblivion] to their own repository to build and publish. You can also refer to my Pages repository #link("https://github.com/dyzdyz010/dyzdyz010.github.io")[dyzdyz010.github.io]. If you have any questions, feel free to raise an Issue.
