#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2017/logistic-regression-with-tensorflow.typ
// source_sha256: sha256:302fb097ae1918ef6b578e664f01e68a9d0267743119c802111f20b0da4d6aa4

#show: main.with(
  title: "Building a Simple Logistic Regression Model with TensorFlow from Scratch",
  desc: [Building a Simple Logistic Regression Model with TensorFlow from Scratch],
  date: "2017-06-28",
  tags: (

    blog-tags.ml,
    blog-tags.python,
    blog-tags.tensorflow,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "tutorials/2017/logistic-regression-with-tensorflow",
  sourceLang: "zh",
  translationSourceHash: "sha256:302fb097ae1918ef6b578e664f01e68a9d0267743119c802111f20b0da4d6aa4",
  translationStatus: "machine",
)

TensorFlow is a machine learning framework based on Python. After taking a course on logistic regression on Coursera, I wanted to reimplement what I had done in MATLAB using TensorFlow as a stepping stone to learn Python and the framework.

== Target Audience
Those who know what logistic regression is, understand a bit of Python, and have heard of TensorFlow.

== Dataset

From Andrew's machine learning course on Coursera, `ex2data1.txt`, which determines whether a student will be admitted based on their scores in two exams.

== Environment

Python 2.7 - 3.x

pandas, matplotlib, numpy

== Installing TensorFlow

Install the TensorFlow framework on your own computer. The installation process will not be elaborated here; the CPU version is relatively easier, while the GPU version requires CUDA support. Please install according to your situation.

== Getting Started

Create a folder (let's call it `tensorflow`), create a Python file `main.py` in that folder, and place the dataset file in this folder:

// Image: Creating Directory Structure (https://ws4.sinaimg.cn/large/006tKfTcly1fgzhzjoe5mj30fg042dfz.jpg)

Data format:

// Image: Data Screenshot (https://ws2.sinaimg.cn/large/006tKfTcly1fgzv7030poj30j407q75z.jpg)

The first two columns are the scores from the two exams (x1, x2), and the last column indicates whether the student was admitted (y), where `1` means admitted and `0` means not admitted.

In the source file `main.py`, we first import the necessary packages:

```python
import pandas as pd                # For reading data files
import tensorflow as tf
import matplotlib.pyplot as plt    # For plotting
import numpy as np                 # For subsequent calculations
```

`pandas` is a data processing package that can read datasets and perform various operations; `matplotlib` can be used to visualize our dataset in charts.

Next, we read the dataset file into the program for training:

```python
# Read data file
df = pd.read_csv("ex2data1.txt", header=None)
train_data = df.values
```

The `pandas` function `read_csv` can read data from a CSV (comma-separated values) file into the `df` variable, and `df.values` converts the DataFrame into a two-dimensional array:

// Image: DataFrame Data (https://ws3.sinaimg.cn/large/006tKfTcly1fgzvpetjf7j30me0a4myp.jpg)

With the data in hand, we need to separate the features (x1, x2) and labels (y) into two variables for use in training:

```python
# Separate features and labels, and get data dimensions
train_X = train_data[:, :-1]
train_y = train_data[:, -1:]
feature_num = len(train_X[0])
sample_num = len(train_X)
print("Size of train_X: {}x{}".format(sample_num, feature_num))
print("Size of train_y: {}x{}".format(len(train_y), len(train_y[0])))
```

// Image: Data Dimensions Output (https://ws1.sinaimg.cn/large/006tKfTcly1fgzvtaekpuj309c01k0st.jpg)

As we can see, our dataset contains 100 samples, each with 2 features.

== TensorFlow Model Design

In logistic regression, the prediction function (Hypothesis) we use is:

$ h_theta (x) = "sigmoid"(X W + b) $

where `sigmoid` is an `activation function`, representing the probability of a student being admitted:

$ P(y = 1 | x, theta) $

The shape of this function can be found by #link("https://en.wikipedia.org/wiki/Sigmoid_function")[searching online].

`W` and `b` are our learning targets; W is the weight matrix (Weights), and b is the bias (Bias, also known as the intercept in graphs).

The loss function we use is:

$ J(theta) = -frac(1, m) lr([ sum_(i=1)^m y^((i)) log(h_theta (x^((i)))) + (1 - y^((i))) log(1 - h_theta (x^((i)))) ]) $

Since our dataset only has two features, we don't need to worry about overfitting, so we can omit the regularization term in the loss function.

First, we define two variables in TensorFlow to store our training data:

```python
# Dataset
X = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
```

Here, X and y are not ordinary variables, but `placeholders`, meaning that the values of these variables are unspecified until you start training the model and assign the given data to the variables.

Next, we define our training targets `W` and `b`:

```python
# Training targets
W = tf.Variable(tf.zeros([feature_num, 1]))
b = tf.Variable([-.9])
```

Here, their type is `Variable`, meaning these two variables will change continuously during the training iterations, ultimately achieving the values we expect. We can see that we set the initial value of `W` to a zero vector of dimension `feature_num`, and the initial value of `b` to `-0.9` (arbitrarily chosen, no need to mind).

Next, we express the loss function in TensorFlow:

```python
db = tf.matmul(X, tf.reshape(W, [-1, 1])) + b
hyp = tf.sigmoid(db)

cost0 = y \* tf.log(hyp)
cost1 = (1 - y) \* tf.log(1 - hyp)
cost = (cost0 + cost1) / -sample_num
loss = tf.reduce_sum(cost)
```

As we can see, I express the loss function in three steps: first, I represent the two parts inside the summation separately, then sum them up and perform operations with the outer constant `m`, and finally sum this vector to obtain the value of the loss function.

Next, we need to define the optimization method we will use:

```python
optimizer = tf.train.GradientDescentOptimizer(0.001)
train = optimizer.minimize(loss)
```

Here, the first step is to select the optimizer; we choose the gradient descent method. The second step is the optimization target, which, as the function name suggests, is to minimize the value of the loss function.

*`Note`*: The learning rate (0.001) here should be as small as possible; otherwise, you may encounter #link("https://stackoverflow.com/questions/35106101/why-does-my-tensorflow-convnet-attempted-training-result-in-nan-gradients")[issues with log(0) during loss calculation].

== Training

After completing the above work, we can start training our model.

In TensorFlow, we first need to initialize the previously defined `Variables`:

```python
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
```

Here, we see the appearance of `tf.Session()`, which, as the name suggests, is a `session`, the main body for executing tasks. The definitions we made above are just a model that requires execution steps and framework to obtain results, similar to a `flowchart`. Having just a flowchart is not enough; we need a body to actually run it, which is the role of `Session`.

=== Special Reminder

If you are using the GPU version of TensorFlow and want to train the model while the GPU is highly utilized (e.g., while gaming), you need to pay attention to #link("https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory/34200194")[allocating a fixed amount of GPU memory] when initializing the `Session`, otherwise you may encounter errors when starting the training:

```
2017-06-27 20:39:21.955486: E ... tensorflow ... CUBLAS_STATUS_ALLOC_FAILED
...
tensorflow.python.framework.errors_impl.InternalError: Blas GEMV launch failed:  m=2, n=100
```

In this case, you need to create the `Session` using the following method:

```python
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
```

Here, `0.333` is the fraction of your total GPU memory.

Next, we will train the model using our dataset:

```python
feed_dict = {X: train_X, y: train_y}

for step in range(1000000):
    sess.run(train, {X: train_X, y: train_y})
    if step % 100 == 0:
        print(step, sess.run(W).flatten(), sess.run(b).flatten())
```

First, we store the data to be fed into a variable, which is passed into `sess.run()` during model training; we perform 10000 training iterations, outputting the current target parameters `W, b` every 100 iterations.

At this point, the training code section is complete, and you can run it using your own Python command. If you followed the code strictly without errors, you should see the console continuously outputting the training status:

// Image: Training Process (https://ws1.sinaimg.cn/large/006tKfTcly1fh0l0l38ttj30kv0cv0w6.jpg)

== Visualizing Results

When the training is complete, you will obtain a `W` and a `b`, allowing us to visually present the dataset and the fitted results through charts.

While writing this, I trained a result using the above code:

// Image: Training Results (https://ws1.sinaimg.cn/large/006tKfTcly1fh0l0w2j86j30l3011dfu.jpg)

We can directly write it into the code as:

```python
w = [0.12888144, 0.12310864]
b = -15.47322273
```

Next, we will first represent the dataset on the chart (x1 on the horizontal axis, x2 on the vertical axis):

```python
x1 = train_data[:, 0]
x2 = train_data[:, 1]
y = train_data[:, -1:]

for x1p, x2p, yp in zip(x1, x2, y):
    if yp == 0:
        plt.scatter(x1p, x2p, marker='x', c='r')
    else:
        plt.scatter(x1p, x2p, marker='o', c='g')
```

Here, we use `red x` to represent `not admitted` and `green o` to represent `admitted`.

Next, we will represent the decision boundary obtained from training `XW + b = 0` on the chart:

```python
# Get the line based on parameters
x = np.linspace(20, 100, 10)
y = []
for i in x:
    y.append((i \* -w[1] - b) / w[0])

plt.plot(x, y)
plt.show()
```

At this point, if your code is correct, running it again will yield the following result:

// Image: Fitting Results (https://ws2.sinaimg.cn/large/006tKfTcly1fh0l1ktu4kj30m80iwmyq.jpg)

As we can see, the parameters obtained from training draw a line that effectively separates the two different data samples.

Thus, a complete and simple logistic regression model has been implemented. I hope this article provides readers with a preliminary understanding of implementing machine learning models in `TensorFlow`. I am also in the early stages of learning, so if there are any inaccuracies, feel free to leave comments. If you encounter any issues while implementing the above code, please feel free to discuss in the comments.
