#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-5
// source: content/article/en/meta/2026/bilingual-blog.typ
// source_sha256: sha256:ec490396c942342fa5a9d6158a8d2a4ffa4bffeed8418709b4dd521051319075

#show: main.with(
  title: "博客现在会说两种语言",
  desc: [博客现在支持双语文章和 AI 辅助翻译。],
  date: "2026-05-25",
  tags: (

    blog-tags.blog,
    blog-tags.typst,
    blog-tags.software,
  
  ),
  lang: "zh",
  i18nKey: "meta/2026/bilingual-blog",
  sourceLang: "en",
  translationSourceHash: "sha256:ec490396c942342fa5a9d6158a8d2a4ffa4bffeed8418709b4dd521051319075",
  translationStatus: "machine",
)

最近我终于给博客加上了双语支持。

现在站点同时有英文和中文的路由。文章不再只对应一种语言。我用英文写点什么时，博客可以生成中文版本；我用中文写时，它可以生成英文版本。这两份文件仍然是普通的 Typst 源文件，因此可以像站点的其他部分一样提交、评审、编辑并重新构建。

= 为什么

主要原因很简单：我希望有更多人能读到同样的内容。

个人博客往往首先是写给自己的，但它仍然发布在开放的网络上。如果一篇文章只有一种语言，很多读者就会直接略过，并非因为话题无用，而是因为进入门槛太高。双语文章能把这个门槛稍微降一点。

现在的 AI 翻译已经足够好，使这件事变得可行。它未必总是完美，但能很快产出可用的一稿。之后，如果我在意这篇文章，我可以审校译文；如果没时间，也可以明确标注为机器翻译。

= 工作原理

这不是运行时翻译。

当有人打开页面时，博客不会调用任何 API。相反，翻译是在构建阶段进行的源码生成步骤。脚本读取原始的 Typst 文件，让模型翻译散文性内容，保留代码块、链接、路径、数学公式和 Typst 命令，然后在另一种语言环境下写出另一个 `.typ` 文件。

因此，最终的网站仍然只是一个正常的“准静态”博客。Cloudflare 不需要 OpenAI 密钥。读者不必等待翻译请求。搜索引擎能看到真正的本地化页面。而且如果我不喜欢生成的结果，我可以直接改。

= 源文、机器、已审阅

每篇文章都有一个小小的翻译状态。

- `source` 表示这是人写的原稿。
- `machine` 表示这个文件由 AI 生成。
- `reviewed` 表示我已检查过，不希望脚本轻易覆盖。

我也把 `source` 设为默认值，因为未来的我早晚会忘记填某个字段。

= 折腾仍在继续

当一切正常时，这次更新大多是不可见的。主页仍然像主页，文章仍然像文章，归档仍然是归档。但在幕后，内容模型现在更完整了一点。

这更像是一处小小的基础设施改动，但它改变了谁能读到这个站点。值得。

*折腾永无止境。*
