#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/en/tutorials/2021/rhel-8-with-sas2008-raid-controllers.typ
// source_sha256: sha256:d4a4d69968c95025fdcb04ec67662219f8116eb7890baa1a88fc2e66a6ddddda

#show: main.with(
  title: "使用 SAS 2008 RAID 控制器安装 RHEL 8",
  desc: [使用 SAS 2008 RAID 控制器安装 RHEL 8],
  date: "2021-01-03",
  tags: (

    blog-tags.linux,
  
  ),
  lang: "zh",
  i18nKey: "tutorials/2021/rhel-8-with-sas2008-raid-controllers",
  sourceLang: "en",
  translationSourceHash: "sha256:d4a4d69968c95025fdcb04ec67662219f8116eb7890baa1a88fc2e66a6ddddda",
  translationStatus: "machine",
)

参考: #link("https://gainanov.pro/eng-blog/linux/rhel8-install-to-dell-raid/")[RHEL8. 在 DELL 服务器上安装 RAID (SAS2008) 由 Ruslan Gainanov]

在 RHEL 8 中，许多硬件驱动程序被 #link("https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/considerations_in_adopting_rhel_8/hardware-enablement_considerations-in-adopting-rhel-8#removed-adapters_hardware-enablement")[移除]，包括我正在使用的 `SAS 2008 RAID 总线控制器`。我尝试在我的机器上安装 RHEL 8，但在 `安装目标` 部分只得到了一个 *空* 的可用磁盘列表。

要安装操作系统，我们需要获取该硬件的驱动程序，幸运的是，我们从 #link("https://elrepo.org/linux/dud/el8/x86_64/")[ELRepo] 获得了 DUD（驱动程序更新磁盘），因此我们可以从那里获取缺失的驱动程序。接下来，我将向您展示我是如何在我的服务器上使用 SAS 2008 RAID 控制器安装 RHEL 8 的。

= 确定设备 ID

首先，我们需要确定我硬件的设备 ID。当进入安装程序 GUI 时，通过 `Ctrl + Alt + F2` 获取一个 shell，输入以下命令：

```
lspci -nn
```

您可能想用一些关键字过滤，以使输出更干净易读。这是我得到的：

#figure(image("/public/assets/img/2021/01/photo_2021-01-04_18-29-35.jpg"), caption: "lspci 输出")

所以我正在寻找的设备是：

```
05:00.0 RAID 总线控制器 [0104]: Broadcom / LSI MegaRAID SAS 2008 [Falcon] [1000:0073] (rev 03)
```

这个硬件的设备 ID 是 `1000:0073`。

= 获取驱动程序

现在我们需要去 #link("http://elrepo.org/tiki/DeviceIDs")[设备 ID 配对] 页面获取驱动程序名称。在这种情况下，我的驱动程序是 `megaraid_sas`。

访问 #link("https://elrepo.org/linux/dud/el8/x86_64/")[DUD 列表页面]，按名称查找驱动程序：

#figure(image("/public/assets/img/2021/01/202101041837.png"), caption: "DUD 列表页面")

我正在安装 RHEL 8.3，所以我将使用最后一个匹配项：`dd-megaraid_sas-07.714.04.00-1.el8_3.elrepo.iso`。

按照 #link("https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/updating-drivers-during-installation_installing-rhel-as-an-experienced-user")[RedHat 的文档] 了解如何使用此驱动程序。在我的情况下，我只是将 `iso` 文件复制到另一个 USB 驱动器。

= 修补驱动程序

我将展示我所做的事情，完整的使用文档请查看上面的 `RedHat 链接`。

使用 BIOS 运行安装过程（我没有找到可以按 `Tab` 键的 UEFI 启动窗口），然后按 `Tab`：

#figure(image("/public/assets/img/2021/01/boot-menu.png"), caption: "启动菜单")

在底部的命令中，附加 `inst.dd` 选项并按 `Enter`。

按照交互提示选择要安装的驱动程序。当您完成后，您将进入正常的安装 GUI。

现在转到 `安装目标` 部分，您会发现您的磁盘显示出来了！

#figure(image("/public/assets/img/2021/01/destination-with-raid.png"), caption: "带 RAID 的安装目标")

现在您可以进入正常的安装过程。当安装完成并重启系统时，该驱动程序将包含在您刚刚安装的系统中。享受吧
