#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/meta/2017/wonderland-ghost-theme.typ
// source_sha256: sha256:1939bc498d9c6633d7cb1c44ef34d8c186332debb5366cd9dba53ef277cb8871

#show: main.with(
  title: "Wonderland - A Simple and Clean Ghost Theme",
  desc: [Introduction to the Wonderland Ghost Theme],
  date: "2017-08-01",
  tags: (

    blog-tags.ghost,
    blog-tags.blog,
    blog-tags.theme,
  
  ),
  lang: "en",
  i18nKey: "meta/2017/wonderland-ghost-theme",
  sourceLang: "zh",
  translationSourceHash: "sha256:1939bc498d9c6633d7cb1c44ef34d8c186332debb5366cd9dba53ef277cb8871",
  translationStatus: "machine",
)

Inspired by a friend, this is implemented as a Ghost theme. The current features include:

+ Home page
+ Article page
+ Tag archive page

Friends who like it are welcome to download and use it, and it would be even better to give it a star.

Project address: #link("https://github.com/dyzdyz010/wonderland")[Wonderland]

Theme screenshot:

#link("https://ww1.sinaimg.cn/large/006tNc79gy1fi4d6cm2fij31kw0zkgvj.jpg")[Home screenshot]

#link("https://camo.githubusercontent.com/07e148ba56aa768d5be263de1ab498d38429661b/68747470733a2f2f7777342e73696e61696d672e636e2f6c617267652f303036744e6337396779316669346436636d32666a6a33316b77307a6b67766a2e6a7067")[Theme preview]
