#let blog-tags = (
  programming: "Programming",
  software: "Software",
  network: "Network",
  software-engineering: "Software Engineering",
  tooling: "Tooling",
  linux: "Linux",
  dev-ops: "DevOps",
  compiler: "Compiler",
  music-theory: "Music Theory",
  tinymist: "Tinymist",
  golang: "Golang",
  typst: "Typst",
  life: "Life",
  misc: "Miscellaneous",
  ue5: "UE5",
  protobuf: "Protobuf",
  cloudflare: "Cloudflare",
  astro: "Astro",
  blog: "Blog",
  theme: "Theme",
  vue: "Vue",
  vitepress: "Vitepress",
)

#let blog-collections = (
  blog: "Blog",
  project: "Project",
  note: "Note",
)
