#let blog-tags = (
  programming: "Programming",
  software: "Software",
  network: "Network",
  software-engineering: "Software Engineering",
  tooling: "Tooling",
  linux: "Linux",
  dev-ops: "DevOps",
  compiler: "Compiler",
  music-theory: "Music Theory",
  tinymist: "Tinymist",
  golang: "Golang",
  typst: "Typst",
  life: "Life",
  misc: "Miscellaneous",
  ue5: "UE5",
  protobuf: "Protobuf",
  cloudflare: "Cloudflare",
  astro: "Astro",
  blog: "Blog",
  theme: "Theme",
  vue: "Vue",
  vitepress: "Vitepress",
  mmo: "MMO",
  server: "Server",
  rust: "Rust",
  game: "Game",
  elixir: "Elixir",
  erlang: "Erlang",
  ffmpeg: "FFmpeg",
  frontend: "Frontend",
  clang: "Clang",
  ml: "Machine Learning",
  python: "Python",
  redis: "Redis",
  tensorflow: "TensorFlow",
  algorithm: "Algorithm",
  apple: "Apple",
  ghost: "Ghost",
  windows: "Windows",
  wsl: "WSL",
  git: "Git",
  notion: "Notion",
  emacs: "Emacs",
  haskell: "Haskell",
)

#let blog-collections = (
  blog: "Blog",
  project: "Project",
  note: "Note",
)
