#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2022/elixir-otp-quickstart.typ
// source_sha256: sha256:9538cad7b15e5325bcf84e4fd6791748f098f9372d1219a1ebe5c7aeb98d4f51

#show: main.with(
  title: "Simple Practice with Elixir+OTP",
  desc: [Here, we look at a complete example developed using Elixir and OTP, which implements a simple counter server.],
  date: "2022-12-27",
  tags: (

    blog-tags.elixir,
    blog-tags.server,
  
  ),
  lang: "en",
  i18nKey: "tutorials/2022/elixir-otp-quickstart",
  sourceLang: "zh",
  translationSourceHash: "sha256:9538cad7b15e5325bcf84e4fd6791748f098f9372d1219a1ebe5c7aeb98d4f51",
  translationStatus: "machine",
)

Here, we look at a complete example developed using Elixir and OTP, which implements a simple counter server.

First, we need to create a new Elixir project. We can use the `mix` command to create the project:

```elixir
mix new counter
```

This will create a new project named `counter` and generate some initial files.

Next, we need to create a module to manage the counter's state. This module will use the `GenServer` module to manage the state. We can create a new module file in the project's `lib` directory, for example, `lib/counter.ex`, and write the following code:

```elixir
defmodule Counter do
  use GenServer

  def start_link(initial_count) do
    GenServer.start_link(__MODULE__, initial_count)
  end

  def increment(pid) do
    GenServer.call(pid, :increment)
  end

  def get(pid) do
    GenServer.call(pid, :get)
  end

  def init(initial_count) do
    {:ok, initial_count}
  end

  def handle_call(:increment, _from, count) do 
    {:reply, :ok, count + 1}
  end

  def handle_call(:get, _from, count) do
    {:reply, count, count} 
  end
end
```

Here, we created a module named `Counter` and used the `GenServer` module to manage the state. We defined three functions: `start_link/1` to start a new counter process, `increment/1` to increment the counter's value by 1, and `get/1` to retrieve the current value of the counter. We also defined two handling functions: `handle_call/3` to handle calls from clients and `init/1` to initialize the counter's state. Next, we can use this module to create new counter processes and use the `increment/1` and `get/1` functions to operate the counter. For example, we can run the following code in `iex` to create a new counter process and use it to count:

```elixir
iex> pid = Counter.start_link(0)
{:ok, #PID<0.119.0>}
iex> Counter.increment(pid) 
:ok 
iex> Counter.get(pid) 
1 
iex> Counter.increment(pid) 
:ok 
iex> Counter.get(pid)
2
```

In this example, we created a new counter process and used the `increment/1` function twice to increment the counter's value by 1. Then, we used the `get/1` function twice to retrieve the current counter value, finding that it has become 2.

This is a complete example of a simple counter server developed using Elixir and OTP. By using the modules and tools provided by OTP, we can build maintainable server-side programs more quickly and efficiently.
