#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2022/setup-elixir-development-environment.typ
// source_sha256: sha256:419e96e0d9e97dee5b2e3ef806df54629cb076882f8f515bbd790ec4cb96b159

#show: main.with(
  title: "Setting Up the Elixir Development Environment",
  desc: [This article is generally applicable to Linux, WSL, and macOS.],
  date: "2022-12-27",
  tags: (

    blog-tags.elixir,
    blog-tags.tooling,
  
  ),
  lang: "en",
  i18nKey: "tutorials/2022/setup-elixir-development-environment",
  sourceLang: "zh",
  translationSourceHash: "sha256:419e96e0d9e97dee5b2e3ef806df54629cb076882f8f515bbd790ec4cb96b159",
  translationStatus: "machine",
)

*This article is generally applicable to Linux, WSL, and macOS.*

= 1. Installing Elixir

Since Elixir runs on top of the Erlang runtime environment, installing Elixir also requires installing Erlang.

Here we can choose which package manager to use for installation. Generally, `Homebrew` is sufficient, as it can automatically install its dependencies, including Erlang, when installing Elixir:

```bash
brew install elixir
```

This will install the latest version of Elixir.

Another method is through #link("https://asdf-vm.com/")[Home | asdf (asdf-vm.com)]. `asdf` is a version manager that can install specific versions of software to maintain a stable development environment, unlike `Homebrew`, which automatically updates software versions whenever it is updated, potentially breaking the development environment.

With `asdf`, you first need to add the corresponding software library, starting with `Erlang`:

```bash
asdf plugin add erlang
```

Then install a specific version:

```bash
asdf install erlang 25.1.1
```

This way, `asdf` will pull the specified version for compilation and installation.

After `Erlang` is installed, continue with the installation of `Elixir`:

```bash
asdf plugin add elixir
asdf install elixir 1.14.1
```

Now `Elixir` is installed. We can use the `iex` command to check if the installation is successful.

= 2. Configuring the Code Editor

I prefer using VSCode as my editor because it has a rich variety of plugins that can make the editor both visually appealing and user-friendly.

In VSCode, we only need one plugin: `ElixirLS`, which is an implementation of the `Elixir` LSP (Language Server Protocol).

ElixirLS provides features such as syntax highlighting, code suggestions, auto-completion, and code navigation. These features can help us write code faster and avoid errors.

Additionally, ElixirLS offers code checking capabilities that can help us identify errors and potential issues in our code. It displays error messages in the editor and provides suggestions for fixes.

ElixirLS also supports running, debugging, and testing parts of Elixir. For example, we can use ElixirLS to run Elixir scripts or debug Elixir applications.

The editor configuration is complete. Let's write a Hello world. Enter the `iex` interactive environment:

```bash
iex> IO.puts "Hello, World!" 
Hello, World! 
:ok
```
