#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/tutorials/2022/ue5-protobuf.typ
// source_sha256: sha256:3a570c38c7a0eb7c9dd5730e0b4d812b6e267f5f93981b0a4b234250fd2a08ac

#show: main.with(
  title: "Integrating Protobuf into UE5 Projects",
  desc: [Integrating Protobuf into UE5 Projects],
  date: "2022-10-13",
  tags: (

    blog-tags.programming,
    blog-tags.ue5,
    blog-tags.protobuf,
  
  ),
  lang: "en",
  i18nKey: "tutorials/2022/ue5-protobuf",
  sourceLang: "zh",
  translationSourceHash: "sha256:3a570c38c7a0eb7c9dd5730e0b4d812b6e267f5f93981b0a4b234250fd2a08ac",
  translationStatus: "machine",
)

*Unreal Engine Version: 5.0.3*

*Protobuf Version: 21.7*

#quote(block: true)[
  As someone who doesn't understand C++, integrating a C++ library into UE is truly a torment.

  —— Wozki Shode
]

#link("https://www.bilibili.com/video/BV1j54y1G7wE/")[The tutorial on Bilibili] is very detailed, from creating the plugin to importing the `Protobuf` source code. If you strictly follow his method, the final result *should* be usable. However, I encountered problems during the process:

There is a step in the video where the `Protobuf` source code is copied to the plugin code directory, but from the file list in the video, it is clear that it does not completely match the official source code. I tried placing the official source code intact into the plugin, but the compilation failed;

I paused the video, used the file list from the video to delete the extra official source files, and then placed them into the plugin. The plugin itself compiled successfully, but once I generated `C++` files from the `proto` files and included them in the game code, the compilation reported a bunch of errors.

After consulting numerous resources, I found that there are almost no recent tutorials or code repositories that are still being updated, and most have lost their reference value. Eventually, I found #link("https://gitee.com/love_linger/UE4Protobuf/blob/master/Protobuf.Build.cs")[this code]. The author in the code used the method of `importing precompiled library files` to achieve the integration of `Protobuf`, which gave me an idea. The precompiled library files can be compiled from the official source code, and I only need to include the complete header files. Therefore, I did the following work:

= Compile the required include files and library files from the official source code

Download the source code from #link("https://github.com/protocolbuffers/protobuf/releases")[the official GitHub repository]. At the time of writing this article, the latest *Release* is `21.7`. When downloading, choose the C++ compressed package:

#figure(image("/public/assets/img/2022/20221012_proto_source_download.png"), caption: "Download Source Code")

After downloading, unzip it and compile and install according to the official `README` instructions. At that time, I used `CMake + VS2019` to obtain the final include files and library files:

#figure(image("/public/assets/img/2022/20221012_proto_build_result.png"), caption: "Proto Source Compilation Result")

- The `include` folder contains the header files to be included
- The `lib` folder contains the compiled `.lib` library files, I only used `libprotobuf.lib`
- The `bin` folder contains the executable program `protoc.exe` for converting `.proto` files

= Integrate the compilation results into the UE5 plugin

So the things that need to be copied are as follows (to keep the file structure tidy):

- `include` folder
- `lib/libprotobuf.lib`
- `bin/protoc.exe`

Place these three items in the plugin directory. My plugin is named `SimpleProto5`, and I placed it under `Plugins/Source/SimpleProto5/ThirdParty/probuf`:

#figure(image("/public/assets/img/2022/20221012_proto_plugin_structure.png"), caption: "Placement Path")

After placing the files, the `.Build.cs` file of the plugin also needs to be modified to add the header file include paths and library file search paths:

```cs
// Header file include paths
PublicSystemIncludePaths.AddRange(
  new string[]
  {
    Path.Combine(ThridPartyPath, "protobuf/include")
  }
);

// Library file include paths
PublicAdditionalLibraries.Add(Path.Combine(ThridPartyPath, "protobuf", "lib", "Win64", "libprotobuf.lib"));
```

The library file path writing is temporary because my goal is to support more than just the `Windows` platform, so I can add different library file paths for different platforms later.

= Subsequent Operations

You can choose to continue following the video to complete this plugin, but the process of introducing `Protobuf` ends here. Friends following the article can compile the project to see if there are no other issues; the project should compile normally.

If the following error occurs during compilation:

```text
inlined_string_field.h(430): [C4668] “GOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE” is not defined as a preprocessor macro, replacing “#if/#elif” with “0”
```

You only need to locate line 430 of the `inlined_string_field.h` file based on the error and change `#if` to `#ifdef`.

I wish everyone a great time playing with `Protobuf` in `UE5`!
