#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by Hermes Agent from the zh source
// prompt_version: wonderland-manual-i18n-v1
// source: content/article/zh/life/2026/lightweight-spatial-computing.typ
// source_sha256: sha256:b205cadba1114a500c293cbac0da02d8c24cabd5053bb6265bc27983122c420f

#show: main.with(
  title: "Lightweight hardware is not all of spatial computing",
  desc: [Lightweight glasses may become the high-frequency entry point, but heavier MR/VR devices still define the ceiling of spatial computing.],
  date: "2026-06-06",
  tags: (
    blog-tags.apple,
    blog-tags.software,
    blog-tags.misc,
  ),
  lang: "en",
  i18nKey: "life/2026/lightweight-spatial-computing",
  sourceLang: "zh",
  aiAuthored: true,
  translationSourceHash: "sha256:b205cadba1114a500c293cbac0da02d8c24cabd5053bb6265bc27983122c420f",
  translationStatus: "machine",
)

#quote(block: true)[
  If spatial computing ends up as nothing more than a tiny notification screen in front of your eyes, it may not be the future. It may be the future cut down into a sticky note.

  ——Wozky Shuo-De
]

The recent news around Vision Pro has been increasingly awkward.

On one side, Apple is still maintaining visionOS#footnote[Apple still presents visionOS as its own developer platform; see the Apple Developer #link("https://developer.apple.com/visionos/")[visionOS page].]. On the other, more and more rumors suggest that Apple is shifting its attention toward devices that are lighter, more everyday, and more like glasses#footnote[For the Vision Pro roadmap rumor context, see MacRumors' write-up of #link("https://www.macrumors.com/2024/06/18/apple-suspends-work-on-vision-pro-2/")[The Information's report] and its continuously updated #link("https://www.macrumors.com/roundup/apple-vision-pro/")[Apple Vision Pro roundup].]. So a lot of people have reached a very simple conclusion: headsets are too heavy, so the future must be lightweight glasses; Vision Pro failed, so heavy spatial computing devices should be abandoned.

I think that conclusion is dangerous.

Lightness matters, of course. Nobody wants to wear something heavy on their head every day. But lightness should not become the only correct direction for the entire industry. More precisely, lightness solves the problem of wearing frequency. It does not solve the problem of content ceiling.

Those are not the same problem.

= Lightweight glasses solve the "quick glance" problem

What are lightweight glasses best at?

Simply put, they are good for things that only need a quick glance.

For example:

- message notifications
- navigation arrows
- live translation
- photos and video
- AI assistant prompts
- simple AR annotations

These things are valuable, and they may become a very high-frequency entry point in the future. Like Apple Watch and AirPods, they do not need to carry a complete computing experience. They only need to put the right piece of information near the user at the right moment.

But that is also where the problem begins.

If spatial computing is eventually understood as "put phone notifications on glasses", its imagination will be compressed dramatically. We have spent years working on VR, AR, MR, spatial interaction, hand tracking, eye tracking, occlusion, spatial audio, and digital twins. Was all of that just to display a WeChat notification in front of your eyes?

Clearly not.

= Heavy content needs a heavy entry point

By heavy content, I do not mean that the content itself must be clumsy. I mean that it needs a larger display area, more compute, fuller spatial perception, and a more complex interaction system.

For example:

- huge VR scenes
- fully immersive games
- police, medical, and industrial training
- multi-user spatial collaboration
- complex digital twin systems
- high-precision 3D creation
- MR board games and spatial storytelling
- mixed-reality applications that require real occlusion

These are not problems that lightweight glasses can solve by showing a small hint.

A transparent display with a small field of view can tell you to turn left ahead, but it can hardly let you enter a complete virtual city. It can mark a point on a table, but it will struggle to support a large MR board game with spatial mapping, object occlusion, real hand interaction, virtual characters, and multiplayer sync. It can show a line of instructions next to a factory machine, but it can hardly carry a full immersive training system.

Phones can play movies, but cinemas did not become meaningless. Watches can show notifications, but computers were not replaced. Earbuds can play a voice assistant, but workstations still need GPUs and large screens.

Different devices solve different levels of problems.

If the industry puts all of its resources into lightweight glasses, spatial computing will be downgraded into an "in-front-of-your-eyes small screen" industry.

That is a bad trend.

= Lightness is not free

In many current discussions, lightness is treated as a cost-free virtue. If something is lighter, it must be more advanced. If it looks more like ordinary glasses, it must be closer to the future.

But in hardware, there is no free lunch.

Making a device lighter usually means sacrificing something:

- display area
- field of view
- battery capacity
- local compute
- thermal headroom
- sensor count
- interaction complexity
- full immersion

Yes, some of this can be patched with cloud rendering, phone-assisted compute, external compute pucks, or edge computing. But those solutions introduce latency, networking, power, reliability, and privacy problems.

So I am not against lightness. I am against turning lightness into a sacred answer.

Lightness is an engineering tradeoff, not a final answer.

= Vision Pro's problem is not "weight". It is positioning.

Vision Pro's biggest problem may not be that the device is too heavy. It may be that Apple placed it in a very awkward position.

It looks much more like a high-end spatial computing workstation, development machine, experimental platform, and enterprise demo device. But Apple packaged it as a next-generation everyday computing device that ordinary consumers were supposed to buy.

That creates a mismatch of expectations.

If you treat it as a consumer product, then yes, it is too expensive, too heavy, too light on content, and not frequent enough in daily use.

But if you treat it as a high-fidelity MR prototyping platform, it is very valuable. It has good passthrough, eye-and-hand interaction, spatial windows, immersive environments, RealityKit, Unity PolySpatial#footnote[This refers to the development stack around Apple #link("https://developer.apple.com/augmented-reality/realitykit/")[RealityKit] and Unity's #link("https://docs.unity3d.com/Packages/com.unity.polyspatial.visionos@latest")[PolySpatial visionOS package documentation].], and a complete software system. For research, education, training, demos, and spatial interaction validation, it is not a meaningless product.

So the question should not be:

#quote(block: true)[
  Vision Pro failed, therefore heavy devices have no future.
]

It should be:

#quote(block: true)[
  Vision Pro was positioned incorrectly, so it did not become a mass-market consumer product.
]

Those are two completely different judgments.

If Apple is smart, it should not simply cut off the heavy-device path. It should reposition it.

A more reasonable split would be:

- Vision Pro / Vision handles high-fidelity spatial computing for professional creation, enterprise training, research prototypes, immersive entertainment, and complex 3D content.
- Apple Glass / AI Glass handles everyday wear for notifications, AI assistance, translation, navigation, capture, and lightweight AR.

One is for "entering into it". The other is for "glancing at it".

That is a complete spatial computing product spectrum.

= Spatial computing should not have only one device form

I prefer to divide future spatial computing devices into three layers.

The first layer is lightweight glasses.

They handle high-frequency, low-load, fragmented information interaction. They should be as light, natural, and unobtrusive as possible. Their keyword is always available.

The second layer is MR headsets.

They handle medium-to-high intensity spatial applications, such as work, education, training, design, desktop-class MR games, and mixed physical-virtual demos. They do not need to be worn ten hours a day. But when needed, they should provide enough spatial capability. Their keyword is spatial workstation.

The third layer is heavy VR or professional immersive systems.

They handle content with the highest immersion, complexity, and compute demand: large simulations, professional training, immersive games, virtual production, and complex digital twins. Their keyword is full immersion.

These three layers do not replace each other. They complement each other.

A healthy ecosystem should not require everything to become glasses. We do not require every computing device to become a phone either.

= A rush toward lightness may kill the content ceiling

What worries me most is not that lightweight glasses will succeed.

They certainly can succeed. They probably will.

What worries me is that after they succeed, the whole industry may start to believe that "spatial computing means lightweight glasses". Then every content design will begin compromising toward the smallest display area, lowest interaction density, and shortest attention span.

At that point, spatial computing becomes another branch of the mobile internet:

- shorter content
- shallower interaction
- more fragmented attention
- lower information density

Instead of a new medium that can carry complex spatial experiences.

That would be a shame.

The most valuable part of MR / VR is not moving a phone screen in front of your eyes. It is creating spatial relationships that traditional screens cannot carry.

Objects can exist around a person.

Interfaces can be embedded in the environment.

Virtual characters can share the same table.

Training tasks can happen inside a simulated site.

Information can be organized by spatial layers.

People can collaborate inside the same mixed space.

These things are not notifications, subtitles, or a small card floating in front of your eyes.

These are the parts of spatial computing that deserve serious attention.

= Closing

I am not saying lightness is unimportant.

On the contrary, lightness is very important. Without it, spatial computing will struggle to enter daily life.

What I oppose is treating lightness as the only direction, treating heavier devices as historical baggage, and compressing every spatial experience into a small hint on a pair of glasses.

That is lazy.

Spatial computing should have light devices and heavy devices. It should have everyday entry points and high-fidelity terminals. It should have experiences you glance at, and experiences you enter into.

If the future only has lightweight glasses, what we get may not be the victory of spatial computing. It may be a low-end version of spatial computing after it has been cut down.

Smart companies should not kill the heavy path. They should redefine its place.

Lightweight glasses are responsible for the high-frequency entry point.

Heavy MR / VR is responsible for the content ceiling.

These two things were never in conflict.
