#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/life/2021/20210520.typ
// source_sha256: sha256:967efe2feaf537e300c3fc685a11c2dc34494f1d128b0cfc9abaf43b10583040

#show: main.with(
  title: "20210520",
  desc: [20210520],
  date: "2021-05-20",
  tags: (

    blog-tags.life,
  
  ),
  lang: "en",
  i18nKey: "life/2021/20210520",
  sourceLang: "zh",
  translationSourceHash: "sha256:967efe2feaf537e300c3fc685a11c2dc34494f1d128b0cfc9abaf43b10583040",
  translationStatus: "machine",
)

Why can others always be so happy, while I can never seem to find happiness? Is it because I care too much about what others think? Is it because I like to compare myself with others too much? Why do I always feel like an outsider, no matter what I do? Even when I am leading the effort?

Watching others move forward in life always makes me feel anxious, as if I am the only one standing still. The things I value seem worthless in the eyes of others, making me doubt what I do every day—Is my direction correct? Am I doing well enough?

These thoughts lead me to have a pessimistic outlook on the future, and this pessimism, in turn, constantly urges me, making my life feel like it is being forced forward against my will.

I hate this life, yet I feel powerless to change it.
