#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/life/2021/2021-year-review.typ
// source_sha256: sha256:f83890fda6e917e4920530d2901f164f9de4dfb972d3726343ef77b7ecf3441d

#show: main.with(
  title: "2021 Summary",
  desc: [2021 Summary],
  date: "2022-01-11",
  tags: (

    blog-tags.life,
  
  ),
  lang: "en",
  i18nKey: "life/2021/2021-year-review",
  sourceLang: "zh",
  translationSourceHash: "sha256:f83890fda6e917e4920530d2901f164f9de4dfb972d3726343ef77b7ecf3441d",
  translationStatus: "machine",
)

Unknowingly, I have been working for almost eight years.

Since the outbreak of the COVID-19 pandemic in early 2020, many things that were once taken for granted have changed around the world. Some items that were rarely used suddenly became necessities; international connections became difficult, and internal conflicts became more pronounced, affecting both developed and developing countries alike.

Amidst the not-so-intense internal conflicts and struggles, the quality of life for us ordinary people has visibly declined. The sense of division among different groups has grown stronger, with differences and disparities becoming the main theme, as if everyone has lost their empathy, returning to a dark age of survival of the fittest, where dignity and shame no longer matter. The ripples of the times have gradually turned into chaotic waves, and I, an ordinary person, feel powerless to stand at the forefront, merely drifting along with the tide, feeling the dust of the era settling on me.

Recalling the "Marshmallow Experiment" I once saw, although it may not be entirely accurate, my understanding is that the motivation for delayed gratification is built on a sense of security. What is delayed gratification? It is the belief that with effort, one can excel, achieve small successes, or even become wealthy; that one reaps what one sows; that as long as there are dreams, they can be realized. What is a sense of security? A stable job/income; a sound accountability system/compensation mechanism/prevention mechanism; the trust that comes from harmonious interpersonal relationships; a well-off family background/ample assets. In the past Chinese society, losing a sense of security might have meant merely losing the opportunity to realize an ideal life, blending in with the crowd; in today's society, losing a sense of security also means losing human dignity. As the wealth gap widens, various forms of discourse power become increasingly centralized, making it harder for the disadvantaged to get a second chance, both in practical terms and in widespread consciousness.

Whenever I see some media and celebrities online clearly inputting values, I feel a deep sense of powerlessness—powerless to change, unwilling to comply. Is the world inevitably heading towards a winner-takes-all situation? Or is it only in China? Economic capability is increasingly becoming the only standard by which a person is measured; I wonder how those who have lost their passion will cope with situations that are thankless and altruistic but not beneficial to themselves.

However, putting these aside, I still wish to be a hopeful person. Since this world can operate normally for a day, what reason do I have not to strive towards my dreams for a day?

Work has gradually become stable, providing ample rest time, allowing me to finally have the energy and conditions to study game development and various hobbies;

I have moved into a new house, gaining the motivation to shape it into a place I like;

I visited Kunming, Yunnan for the first time, adding another piece to my footprint map;

I found beautiful places in the city I live in, further broadening my thinking;

My programming skills continue to improve, and I have not given up on my persistence;

I have met people who understand me, and it turns out that the tacit understanding between people is such a wonderful feeling, and life is not just about fighting alone.

= In the new year, I make a wish:

1. To exercise, as a good body can extend the length of my efforts towards my dreams.
2. For the COVID-19 pandemic to end soon, allowing the world to connect closely again.
3. To continue striving towards my dreams, at least not to stand still.
4. To create more beautiful memories.
