#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2017/ml-course-summary-review.typ
// source_sha256: sha256:270c39d68fbfe3e4f03ff93b3d50a44591fb7ef9299890ad4f8ea82d82a5a5e8

#show: main.with(
  title: "Summary of the Machine Learning Course",
  desc: [A summary of learning from Andrew Ng's Machine Learning course on Coursera.],
  date: "2017-07-19",
  tags: (

    blog-tags.ml,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2017/ml-course-summary-review",
  sourceLang: "zh",
  translationSourceHash: "sha256:270c39d68fbfe3e4f03ff93b3d50a44591fb7ef9299890ad4f8ea82d82a5a5e8",
  translationStatus: "machine",
)

Unknowingly, I have finally completed Andrew Ng's Machine Learning course on Coursera after a sporadic pace. From having only a simple interest and lack of understanding in machine learning, I now have a general concept and thought process about it in my mind. This course has helped me get to where I am now.

Andrew Ng explained various machine learning models and their simple implementation methods in a very easy-to-understand way. I have never found such comprehensible tutorials in my country; most current tutorials start from mathematical reasoning and definitions, with various formula derivations that leave someone like me completely bewildered, possibly giving up before even starting.

The course content is basically divided into three parts:

- Supervised Learning
- Unsupervised Learning
- Algorithm Debugging and Optimization

In `Supervised Learning`, the models and algorithms introduced include:

- Linear Regression & Gradient Descent & Normal Equation
- Logistic Regression (Binary & Multiclass)
- Neural Networks & Backpropagation
- Support Vector Machines & Kernel Functions

In `Unsupervised Learning`, the models and algorithms introduced include:

- K-Means Algorithm & Principal Component Analysis (PCA)
- Anomaly Detection & Normal Distribution/Joint Normal Distribution
- Recommendation Systems & Collaborative Filtering Algorithms

During the explanation of these contents, the course also covered many useful/common techniques and methods;

- Using Regularization to prevent overfitting
- Using Random Initialization in Neural Networks and K-Means Algorithm
- Evaluating the current performance and existing problems of the model by plotting various relationship curves (iterations - cost function, etc.)
- Using precision/recall to assess the training effectiveness of the model
- Using Stochastic Gradient Descent/Mini-Batch Gradient Descent to reduce computation
- Using methods like MapReduce to enable the model to run on distributed architectures
- How to select features
- How to choose the appropriate algorithm/model in specific situations (product of normal distributions vs joint normal distribution)

During the learning process, I implemented logistic regression and neural networks using TensorFlow, encountered and filled some pitfalls, and gained a deeper understanding of these contents. I hope to continue persevering and move towards true artificial intelligence.
