#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2017/ml-logistic-regression-review.typ
// source_sha256: sha256:96177ed58d74ef37e5652d2f7028f31f6ae925a74e3e357b4c7123aabfdb07ba

#show: main.with(
  title: "Machine Learning - Summary of Logistic Regression Learning",
  desc: [Machine Learning - Summary of Logistic Regression Learning],
  date: "2017-04-26",
  tags: (

    blog-tags.ml,
    blog-tags.programming,
  
  ),
  lang: "en",
  i18nKey: "study/2017/ml-logistic-regression-review",
  sourceLang: "zh",
  translationSourceHash: "sha256:96177ed58d74ef37e5652d2f7028f31f6ae925a74e3e357b4c7123aabfdb07ba",
  translationStatus: "machine",
)

Finally completed the third week of Andrew's Machine Learning course on Coursera.

The third week mainly discussed the concept and implementation of *Logistic Regression*.

In the course, Andrew mentioned that logistic regression is primarily used to solve *classification problems*, where the final results we need are several discrete values. For example, in a binary classification problem of _yes/no_, it can be viewed as taking values —

- *Yes:* $y=1$
- *No:* $y=0$

In this context, unlike the previous chapter on *Linear Regression*, the *hypothesis function* here uses the *Sigmoid* function, which aims to represent the probability that a sample belongs to one of the categories:

$ P(y=1|x;theta) = h_theta (x) = g(theta^T x) $

$ g(z) = frac(1, 1+e^(-z)) $

The graph of the function $g(z)$ is as follows:

#figure(image("/public/assets/img/2017/04/006tNc79ly1fezs1eute2j30hk0bo3z6.jpg"), caption: "Graph of the Sigmoid Function")

It can be seen that the range of this function is $[0, 1]$, which exactly matches the definition of probability. Therefore, we define:

$ y = cases(
  1 &quad h_theta (x) >= 0.5,
  0 &quad h_theta (x) < 0.5,
) $

From the above graph, we can see that when $h_theta (x) >= 0.5$, $z >= 0$, which means $theta^T x >= 0$.

To satisfy this condition (i.e., $theta^T x >= 0$), we introduce the concept of *Decision Boundary*. Taking the example from the course:

#figure(image("/public/assets/img/2017/05/006tNc79ly1fezv6qgjh4j30ik0fw0uz.jpg"))

In the case of two features ($x_1, x_2$), let $z = theta_0 + theta_1 x_1 + theta_2 x_2 = 0$, which can be represented by a straight line (decision boundary) in the above graph, separating samples belonging to two categories.

In this example, according to the formula above, we can define:

#quote(block: true)[
When $theta_0 + theta_1 x_1 + theta_2 x_2 >= 0$, we predict $y = 1$; when $theta_0 + theta_1 x_1 + theta_2 x_2 < 0$, we predict $y = 0$
]

The *goal* of logistic regression is to adjust $theta$ so that this line can separate the two types of samples with minimal error, allowing predictions for new samples.

To obtain the required $theta$, we introduce the concept of *Cost Function*, denoted as $J(theta)$.

Unlike the cost function in linear regression, using it directly would result in $J(theta)$ being a non-convex function, which cannot guarantee convergence to a global optimum:

#figure(image("/public/assets/img/2017/04/006tNc79ly1fezvqbwo05j30oq0fswfl.jpg"))

Therefore, to ensure that the cost function $J(theta)$ can achieve a global minimum through iteration, we define the logistic regression's $J(theta)$ in the following form: _($m$ is the number of samples, same below)_

$ J(theta) = frac(1, m) sum_(i=1)^m "Cost"(h_theta (x), y) $

$ "Cost"(h_theta (x), y) = cases(
  -log(h_theta (x)) &quad y = 1,
  -log(1 - h_theta (x)) &quad y = 0,
) $

When $y = 0$, the graph of $"Cost"(h_theta (x), y)$ is shown below:

#figure(image("/public/assets/img/2017/04/006tNc79ly1fezwnnpeuuj30nk0keta5.jpg"))

It can be seen that when $h_theta (x) = 0$, the value of the cost function $J(theta)$ is also 0, meaning there is no cost, which is completely consistent.

To ensure that the final hypothesis function $h_theta (x)$ can reasonably predict the results of subsequent samples, we need to continuously iterate $theta$ to achieve a reasonable minimum value for the cost function $J(theta)$. To make this process feasible, we combine the above piecewise function into the following form:

$ "Cost"(h_theta (x), y) = -y dot log(h_theta (x)) - (1 - y) log(1 - h_theta (x)) $

$ J(theta) = -frac(1, m) lr([ sum_(i=1)^m y^((i)) log(h_theta (x^((i)))) + (1 - y^((i))) log(1 - h_theta (x^((i)))) ]) $

Our goal is to find the value of $min J(theta)$ that minimizes $theta$ and substitute it into the hypothesis function $h_theta (x)$, so that when we obtain a new sample $x$, we can use the following formula to derive the prediction result:

$ h_theta (x) = frac(1, 1 + e^(-theta^T x)) $

To achieve $min_theta J(theta)$, we continue to use the gradient descent method learned previously: _($j$ represents the feature index in the sample, same below)_

$ theta_j = theta_j - alpha frac(partial, partial theta_j) J(theta) $

Where $theta_j$ must be _updated simultaneously_.

After taking the partial derivative, the gradient descent formula obtained is:

$ theta_j = theta_j - alpha sum_(i=1)^m (h_theta (x^((i))) - y^((i))) x_j^((i)) $

In `Matlab` and `Octave`, we can implement the gradient descent algorithm without manual coding, as the software has a built-in iterative function `fminunc` that can help us automatically perform iterative calculations, and we only need to provide the values of the following two formulas:

- $J(theta)$
- $frac(partial, partial theta_j) J(theta)$ $quad j = 0, 1, ..., n$

The calling format of the `fminunc` function is as follows:

```octave
[theta, cost] = fminunc(@(t)(costFunction(t, X, y)), initial_theta, options);
```

Where:

- _costFunction_: a function we implement to calculate the values of $J(theta)$ and $frac(partial, partial theta_j) J(theta)$
- _initial\_theta_: the initial $theta$ vector
- _options_: used to specify the iteration method of the `fminunc` function
- _theta_: the resulting $theta$ value after iteration
- _cost_: the computed value of `costFunction` when obtaining the result $theta$ value

At this point, we can implement binary classification problems using logistic regression on datasets.

For problems that require distinguishing more than two categories, we can _decompose the problem into multiple binary classifications_, implementing a hypothesis function $h_theta (x)$ for each category. Using the example from the course:

#figure(image("/public/assets/img/2017/04/006tNc79ly1ff0505j5irj30l60i2jsa.jpg"))

At this point, different shapes represent different classifications.

$ h_theta^((i)) x = P(y=i | x; theta) quad (i = 1, 2, 3) $

Ultimately, we need to derive three hypothesis functions. When predicting new samples, we only need to substitute the samples into the three hypothesis functions and take the maximum value from the computed results.

In the initial example, we could distinguish different categories of samples with a straight line:

#figure(image("/public/assets/img/2017/05/006tNc79ly1fezv6qgjh4j30ik0fw0uz.jpg"))

However, in other problems, there may be such sample distributions:

#figure(image("/public/assets/img/2017/05/006tNc79ly1ff07vikxvbj30si0m6dhz.jpg"))

At this time, the decision boundary is an irregular curve, and we need to modify the decision boundary to a form similar to the following:

$ z = theta_0 + theta_1 x_1 + theta_2 x_2 + theta_3 x_1^2 + theta_4 x_2^2 $

In this case, the number of features increases to 4 ($x_1, x_2, x_1^2, x_2^2$). As the number of features increases, the decision boundary may take on this shape:

#figure(image("/public/assets/img/2017/04/006tNc79ly1ff0do3wk0kj30sk0mw40s.jpg"))

This situation is clearly not what we want, so it is referred to as _overfitting_. Therefore, we need to avoid this situation. The course introduced a method that can effectively address this situation, called _regularization_. The principle of regularization is to add a term to the cost function. The form of the cost function $J(theta)$ after using regularization is:

$ J(theta) = -lr([ frac(1, m) sum_(i=1)^m y^((i)) log(h_theta (x^((i)))) + (1 - y^((i))) log(1 - h_theta (x^((i)))) ]) + frac(lambda, 2m) sum_(j=1)^n theta_j^2 $

_Note: The summation for the regularization term starts from $j=1$, meaning $theta_0$ does not participate in regularization._

Here, the selection of $lambda$ is also important.

The final form of the gradient descent algorithm after using regularization is:

$ theta_0 = theta_0 - alpha frac(1, m) sum_(i=1)^m (h_theta (x^((i))) - y^((i))) x_0^((i)) $

$ theta_j &= theta_j - alpha lr([ frac(1, m) sum_(i=1)^m (h_theta (x^((i))) - y^((i))) x_j^((i)) + frac(lambda, m) theta_j ]) \
&= theta_j (1 - alpha frac(lambda, m)) - alpha frac(1, m) sum_(i=1)^m (h_theta (x^((i))) - y^((i))) x_j^((i)) $

$ (j = 1, 2, 3, ..., n) $

Solving the above formulas that use the regularization method can effectively address the overfitting problem in logistic regression.

That's all.
