#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/study/2017/music-theory-pentatonic-scale.typ
// source_sha256: sha256:9f77cfb6a95eb1a06bb2d81a9374b59a419605dfc293954f9cf9d5d05eef7695

#show: main.with(
  title: "Fundamentals of Music Theory - Pentatonic Scale",
  desc: [Basic knowledge of the pentatonic scale, including the characteristics and progressions of the five modes: Gong, Shang, Jiao, Zhi, and Yu.],
  date: "2017-06-11",
  tags: (

    blog-tags.music-theory,
  
  ),
  lang: "en",
  i18nKey: "study/2017/music-theory-pentatonic-scale",
  sourceLang: "zh",
  translationSourceHash: "sha256:9f77cfb6a95eb1a06bb2d81a9374b59a419605dfc293954f9cf9d5d05eef7695",
  translationStatus: "machine",
)

The pentatonic scale is a mode that consists of only five notes that continuously cycle. Starting from C, the pentatonic scale is:

*C - D - E - G - A*

This corresponds to what we commonly refer to as *Gong, Shang, Jiao, Zhi, Yu*, sung as

*do - re - mi - sol - la*

What mode is this, and which note is the tonic:

- The tonic of the C Gong mode is *C*, sung as *do*;
- The tonic of the D Jiao mode is *D*, sung as *mi*;
- The tonic of the G Yu mode is *G*, sung as *la*;
- ......

From the scale, it can be seen that compared to the familiar *do re mi fa sol la si*, the pentatonic scale lacks the *IV* and *VII* degrees (i.e., *fa* and *si*), missing half steps and augmented fourths/diminished fifths, and is constructed from *major seconds* (do-re, sol-la, etc.) and *minor thirds* (mi-sol, la-do), forming the basic pentatonic tonality.

The five pentatonic modes of Gong, Shang, Jiao, Zhi, and Yu have different arrangements and characteristics in composition:

The characteristic of the *Gong mode* is the *major third* above the tonic (i.e., *do-mi*), emphasizing the progression of *do-mi (mi-do)*, with the three notes *sol-la-do* often *appearing in groups*, while the three notes *do-mi-sol* often *do not appear in groups*, meaning progressions like mi-do/sol-mi-do do not occur, but rather transition through the addition of *re* or *la*, ultimately returning to the tonic do, such as la-sol-mi-re-do.

The characteristic of the *Zhi mode* is the *perfect fourth* and *major sixth* above the tonic (i.e., *so-do*, *so-mi*), often starting with the *Gong chord* (tonic being Gong), with the first half of the phrase usually stopping at re, but ultimately stopping at the tonic sol; the Zhi mode also frequently features descending progressions of *do-la-sol*, as well as phrases like *re-mi-la*.

The characteristic of the *Shang mode* is the *major second* and *minor seventh* above the tonic (i.e., *re-me*, *re-do*), starting and ending on re, with progressions like *re-mi-sol* often appearing, and the ending typically resolving to the final tone re through *mi* or *do*.

The characteristic of the *Yu mode* is the *minor third* and *perfect fifth* above the tonic (i.e., *la-do*, *la-mi*), also starting with the tonic la and ending with la, emphasizing the progression of *la-do-mi*, while also frequently featuring progressions like *mi-re-do (-la)*.

The characteristic of the *Jiao mode* is the *minor sixth* above the tonic (i.e., *mi-do*), starting with the Gong chord and ending with the Jiao major third chord (*mi-sharp sol-si*); it emphasizes the appearance of mi, often stopping on mi; progressions like *la-sol-mi* are common.

In the pentatonic scale, the *I degree* (tonic) is the *most stable*, and should be emphasized in the melody; the *IV* and *V degrees* are *less stable*, serving to support the tonic; the remaining degrees are unstable, tending to progress to the aforementioned stable degrees, and this process of moving from instability to stability forms the outline of the melody.
