#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/life/2017/2017-year-review.typ
// source_sha256: sha256:00460152f04504db49148ffe5fcb649ba1d62eda0ab62e6a979bcbb4fa45a217

#show: main.with(
  title: "2017 Summary",
  desc: [2017 Summary],
  date: "2017-12-31",
  tags: (

    blog-tags.life,
  
  ),
  lang: "en",
  i18nKey: "life/2017/2017-year-review",
  sourceLang: "zh",
  translationSourceHash: "sha256:00460152f04504db49148ffe5fcb649ba1d62eda0ab62e6a979bcbb4fa45a217",
  translationStatus: "machine",
)

2017 was another year of being unproductive. Upon reflection, it seems I have drifted further away from my ideals. 🙄

During the Spring Festival this year, at a reunion with high school classmates, my workplace suddenly required attendance, so I had to leave in a hurry.

After the Spring Festival, I passed the initial exam for graduate school and began reviewing for the re-examination. I passed the re-examination in April, marking the end of my time working at the company. In the second half of the year, I returned to school, experiencing a different kind of military academy life. It was difficult to go out and take leave, and even during holidays, I could only stay put. Fortunately, the semester was relatively easy, and as I write this, there are only two weeks left until winter break. I also won an award in the national mathematical modeling competition, which can be considered a personal achievement.

At the beginning of the year, I purchased the deeplearning.ai machine learning series courses on Coursera. I have now completed the first two parts, and I am currently working on the third part. Seeing myself complete the courses and obtain certificates gives me a sense of accomplishment, especially since I haven't had many things I fully committed to in the past few years, like learning the flute. 😑

My physical condition has been deteriorating over time; my lumbar disc herniation seems to be worsening. In the new year, I hope to adjust my mindset and exercise my body, at least not let it become a burden on my brain.

In the new year, my current job is facing reforms, and there may finally be an opportunity to escape my boring life and pursue the life I want. My personality may not suit the characteristics of Chinese national conditions, so in the new year, I will focus on the possibility of studying and living abroad. I will learn English, take the TOEFL, continue learning programming knowledge, find ways to publish papers, learn a minor language, and understand matters related to studying abroad and school information; I will also continue to try to persist in learning the flute and studying music knowledge.

As the New Year's bell is about to ring, I hope that in the new year, I can still stay true to myself and not let this boring life turn me into the person I once disliked; I hope that those around me can pursue the beauty in their hearts and find the meaning of their lives.
