#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/life/2017/europe-folk-music-playlist.typ
// source_sha256: sha256:0b0c17e826024626c945d1b5fe70ef248046b3982c3d36fdc828cd5a332e2c06

#show: main.with(
  title: "European Folk Playlist",
  desc: [European Folk Playlist],
  date: "2017-08-01",
  tags: (

    blog-tags.music-theory,
    blog-tags.misc,
  
  ),
  lang: "en",
  i18nKey: "life/2017/europe-folk-music-playlist",
  sourceLang: "zh",
  translationSourceHash: "sha256:0b0c17e826024626c945d1b5fe70ef248046b3982c3d36fdc828cd5a332e2c06",
  translationStatus: "machine",
)

#link("https://music.163.com/#/playlist?id=7288440")[Listen to this playlist on NetEase Cloud Music]
