#import "/templates/blog.typ": *
#import "/templates/enums.typ": *

// @generated by scripts/i18n/translate.mjs
// prompt_version: wonderland-i18n-v1
// model: gpt-4o-mini
// source: content/article/zh/meta/2020/new-theme-wonderland.typ
// source_sha256: sha256:1762792884fed0f6270ed3d26c914068f4bb5c8476c107273615fcdc21cf76a4

#show: main.with(
  title: "Wonderland - Blog Theme, Redesigned",
  desc: [Create a new blog theme with Hugo: Wonderland],
  date: "2020-01-09",
  tags: (

    blog-tags.blog,
    blog-tags.theme,
  
  ),
  lang: "en",
  i18nKey: "meta/2020/new-theme-wonderland",
  sourceLang: "zh",
  translationSourceHash: "sha256:1762792884fed0f6270ed3d26c914068f4bb5c8476c107273615fcdc21cf76a4",
  translationStatus: "machine",
)

My blogging solution is as changeable as my emotions, and now I've returned to static web hosting #link("https://gohugo.io")[Hugo]. Indeed, the hustle is temporary, but peace of mind is everlasting.

#link("https://bulma.io")[Bulma] is a CSS library with beautiful default styles and a sensible style organization system, which I really like. So I based this new simple theme on this library.

Since it’s not fully completed yet, there are still many issues. For example, as I write this article, the menu in the upper right corner is still a hardcoded fake menu...

I can't guarantee that this theme will be completed in the end, after all, the urge to tinker hasn't completely died. Who knows when a new and better blogging solution will appear? I wouldn't hesitate to switch over and start tinkering again.

Simple, colorful, clear. Just make do with it.
